using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Mono.GridEdgeMarker; // Mono
using Content.Shared.Maps; // Mono
using Content.Shared.Shuttles.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map; // Mono
using Robust.Shared.Map.Components;
using Robust.Shared.Physics;
using Robust.Shared.Threading;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Vector2 = System.Numerics.Vector2;

namespace Content.Client.Shuttles.UI;

/// <summary>
/// Provides common functionality for radar-like displays on shuttle consoles.
/// </summary>
[GenerateTypedNameReferences]
[Virtual]
public partial class BaseShuttleControl : MapGridControl
{
    // Triad: removed — vertices are cached in grid-local space and transformed by the draw handle, so
    // there is no per-frame vertex pass left for the parallel manager to run.
    /*
    [Dependency] private IParallelManager _parallel = default!;
    */
    // End Triad
    [Dependency] private ITileDefinitionManager _tileDef = default!; // Mono
    protected readonly EntityLookupSystem _lookup; // Mono
    protected readonly SharedMapSystem Maps;

    protected readonly Font Font;

    // Triad: removed — superseded by the cached grid-local vertex buffers below.
    /*
    private GridDrawJob _drawJob;
    */
    // End Triad

    // Cache grid drawing data as it can be expensive to build
    public readonly Dictionary<EntityUid, GridDrawData> GridData = new();

    // Per-draw caching
    private readonly Dictionary<Vector2i, IReadOnlyList<Vector2>> _gridTileList = new(); // Mono // Triad: stores the vertex loop rather than the whole tile definition
    // Triad: removed — the per-direction edge table moved into RadarGridGeometry, which stores
    // directed segments instead of Box2. See that file for why the Box2 form was wrong.
    /*
    // Mono - tile mapped to vector lying along each of 4 directions, if any
    private readonly Dictionary<Vector2i, Box2?[]> _gridDirEdges = new();
    */
    // End Triad
    // stores inward directions of borders
    private readonly List<RadarGridGeometry.Segment> _edges = new(); // Triad: tuple -> Segment
    private readonly HashSet<Entity<GridEdgeMarkerComponent>> _edgeMarkers = new();

    private EntityQuery<TransformComponent> _xformQuery; // Mono

    // Triad: scratch buffer for the tile triangles, reused across rebuilds.
    private readonly List<Vector2> _triangles = new();

    /// <summary>
    /// Grids retained before <see cref="PruneGridData"/> starts releasing stale ones. Comfortably above
    /// what any one view holds, so the common case never walks the dictionary.
    /// </summary>
    private const int GridDataSoftCap = 64;

    /// <summary>
    /// How long a grid's geometry survives after it was last drawn.
    /// </summary>
    private static readonly TimeSpan GridDataRetention = TimeSpan.FromSeconds(15);

    /// <summary>
    /// How often the retention sweep is allowed to run.
    /// </summary>
    private static readonly TimeSpan GridDataPruneInterval = TimeSpan.FromSeconds(5);

    /// <summary>
    /// Shortest gap between two rebuilds of the same grid. INTERIM: this exists only because a rebuild
    /// currently costs the whole grid; per-chunk geometry should shrink or remove it. See DrawGrid.
    /// </summary>
    private static readonly TimeSpan RebuildCoalesceInterval = TimeSpan.FromMilliseconds(250);

    private TimeSpan _nextPrune;

    /// <summary>
    /// Stock white texture for the untextured primitive draws. Held because the static accessor goes
    /// through IoC on every read, and this sits in the per-frame path.
    /// </summary>
    private readonly Texture _white;

    /// <summary>
    /// Most vertices handed to a single DrawPrimitives call. Clyde copies each call into one batch vertex
    /// buffer of MaxBatchQuads * 4 = 65,532 entries, and a span that does not fit throws out of the copy,
    /// killing the rest of the control's draw. A VGRoid's buffer alone is several times that. Chosen as a
    /// clean multiple of both primitive strides (2 and 3) with headroom below the real cap.
    /// </summary>
    private const int BatchVertices = 60_000;
    // End Triad

    // Triad: removed — _allVertices held the per-frame transformed copy of the geometry, which the
    // grid-local caching makes unnecessary. Its BatchVertices sized batches against the flat-colour
    // overload's stackalloc; the replacement constant below is sized against Clyde's batch buffer,
    // which is the cap that binds on the DrawVertexUV2DColor path.
    /*
    private Vector2[] _allVertices = Array.Empty<Vector2>();

    private const int BatchVertices = 3 * 4096;
    */
    // End Triad

    // Triad: removed — written in the constructor and never read.
    /*
    private (DirectionFlag, Vector2i)[] _neighborDirections;
    */
    // End Triad

    public BaseShuttleControl() : this(32f, 32f, 32f)
    {
    }

    public BaseShuttleControl(float minRange, float maxRange, float range) : base(minRange, maxRange, range)
    {
        RobustXamlLoader.Load(this);
        Maps = EntManager.System<SharedMapSystem>();
        _lookup = EntManager.System<EntityLookupSystem>(); // Mono
        _xformQuery = EntManager.GetEntityQuery<TransformComponent>(); // Mono
        Font = new VectorFont(IoCManager.Resolve<IResourceCache>().GetResource<FontResource>("/Fonts/NotoSans/NotoSans-Regular.ttf"), 12);

        _white = Texture.White; // Triad

        // Triad: removed — _drawJob fed the per-frame transform pass, and _neighborDirections was
        // populated here and never read.
        /*
        _drawJob = new GridDrawJob()
        {
            ScaledVertices = _allVertices,
        };

        _neighborDirections = new (DirectionFlag, Vector2i)[4];

        for (var i = 0; i < 4; i++)
        {
            var dir = (DirectionFlag) Math.Pow(2, i);
            var dirVec = dir.AsDir().ToIntVec();
            _neighborDirections[i] = (dir, dirVec);
        }
        */
        // End Triad
    }

    protected void DrawData(DrawingHandleScreen handle, string text)
    {
        var coordsDimensions = handle.GetDimensions(Font, text, 1f);
        const float coordsMargins = 5f;

        handle.DrawString(Font,
            new Vector2(coordsMargins, PixelHeight) - new Vector2(0f, coordsDimensions.Y + coordsMargins),
            text,
            Color.FromSrgb(IFFComponent.SelfColor));
    }

    protected void DrawCircles(DrawingHandleScreen handle)
    {
        // Equatorial lines
        var gridLines = Color.LightGray.WithAlpha(0.01f);

        // Each circle is this x distance of the last one.
        const float EquatorialMultiplier = 2f;

        var minDistance = MathF.Pow(EquatorialMultiplier, EquatorialMultiplier * 1.5f);
        var maxDistance = MathF.Pow(2f, EquatorialMultiplier * 6f);
        var cornerDistance = MathF.Sqrt(WorldRange * WorldRange + WorldRange * WorldRange);

        var origin = MidPointVector; // Mono

        for (var radius = minDistance; radius <= maxDistance; radius *= EquatorialMultiplier)
        {
            if (radius > cornerDistance)
                continue;

            var color = Color.ToSrgb(gridLines).WithAlpha(0.05f);
            var scaledRadius = MinimapScale * radius;
            var text = $"{radius:0}m";
            var textDimensions = handle.GetDimensions(Font, text, UIScale);

            handle.DrawCircle(origin, scaledRadius, color, false);
            handle.DrawString(Font, ScalePosition(new Vector2(0f, -radius)) - new Vector2(0f, textDimensions.Y), text, UIScale, color);
        }

        const int gridLinesRadial = 8;

        for (var i = 0; i < gridLinesRadial; i++)
        {
            Angle angle = (Math.PI / gridLinesRadial) * i;
            // TODO: Handle distance properly.
            var aExtent = angle.ToVec() * ScaledMinimapRadius * 1.42f;
            var lineColor = Color.MediumSpringGreen.WithAlpha(0.02f);
            handle.DrawLine(origin - aExtent, origin + aExtent, lineColor);
        }
    }

    // Frontier Corvax: north line drawing
    protected void DrawNorthLine(DrawingHandleScreen handle, Angle angle)
    {
        var origin = MidPointVector;
        var aExtent = (angle - Math.Tau / 4).ToVec() * ScaledMinimapRadius * 1.42f;
        var lineColor = Color.Red.WithAlpha(0.1f);
        handle.DrawLine(origin, origin + aExtent, lineColor);
    }
    // End Frontier Corvax

    // Mono
    protected void DrawAzimuthScale(DrawingHandleScreen handle, Angle rotation)
    {
        const int azimuthMinorTickStepDegrees = 10;
        const int azimuthMajorTickInterval = 3;
        const int azimuthCardinalTickInterval = 9;
        const float edgeInset = 10f;
        const float tickInset = 4f;
        const float minorTickLength = 5f;
        const float majorTickLength = 9f;
        const float cardinalTickLength = 12f;
        const float labelPadding = 3f;
        const float labelOffset = tickInset + cardinalTickLength + labelPadding;
        const float regularLabelScale = 0.62f;
        const float cardinalLabelScale = 0.72f;

        var origin = MidPointVector;
        var viewportSize = new Vector2(PixelWidth, PixelHeight);

        var subtleGray = Color.FromHex("#676767");
        var northAccent = Color.FromHex("#7F7442");
        var eastAccent = Color.FromHex("#456273");
        var baseTickColor = subtleGray.WithAlpha(0.34f);
        var majorTickColor = subtleGray.WithAlpha(0.5f);
        var cardinalTickColor = subtleGray.WithAlpha(0.68f);
        var regularLabelColor = subtleGray.WithAlpha(0.76f);
        var cardinalLabelColor = subtleGray.WithAlpha(0.9f);
        var labelShadowColor = Color.Black.WithAlpha(0.36f);

        for (var step = 0; step < 360 / azimuthMinorTickStepDegrees; step++)
        {
            var degrees = step * azimuthMinorTickStepDegrees;
            var direction = GetAzimuthDirection(rotation, degrees);
            var isCardinal = step % azimuthCardinalTickInterval == 0;
            var isMajor = step % azimuthMajorTickInterval == 0;
            var isNorth = degrees == 0;
            var isEast = degrees == 90;
            var tickLength = isCardinal
                ? cardinalTickLength
                : isMajor
                    ? majorTickLength
                    : minorTickLength;

            if (!TryGetViewportEdgePoint(origin, direction, viewportSize, edgeInset, out var edgePoint, out var inwardNormal))
                continue;

            var outer = edgePoint + inwardNormal * tickInset;
            var inner = outer + inwardNormal * tickLength;
            var tickColor = isNorth
                ? northAccent.WithAlpha(0.58f)
                : isEast
                    ? eastAccent.WithAlpha(0.58f)
                    : isCardinal
                        ? cardinalTickColor
                        : isMajor
                            ? majorTickColor
                            : baseTickColor;
            handle.DrawLine(outer, inner, tickColor);
            if (isNorth)
            {
                var sideOffset = new Vector2(-inwardNormal.Y, inwardNormal.X) * 0.35f;
                handle.DrawLine(outer + sideOffset, inner + sideOffset, tickColor.WithAlpha(0.46f));
            }

            if (!isMajor)
                continue;

            var label = degrees.ToString();
            var labelScale = isCardinal ? cardinalLabelScale : regularLabelScale;
            var labelColor = isEast
                ? eastAccent.WithAlpha(0.76f)
                : isCardinal
                    ? cardinalLabelColor
                    : regularLabelColor;
            var labelSize = handle.GetDimensions(Font, label, labelScale);
            var labelPosition = GetEdgeLabelPosition(edgePoint, inwardNormal, labelSize, viewportSize, labelOffset);
            handle.DrawString(Font, labelPosition + new Vector2(1f, 1f), label, labelScale, labelShadowColor);
            handle.DrawString(Font, labelPosition, label, labelScale, labelColor);
        }
    }

    protected void DrawAzimuthRing(DrawingHandleScreen handle, Angle rotation)
    {
        const int azimuthMinorTickStepDegrees = 10;
        const int azimuthMajorTickInterval = 3;
        const int azimuthCardinalTickInterval = 9;
        const float ringInset = 16f;
        const float minorTickLength = 5f;
        const float majorTickLength = 9f;
        const float cardinalTickLength = 12f;
        const float labelPadding = 5f;
        const float regularLabelScale = 0.62f;
        const float cardinalLabelScale = 0.72f;

        var origin = MidPointVector;
        var radius = MathF.Max(8f, SizeFull * 0.5f - ringInset);

        var subtleGray = Color.FromHex("#676767");
        var northAccent = Color.FromHex("#7F7442");
        var eastAccent = Color.FromHex("#456273");
        var baseTickColor = subtleGray.WithAlpha(0.34f);
        var majorTickColor = subtleGray.WithAlpha(0.5f);
        var cardinalTickColor = subtleGray.WithAlpha(0.68f);
        var regularLabelColor = subtleGray.WithAlpha(0.76f);
        var cardinalLabelColor = subtleGray.WithAlpha(0.9f);
        var labelShadowColor = Color.Black.WithAlpha(0.36f);

        handle.DrawCircle(origin, radius, subtleGray.WithAlpha(0.12f), false);

        for (var step = 0; step < 360 / azimuthMinorTickStepDegrees; step++)
        {
            var degrees = step * azimuthMinorTickStepDegrees;
            var direction = GetAzimuthDirection(rotation, degrees);
            var isCardinal = step % azimuthCardinalTickInterval == 0;
            var isMajor = step % azimuthMajorTickInterval == 0;
            var isNorth = degrees == 0;
            var isEast = degrees == 90;
            var tickLength = isCardinal
                ? cardinalTickLength
                : isMajor
                    ? majorTickLength
                    : minorTickLength;

            var outer = origin + direction * radius;
            var inner = origin + direction * (radius - tickLength);
            var tickColor = isNorth
                ? northAccent.WithAlpha(0.58f)
                : isEast
                    ? eastAccent.WithAlpha(0.58f)
                    : isCardinal
                        ? cardinalTickColor
                        : isMajor
                            ? majorTickColor
                            : baseTickColor;
            handle.DrawLine(outer, inner, tickColor);
            if (isNorth)
            {
                var sideOffset = new Vector2(-direction.Y, direction.X) * 0.35f;
                handle.DrawLine(outer + sideOffset, inner + sideOffset, tickColor.WithAlpha(0.46f));
            }

            if (!isMajor)
                continue;

            var label = degrees.ToString();
            var labelScale = isCardinal ? cardinalLabelScale : regularLabelScale;
            var labelColor = isEast
                ? eastAccent.WithAlpha(0.76f)
                : isCardinal
                    ? cardinalLabelColor
                    : regularLabelColor;
            var labelSize = handle.GetDimensions(Font, label, labelScale);
            var labelPosition = origin + direction * (radius - tickLength - labelPadding) - labelSize * 0.5f;
            handle.DrawString(Font, labelPosition + new Vector2(1f, 1f), label, labelScale, labelShadowColor);
            handle.DrawString(Font, labelPosition, label, labelScale, labelColor);
        }
    }

    protected void DrawCompassOverlay(DrawingHandleScreen handle, Angle heading)
    {
        var compassCenter = new Vector2(44f, 44f);
        const float compassRadius = 24f;
        var ringColor = Color.White.WithAlpha(0.08f);
        var northColor = Color.FromHex("#776C43");
        var eastColor = Color.FromHex("#4C6572");
        handle.DrawCircle(compassCenter, compassRadius, ringColor, false);
        handle.DrawCircle(compassCenter, 2.5f, ringColor.WithAlpha(0.48f), true);

        DrawCompassNeedle(handle, compassCenter, compassRadius, GetAzimuthDirection(heading, 0f), "N", northColor);
        DrawCompassNeedle(handle, compassCenter, compassRadius * 0.82f, GetAzimuthDirection(heading, 90f), "E", eastColor);
    }

    private void DrawCompassNeedle(
        DrawingHandleScreen handle,
        Vector2 compassCenter,
        float radius,
        Vector2 direction,
        string label,
        Color color)
    {
        var tip = compassCenter + direction * radius;
        var tail = compassCenter - direction * (radius * 0.35f);
        DrawArrowLine(handle, tail, tip, color.WithAlpha(0.58f), 6f);

        var labelSize = handle.GetDimensions(Font, label, 0.9f);
        var labelPosition = tip + direction * 6f - new Vector2(labelSize.X * 0.5f, labelSize.Y * 0.5f);
        handle.DrawString(Font, labelPosition, label, 0.9f, color.WithAlpha(0.7f));
    }

    private static void DrawArrowLine(
        DrawingHandleScreen handle,
        Vector2 start,
        Vector2 end,
        Color color,
        float headLength)
    {
        var direction = end - start;
        if (direction.LengthSquared() <= 0.001f)
            return;

        direction = Vector2.Normalize(direction);
        var left = new Vector2(-direction.Y, direction.X);
        handle.DrawLine(start, end, color);
        handle.DrawLine(end, end - direction * headLength + left * (headLength * 0.45f), color);
        handle.DrawLine(end, end - direction * headLength - left * (headLength * 0.45f), color);
    }

    private static bool TryGetViewportEdgePoint(
        Vector2 origin,
        Vector2 direction,
        Vector2 viewportSize,
        float inset,
        out Vector2 edgePoint,
        out Vector2 inwardNormal)
    {
        edgePoint = default;
        inwardNormal = default;

        if (direction.LengthSquared() <= 0.001f)
            return false;

        direction = Vector2.Normalize(direction);
        var min = new Vector2(inset, inset);
        var max = viewportSize - min;
        if (max.X <= min.X || max.Y <= min.Y)
            return false;

        var tx = direction.X > 0f
            ? (max.X - origin.X) / direction.X
            : direction.X < 0f
                ? (min.X - origin.X) / direction.X
                : float.PositiveInfinity;
        var ty = direction.Y > 0f
            ? (max.Y - origin.Y) / direction.Y
            : direction.Y < 0f
                ? (min.Y - origin.Y) / direction.Y
                : float.PositiveInfinity;

        var t = Math.Min(tx, ty);
        if (!float.IsFinite(t) || t <= 0f)
            return false;

        edgePoint = origin + direction * t;

        if (tx < ty)
            inwardNormal = direction.X > 0f ? -Vector2.UnitX : Vector2.UnitX;
        else
            inwardNormal = direction.Y > 0f ? -Vector2.UnitY : Vector2.UnitY;

        return true;
    }

    private static Vector2 GetEdgeLabelPosition(
        Vector2 edgePoint,
        Vector2 inwardNormal,
        Vector2 labelSize,
        Vector2 viewportSize,
        float offset)
    {
        var anchor = edgePoint + inwardNormal * offset;
        Vector2 requested;
        if (Math.Abs(inwardNormal.X) > Math.Abs(inwardNormal.Y))
        {
            requested = inwardNormal.X > 0f
                ? new Vector2(anchor.X, anchor.Y - labelSize.Y * 0.5f)
                : new Vector2(anchor.X - labelSize.X, anchor.Y - labelSize.Y * 0.5f);
        }
        else
        {
            requested = inwardNormal.Y > 0f
                ? new Vector2(anchor.X - labelSize.X * 0.5f, anchor.Y)
                : new Vector2(anchor.X - labelSize.X * 0.5f, anchor.Y - labelSize.Y);
        }

        var minPosition = new Vector2(offset, offset);
        var maxPosition = viewportSize - labelSize - minPosition;
        return Vector2.Clamp(requested, minPosition, maxPosition);
    }

    private static Vector2 GetAzimuthDirection(Angle baseAngle, float azimuthDegrees)
    {
        var angle = baseAngle + Angle.FromDegrees(azimuthDegrees);
        var radians = (float) angle.Theta - MathF.PI / 2f;
        return new Vector2(MathF.Cos(radians), MathF.Sin(radians));
    }
    // End Mono

    // Triad: the geometry is cached in GRID-LOCAL space and the grid-to-view matrix is pushed onto the
    // draw handle, so the vertices themselves never move. That removes the per-frame transform pass, and
    // the cached buffers go to the DrawVertexUV2DColor overload, which does not stackalloc. It is NOT
    // size-unlimited though: each call is copied into Clyde's fixed batch vertex buffer, so the draw is
    // still sliced by DrawBatched to stay under that cap.
    protected void DrawGrid(DrawingHandleScreen handle, Matrix3x2 gridToView, Entity<MapGridComponent> grid, Color color, float alpha = 0.01f)
    {
        var gridData = GridData.GetOrNew(grid.Owner);
        gridData.LastDrawn = Timing.RealTime;

        // Built is checked separately from the tick: a grid whose tiles have not changed since it was
        // created reports tick zero, which never compares as newer, and keying off an empty vertex buffer
        // instead would rebuild a genuinely empty grid on every single frame.
        var stale = gridData.LastBuild < grid.Comp.LastTileModifiedTick;

        // Triad: INTERIM MITIGATION — supersede with chunked geometry, do not treat as the fix.
        //
        // A rebuild re-decomposes the WHOLE grid, measured at ~110 ms for a 33k-tile VGRoid, and the
        // trigger is "any tile changed since last time". Tile changes arrive spread across ticks rather
        // than in one batch: dungeon generation runs on a job queue budgeted at 2 ms per tick, and sustained
        // hull damage looks the same from here. So the client is asked for a ~110 ms rebuild in response to
        // every ~2 ms of server work, roughly 55:1, and it simply cannot keep up. That is why a generating
        // asteroid's outline trails the terrain by seconds.
        //
        // Coalescing bounds the damage without deciding anything structural: a grid that is actively
        // changing rebuilds at most ~4x/sec instead of ~30x, and a static grid is unaffected because it
        // rebuilds once and never goes stale again. The cost is that the outline can lag reality by up to
        // the interval while tiles are in flux, which is not perceptible during generation or a firefight.
        // Nothing is dropped: stale stays true until a rebuild actually happens, so the final state is
        // always picked up on the first draw past the interval.
        //
        // The real fix is per-chunk geometry, so a tile edit re-decomposes ~256 tiles instead of 33,069.
        // Once that lands this interval should shrink or go away entirely.
        if (!gridData.Built || (stale && Timing.RealTime >= gridData.NextRebuild))
        {
            RebuildGridGeometry(grid, gridData);
            gridData.LastBuild = grid.Comp.LastTileModifiedTick;
            gridData.Built = true;
            gridData.NextRebuild = Timing.RealTime + RebuildCoalesceInterval;
        }
        // End Triad

        if (gridData.VertexCount == 0)
        {
            PruneGridData();
            return;
        }

        // The flat-colour overloads fold Modulate in for us; this one does not, so bake it.
        var fill = color.WithAlpha(alpha) * handle.Modulate;
        var line = color * handle.Modulate;

        if (gridData.CachedFill != fill || gridData.CachedLine != line)
            Recolor(gridData, fill, line);

        var previous = handle.GetTransform();
        handle.SetTransform(gridToView * previous);

        DrawBatched(handle, DrawPrimitiveTopology.TriangleList, gridData.Vertices, 0, gridData.EdgeIndex);
        DrawBatched(handle, DrawPrimitiveTopology.LineList, gridData.Vertices, gridData.EdgeIndex, gridData.VertexCount - gridData.EdgeIndex);

        handle.SetTransform(previous);

        PruneGridData();
    }

    /// <summary>
    /// Rewrites a grid's cached vertex buffer. Only runs when the grid's tiles have changed.
    /// </summary>
    private void RebuildGridGeometry(Entity<MapGridComponent> grid, GridDrawData gridData)
    {
        var tileSize = grid.Comp.TileSize;

        _gridTileList.Clear();

        var rator = Maps.GetAllTiles(grid.Owner, grid.Comp);
        while (rator.MoveNext(out var tileRef))
        {
            var def = (ContentTileDefinition)_tileDef[tileRef.Value.Tile.TypeId];
            _gridTileList[tileRef.Value.GridIndices] = def.Vertices;
        }

        RadarGridGeometry.Build(_gridTileList, tileSize, _triangles, _edges);

        // Mono - grid edge markers are entities rather than tiles, so they join the outline afterwards.
        _edgeMarkers.Clear();
        _lookup.GetLocalEntitiesIntersecting(grid, grid.Comp.LocalAABB, _edgeMarkers);
        foreach (var edge in _edgeMarkers)
        {
            if (!_xformQuery.TryComp(edge, out var xform))
                continue;

            var coord = xform.Coordinates.Position;
            var rotation = xform.LocalRotation;
            var begin = rotation.RotateVec(edge.Comp.Begin);
            var end = rotation.RotateVec(edge.Comp.End);
            _edges.Add(new RadarGridGeometry.Segment(coord + begin * tileSize, coord + end * tileSize));
        }

        RadarGridGeometry.MergeCollinear(_edges);

        // Grow-only. A full VGRoid buffer is ~8 MB, which is well past the Large Object Heap threshold, and
        // a grid whose tiles are actively changing rebuilds on every tick that touches it: reallocating on
        // every size change turns tile edits into a stream of LOH garbage and the gen2 collections that
        // follow. VertexCount carries the live length instead of the array's own.
        var total = _triangles.Count + _edges.Count * 2;
        if (gridData.Vertices.Length < total)
            gridData.Vertices = new DrawVertexUV2DColor[total];

        gridData.VertexCount = total;
        var verts = gridData.Vertices;

        for (var i = 0; i < _triangles.Count; i++)
        {
            verts[i] = new DrawVertexUV2DColor(_triangles[i], Color.White);
        }

        gridData.EdgeIndex = _triangles.Count;

        var write = gridData.EdgeIndex;
        foreach (var edge in _edges)
        {
            verts[write++] = new DrawVertexUV2DColor(edge.Start, Color.White);
            verts[write++] = new DrawVertexUV2DColor(edge.End, Color.White);
        }

        // Force the next draw to write real colours over the placeholders.
        gridData.CachedFill = null;
        gridData.CachedLine = null;
    }

    /// <summary>
    /// Rewrites the colour on a cached buffer. Only runs when the grid's IFF colour actually changes.
    /// </summary>
    private static void Recolor(GridDrawData gridData, Color fill, Color line)
    {
        // DrawVertexUV2DColor holds a linear colour, which is what the flat-colour path converts to.
        var fillLinear = Color.FromSrgb(fill);
        var lineLinear = Color.FromSrgb(line);
        var verts = gridData.Vertices;

        for (var i = 0; i < gridData.EdgeIndex; i++)
        {
            verts[i].Color = fillLinear;
        }

        for (var i = gridData.EdgeIndex; i < gridData.VertexCount; i++)
        {
            verts[i].Color = lineLinear;
        }

        gridData.CachedFill = fill;
        gridData.CachedLine = line;
    }

    /// <summary>
    /// Draws a range of a cached buffer in slices of at most <see cref="BatchVertices"/>, aligned to whole
    /// primitives. Only list topologies split like this; strips, fans and loops share vertices across
    /// primitives and are rejected.
    /// </summary>
    private void DrawBatched(DrawingHandleScreen handle, DrawPrimitiveTopology topology, DrawVertexUV2DColor[] vertices, int offset, int count)
    {
        if (count <= 0)
            return;

        var stride = topology switch
        {
            DrawPrimitiveTopology.TriangleList => 3,
            DrawPrimitiveTopology.LineList => 2,
            _ => throw new ArgumentOutOfRangeException(nameof(topology), topology, "Only list topologies can be batched."),
        };

        var batchSize = BatchVertices - BatchVertices % stride;

        for (var start = 0; start < count; start += batchSize)
        {
            var batch = Math.Min(batchSize, count - start);
            handle.DrawPrimitives(topology, _white, vertices.AsSpan(offset + start, batch));
        }
    }

    /// <summary>
    /// Drops geometry for grids this control has not drawn recently. Upstream never released these, so a
    /// radar panned across a sector retained every grid it had ever seen for the life of the control.
    /// </summary>
    private void PruneGridData()
    {
        // DrawGrid runs once per visible grid, so this is gated on an interval rather than run per call.
        // Walking the dictionary on every grid every frame would reintroduce the quadratic cost this
        // whole pass exists to remove.
        if (Timing.RealTime < _nextPrune)
            return;

        _nextPrune = Timing.RealTime + GridDataPruneInterval;

        if (GridData.Count <= GridDataSoftCap)
            return;

        var cutoff = Timing.RealTime - GridDataRetention;

        // Removing during enumeration is supported on Dictionary<,> as of .NET Core 3.0.
        foreach (var (uid, data) in GridData)
        {
            if (data.LastDrawn < cutoff)
                GridData.Remove(uid);
        }
    }
    // End Triad

    // Triad: removed — replaced by RadarGridGeometry.Build, which stores tile edges as directed segments
    // rather than Box2. The original is preserved here because the fork chain still carries this method.
    /*
    protected void DrawGridOriginal(DrawingHandleScreen handle, Matrix3x2 gridToView, Entity<MapGridComponent> grid, Color color, float alpha = 0.01f)
    {
        var rator = Maps.GetAllTiles(grid.Owner, grid.Comp);
        var minimapScale = MinimapScale;
        var midpoint = new Vector2(MidPoint, MidPoint);
        var tileSize = grid.Comp.TileSize;

        // Check if we even have data
        // TODO: Need to prune old grid-data if we don't draw it.
        var gridData = GridData.GetOrNew(grid.Owner);

        if (gridData.LastBuild < grid.Comp.LastTileModifiedTick)
        {
            gridData.Vertices.Clear();
            _gridTileList.Clear();
            _gridDirEdges.Clear();

            // Okay so there's 2 steps to this
            // 1. Is that get we get a set of all tiles. This is used to decompose into triangle-strips
            // 2. Is that we get a list of all tiles. This is used for edge data to decompose into line-strips.
            while (rator.MoveNext(out var tileRef))
            {
                var index = tileRef.Value.GridIndices;

                // Mono - drawing logic rewritten
                var def = (ContentTileDefinition)_tileDef[tileRef.Value.Tile.TypeId];
                _gridTileList[index] = def;
                _gridDirEdges[index] = new Box2?[4];

                // since our shape has to be convex, just draw it by taking our first vertex as origin
                var bl = Maps.TileToVector(grid, index);
                var origin = bl + def.Vertices[0] * tileSize;
                var prev = bl + def.Vertices[1] * tileSize;
                for (var i = 2; i < def.Vertices.Count; i++)
                {
                    var vert = bl + def.Vertices[i] * tileSize;
                    gridData.Vertices.Add(origin);
                    gridData.Vertices.Add(prev);
                    gridData.Vertices.Add(vert);
                    prev = vert;
                }

                prev = def.Vertices[^1];
                for (var i = 0; i < def.Vertices.Count; i++)
                {
                    var vert = def.Vertices[i];
                    var wasPrev = prev;
                    prev = vert;

                    var dirFlag = DirectionFlag.None;
                    if (wasPrev.X == 0 && vert.X == 0)
                        dirFlag = DirectionFlag.West;
                    else if (wasPrev.X == 1 && vert.X == 1)
                        dirFlag = DirectionFlag.East;
                    else if (wasPrev.Y == 0 && vert.Y == 0)
                        dirFlag = DirectionFlag.South;
                    else if (wasPrev.Y == 1 && vert.Y == 1)
                        dirFlag = DirectionFlag.North;

                    if (dirFlag != DirectionFlag.None)
                    {
                        var idxVec = dirFlag.AsDir().ToIntVec();
                        var arrIdx = GetDirIndex(idxVec);
                        _gridDirEdges[index][arrIdx] = new Box2(wasPrev, vert);
                    }
                }
            }

            gridData.EdgeIndex = gridData.Vertices.Count;
            _edges.Clear();

            foreach (var (index, def) in _gridTileList)
            {
                // Mono - drawing logic rewritten
                var bl = Maps.TileToVector(grid, index);

                // start from drawing the end->start line
                var prev = def.Vertices[^1];
                for (var i = 0; i < def.Vertices.Count; i++)
                {
                    var vert = def.Vertices[i];
                    var wasPrev = prev;
                    prev = vert;

                    // check if this edge is on any direction - we do have _gridDirEdges to cache this, but it's more feasible to just do this again
                    var dirFlag = DirectionFlag.None;
                    if (wasPrev.X == 0 && vert.X == 0)
                        dirFlag = DirectionFlag.West;
                    else if (wasPrev.X == 1 && vert.X == 1)
                        dirFlag = DirectionFlag.East;
                    else if (wasPrev.Y == 0 && vert.Y == 0)
                        dirFlag = DirectionFlag.South;
                    else if (wasPrev.Y == 1 && vert.Y == 1)
                        dirFlag = DirectionFlag.North;

                    if (dirFlag != DirectionFlag.None)
                    {
                        var dirDir = dirFlag.AsDir();
                        var dirVec = dirDir.ToIntVec();
                        if (_gridDirEdges.TryGetValue(index + dirVec, out var otherEdges))
                        {
                            var oppositeDir = dirDir.GetOpposite().ToIntVec();
                            var arrIdx = GetDirIndex(oppositeDir);
                            var otherEdge = otherEdges[arrIdx];
                            if (otherEdge is { } neighbor)
                            {
                                var offset = (Vector2)dirVec;

                                // offset into our coordinate space: tile relative to us + point relative to tile
                                var otherPrev = neighbor.BottomLeft + offset;
                                var otherVert = neighbor.TopRight + offset;
                                var otherEdgeVec = otherVert - otherPrev;
                                // so we can map points onto the parametric form of our line
                                var otherEdgeAdj = otherEdgeVec / otherEdgeVec.LengthSquared();

                                var relPrev = wasPrev - otherPrev;
                                var relVert = vert - otherPrev;
                                var relPrevPos = Vector2.Dot(relPrev, otherEdgeAdj);
                                var relVertPos = Vector2.Dot(relVert, otherEdgeAdj);
                                // swap us around for ease of checks if needed
                                if (relPrevPos > relVertPos)
                                    (relVertPos, relPrevPos) = (relPrevPos, relVertPos);

                                // we're fully inside the other edge: do not draw us
                                if (relPrevPos >= 0 && relVertPos <= 1)
                                    continue;

                                // if we do not intersect, just draw us
                                if (!(relPrevPos >= 1 || relVertPos <= 0))
                                {
                                    // we end somewhere inside it
                                    if (relPrevPos >= 0 || relVertPos <= 1)
                                    {
                                        // draw the non-overlapping part
                                        if (relVertPos <= 1)
                                            relVertPos = 0;
                                        if (relPrevPos >= 0)
                                            relPrevPos = 1;

                                        var p1 = otherPrev + otherEdgeVec * relPrevPos;
                                        var p2 = otherPrev + otherEdgeVec * relVertPos;
                                        if (p2 - p1 != Vector2.Zero)
                                            _edges.Add((bl + p1 * tileSize, bl + p2 * tileSize));
                                    }
                                    // we fully encompass it, have to draw 2 parts
                                    else
                                    {
                                        var p1 = otherPrev + otherEdgeVec * relPrevPos;
                                        var p2 = otherPrev;
                                        var p3 = otherVert;
                                        var p4 = otherPrev + otherEdgeVec * relVertPos;
                                        _edges.Add((bl + p1 * tileSize, bl + p2 * tileSize));
                                        _edges.Add((bl + p3 * tileSize, bl + p4 * tileSize));
                                    }
                                    continue;
                                }
                            }
                        }
                    }

                    _edges.Add((bl + wasPrev * tileSize, bl + vert * tileSize));
                }
            }

            // Mono
            _edgeMarkers.Clear();
            _lookup.GetLocalEntitiesIntersecting(grid, grid.Comp.LocalAABB, _edgeMarkers);
            foreach (var edge in _edgeMarkers)
            {
                if (!_xformQuery.TryComp(edge, out var xform))
                    continue;

                var coord = xform.Coordinates.Position;
                var rotation = xform.LocalRotation;
                var begin = rotation.RotateVec(edge.Comp.Begin);
                var end = rotation.RotateVec(edge.Comp.End);
                _edges.Add((coord + begin * tileSize, coord + end * tileSize));
            }

            // Decompose the edges into longer lines to save data.
            // Now we decompose the lines into longer lines (less data to send to the GPU)
            var decomposed = true;

            while (decomposed)
            {
                decomposed = false;

                for (var i = 0; i < _edges.Count; i++)
                {
                    var (start, end) = _edges[i];
                    var neighborFound = false;
                    var neighborIndex = 0;
                    Vector2 neighborStart;
                    Vector2 neighborEnd = Vector2.Zero;

                    // Does our end correspond with another start?
                    for (var j = i + 1; j < _edges.Count; j++)
                    {
                        (neighborStart, neighborEnd) = _edges[j];

                        if (!end.Equals(neighborStart))
                            continue;

                        neighborFound = true;
                        neighborIndex = j;
                        break;
                    }

                    if (!neighborFound)
                        continue;

                    // Check if our start and the neighbor's end are collinear
                    if (!CollinearSimplifier.IsCollinear(start, end, neighborEnd, 10f * float.Epsilon))
                        continue;

                    decomposed = true;
                    _edges[i] = (start, neighborEnd);
                    _edges.RemoveAt(neighborIndex);
                }
            }

            gridData.Vertices.EnsureCapacity(_edges.Count * 2);

            foreach (var edge in _edges)
            {
                gridData.Vertices.Add(edge.Start);
                gridData.Vertices.Add(edge.End);
            }

            gridData.LastBuild = grid.Comp.LastTileModifiedTick;
        }

        var totalData = gridData.Vertices.Count;
        var triCount = gridData.EdgeIndex;
        var edgeCount = totalData - gridData.EdgeIndex;
        Extensions.EnsureLength(ref _allVertices, totalData);

        _drawJob.MidPoint = midpoint;
        _drawJob.Matrix = gridToView;
        _drawJob.MinimapScale = minimapScale;
        _drawJob.Vertices = gridData.Vertices;
        _drawJob.ScaledVertices = _allVertices;

        _parallel.ProcessNow(_drawJob, totalData);

        // Triad: batch the edge draw too. DrawPrimitives stackallocs 40 bytes per vertex with no
        // size cap (the engine's own TODO flags it), and upstream hands the whole edge span over
        // in one call. Survivable for a shuttle, fatal for a VGRoid: its fractal outline is ~209k
        // vertices, an 8 MiB stackalloc that blows the game thread's stack and CTDs with an empty
        // log, since the access violation surfaces in coreclr rather than as a managed exception.
        // const float BatchSize = 3f * 4096;
        //
        // for (var i = 0; i < Math.Ceiling(triCount / BatchSize); i++)
        // {
        //     var start = (int) (i * BatchSize);
        //     var end = (int) Math.Min(triCount, start + BatchSize);
        //     var count = end - start;
        //     handle.DrawPrimitives(DrawPrimitiveTopology.TriangleList, new Span<Vector2>(_allVertices, start, count), color.WithAlpha(alpha));
        // }
        //
        // handle.DrawPrimitives(DrawPrimitiveTopology.LineList, new Span<Vector2>(_allVertices, gridData.EdgeIndex, edgeCount), color);
        DrawBatched(handle, DrawPrimitiveTopology.TriangleList, 0, triCount, color.WithAlpha(alpha));
        DrawBatched(handle, DrawPrimitiveTopology.LineList, gridData.EdgeIndex, edgeCount, color);
    }

    private static int GetDirIndex(Vector2i dir)
    {
        // 1,  0 -> 1
        // 0,  1 -> 3
        // -1, 0 -> 0
        // 0, -1 -> 2
        return Math.Abs(dir.Y) * 2 + (dir.X + dir.Y + 1) / 2;
    }

    private record struct GridDrawJob : IParallelRobustJob
    {
        public int BatchSize => 64;

        public float MinimapScale;
        public Vector2 MidPoint;
        public Matrix3x2 Matrix;

        public List<Vector2> Vertices;
        public Vector2[] ScaledVertices;

        public void Execute(int index)
        {
            ScaledVertices[index] = Vector2.Transform(Vertices[index], Matrix);
        }
    }
    */
    // End Triad
}

public sealed class GridDrawData
{
    // Triad: grid-LOCAL vertices, coloured and ready to hand to DrawPrimitives. Previously a
    // List<Vector2> of untransformed positions that was copied and transformed every frame.
    public DrawVertexUV2DColor[] Vertices = Array.Empty<DrawVertexUV2DColor>();

    /// <summary>
    /// How much of <see cref="Vertices"/> is live. The array only ever grows, so its own length is not the
    /// answer: reallocating it on every size change would put an ~8 MB buffer on the Large Object Heap
    /// each time a grid's tiles are edited.
    /// </summary>
    public int VertexCount;

    /// <summary>
    /// Vertices index from when edges start.
    /// </summary>
    public int EdgeIndex;

    public GameTick LastBuild;

    /// <summary>
    /// Whether <see cref="Vertices"/> has ever been filled. Tracked separately from
    /// <see cref="LastBuild"/> because a grid untouched since creation reports tick zero, which never
    /// compares as newer than the last build.
    /// </summary>
    public bool Built;

    /// <summary>
    /// Colours currently baked into <see cref="Vertices"/>, so a redraw only rewrites them on a change.
    /// </summary>
    public Color? CachedFill;
    public Color? CachedLine;

    /// <summary>
    /// When this grid was last drawn, used to release geometry for grids that have left the view.
    /// </summary>
    public TimeSpan LastDrawn;

    /// <summary>
    /// Earliest time this grid may be rebuilt again. INTERIM, part of the rebuild coalescing in DrawGrid;
    /// remove alongside it once geometry is per-chunk.
    /// </summary>
    public TimeSpan NextRebuild;
    // End Triad
}
