"Mapping":
 - changed-files:
   - any-glob-to-any-file: "Resources/Maps/**/*.yml" # All .yml files in the Resources/Maps directory, recursive.

"Shipyard":
- changed-files:
  - any-glob-to-any-file:
    - "Resources/Maps/_Triad/Shuttles/**/*.yml" # Grid Files
    - "Resources/Prototypes/_Triad/Shipyard/**/*.yml" # Prototypes Files
    - "Resources/Maps/_NF/Shuttles/**/*.yml" # Frontier Grid Files
    - "Resources/Prototypes/_NF/Shipyard/**/*.yml" # Frontier Prototypes Files
    - "Resources/Maps/_Mono/Shuttles/**/*.yml" # Monolith Grid Files
    - "Resources/Prototypes/_Mono/Shipyard/**/*.yml" # Monolith Prototypes Files

"Sprites":
- changed-files:
  - any-glob-to-any-file:
    - "**/*.rsi/*.png"
    - "**/*.rsi/*.json"

"UI":
- changed-files:
  - any-glob-to-any-file: "**/*.xaml*"

"C#":
- changed-files:
  - any-glob-to-any-file: "**/*.cs"

"Shaders":
- changed-files:
  - any-glob-to-any-file: '**/*.swsl'

"Audio":
- changed-files:
  - any-glob-to-any-file: '**/*.ogg'

"No C#":
- changed-files:
  - all-globs-to-all-files: "!**/*.cs"

"Docs":
- changed-files:
  - any-glob-to-any-file:
    - "**/*.xml"
    - "**/*.md"

"FTL":
- changed-files:
  - any-glob-to-any-file: "Resources/Locale/**/*.ftl"

"YML":
- all:
  - changed-files:
    - any-glob-to-any-file: "**/*.yml"
    - all-globs-to-any-file:
      - "!Resources/Maps/_NF/**/*.yml"
      - "!Resources/Prototypes/Maps/_NF/**/*.yml"

"DB Migration":
- changed-files:
  - any-glob-to-any-file: "Content.Server.Database/Migrations/**/*.cs"
