// Triad: legacy import.
using Content.Shared._NF.Shipyard.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._NF.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class DrydockImportRow : PanelContainer
{
    /// <summary>The client's handle for the file, sent back with the payload on Import.</summary>
    public readonly string FileId;

    public DrydockImportRow(DrydockImportShipInfo ship)
    {
        RobustXamlLoader.Load(this);

        FileId = ship.FileId;

        // "new" in the amber the row is edged with, where a berth row puts its number: this is a hull
        // arriving rather than one already in a slot.
        var marker = new FormattedMessage();
        marker.AddColored(Loc.GetString("shipyard-console-import-row-marker"), DrydockText.Warning);
        MarkerLabel.SetMessage(marker);

        var line = new FormattedMessage();
        line.AddBold(ship.Name);
        line.AddColored(" " + Loc.GetString("shipyard-console-import-row-note"), DrydockText.Dim);
        ShipLabel.SetMessage(line);
    }
}
