// Triad: drydock tab.
using Content.Shared._NF.Shipyard.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class DrydockShipRow : PanelContainer
{
    public Guid ShipId;

    public DrydockShipRow(StoredShipInfo ship)
    {
        RobustXamlLoader.Load(this);

        ShipId = ship.ShipId;
        ShipName.Text = ship.Name;

        // The size class is whatever string the row was filed with, shown as-is. A ship stored by
        // an older build can name a class this one no longer has, and a blank label is a better
        // outcome there than refusing to draw the row at all.
        SizeClassLabel.Text = ship.SizeClass ?? string.Empty;
    }
}
