// Triad: drydock tab.
using Content.Shared._NF.Shipyard.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._NF.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class DrydockShipRow : PanelContainer
{
    public Guid ShipId;

    public DrydockShipRow(StoredShipInfo ship)
    {
        RobustXamlLoader.Load(this);

        ShipId = ship.ShipId;
        ShipName.Text = ship.Name;

        // The size class is whatever string the row was filed with, shown as-is. A ship stored by
        // an older build can name a class this one no longer has, and a blank label is a better
        // outcome there than refusing to draw the row at all.
        SizeClassLabel.Text = ship.SizeClass ?? string.Empty;

        // Only a stored ship can be brought out or given away. A ship that is out is on the list
        // so its owner can see the berth it left is empty, and a held one so they know to ask.
        var stored = ship.State == "Stored";
        StateLabel.Text = ship.State switch
        {
            "Stored" => Loc.GetString("shipyard-console-ship-state-stored"),
            "CheckedOut" => Loc.GetString("shipyard-console-ship-state-out"),
            "Held" => Loc.GetString("shipyard-console-ship-state-held"),
            _ => ship.State,
        };
        StateLabel.Modulate = ship.State switch
        {
            "Stored" => Color.FromHex("#6ec06e"),
            "CheckedOut" => Color.FromHex("#d9a441"),
            _ => Color.FromHex("#cf4f4f"),
        };

        RetrieveButton.Disabled = !stored;
        TransferButton.Visible = stored;
    }
}
