// Triad: drydock tab.
using Content.Shared._NF.Shipyard.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._NF.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class DrydockBerthRow : PanelContainer
{
    private static readonly Color DimText = Color.FromHex("#999999");
    private static readonly Color EmptyText = Color.FromHex("#777777");
    private static readonly Color EscrowText = Color.FromHex("#d9a441");

    public int BerthId;

    public Guid? OccupantShipId;

    /// <summary>The standing offer on the occupant, when it is in escrow. Cancel sends this.</summary>
    public long? OccupantTransferId;

    private readonly string? _occupantName;
    private readonly string? _occupantClass;
    private readonly string? _escrowText;

    /// <param name="canRetrieve">
    /// Whether anything may come out right now: false while the card already carries a deed, since
    /// one card holds one ship, or while no card is in. The row hides Retrieve rather than greying
    /// it, so the one button a row shows is always one that works. The slot it sits in stays
    /// reserved while the flag is set, so the menus on the empty rows still line up with it.
    /// </param>
    public DrydockBerthRow(DrydockBerthInfo berth, bool canRetrieve)
    {
        RobustXamlLoader.Load(this);

        BerthId = berth.BerthId;
        OccupantShipId = berth.OccupantShipId;
        OccupantTransferId = berth.OccupantTransferId;

        // Class text is whatever the row was filed with, shown as-is: a berth or ship stored by an
        // older build can name a class this one no longer has, and a label beats a refused row.
        var slot = new FormattedMessage();
        slot.AddText(Loc.GetString("shipyard-console-berth-row", ("berth", berth.BerthId)));
        slot.PushColor(DimText);
        slot.AddText(" " + Loc.GetString("shipyard-console-berth-row-class", ("class", berth.MaxSizeClass)));
        slot.Pop();
        BerthLabel.SetMessage(slot);

        _occupantName = berth.OccupantName;
        _occupantClass = berth.OccupantSizeClass;

        RetrieveSlot.Visible = canRetrieve;

        // In escrow the row says so in place of Retrieve: the ship keeps its berth and cannot
        // come out until the offer is answered, withdrawn, or expires.
        if (berth.OccupantTransferId != null)
        {
            _escrowText = Loc.GetString("shipyard-console-transfer-escrow",
                ("name", berth.OccupantOfferedTo ?? Loc.GetString("shipyard-console-transfer-someone")));
            CancelButton.Visible = true;
            SetTimeLeft(berth.OccupantOfferSecondsLeft ?? 0);
        }
        else
        {
            DrawOccupant(null);
            RetrieveButton.Visible = canRetrieve && berth.OccupantShipId != null && berth.OccupantState == "Stored";
        }
    }

    /// <summary>Redraws the escrow clock. The menu ticks this once a second from the last state it received.</summary>
    public void SetTimeLeft(int seconds)
    {
        if (_escrowText == null)
            return;

        DrawOccupant($"{_escrowText} · {DrydockClock.Left(seconds)}");
    }

    /// <summary>
    /// The ship in the berth: its name, then its class in the dim colour, then whatever the row
    /// has to add about it. An empty berth says so in the empty colour and nothing else.
    /// </summary>
    private void DrawOccupant(string? trailing)
    {
        var msg = new FormattedMessage();

        if (_occupantName == null)
        {
            msg.PushColor(EmptyText);
            msg.AddText(Loc.GetString("shipyard-console-berth-empty"));
            msg.Pop();
            OccupantLabel.SetMessage(msg);
            return;
        }

        msg.AddText(Loc.GetString("shipyard-console-berth-occupant", ("ship", _occupantName)));
        msg.PushColor(DimText);
        msg.AddText(" " + Loc.GetString("shipyard-console-berth-occupant-class", ("class", _occupantClass ?? "?")));
        msg.Pop();

        if (trailing != null)
        {
            msg.PushColor(EscrowText);
            msg.AddText($" · {trailing}");
            msg.Pop();
        }

        OccupantLabel.SetMessage(msg);
    }
}

/// <summary>The one way an offer's remaining time is written, so the alert and the escrow row agree.</summary>
internal static class DrydockClock
{
    public static string Left(int seconds)
    {
        return seconds >= 60
            ? Loc.GetString("shipyard-console-transfer-minutes-left", ("minutes", (int)Math.Ceiling(seconds / 60.0)))
            : Loc.GetString("shipyard-console-transfer-seconds-left", ("seconds", Math.Max(0, seconds)));
    }
}
