// Triad: drydock tab.
using Content.Shared._NF.Shipyard.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._NF.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class DrydockBerthRow : PanelContainer
{
    // The row at rest, in escrow (amber), and as the berth an offer on the tab would land in (blue).
    private static readonly StyleBoxFlat EscrowFrame = new() { BorderThickness = new Thickness(3), BorderColor = DrydockText.AmberBorder, BackgroundColor = DrydockText.AmberFill };
    private static readonly StyleBoxFlat IncomingFrame = new() { BorderThickness = new Thickness(3), BorderColor = DrydockText.BlueBorder, BackgroundColor = DrydockText.BlueFill };

    public int BerthId;

    public Guid? OccupantShipId;

    /// <summary>The standing offer on the occupant, when it is in escrow. Cancel sends this.</summary>
    public long? OccupantTransferId;

    private readonly string? _occupantName;
    private readonly string? _occupantClass;
    private readonly string? _escrowText;

    /// <param name="canRetrieve">
    /// Whether anything may come out right now: false while the card already carries a deed, since
    /// one card holds one ship, or while no card is in. The row hides Retrieve rather than greying
    /// it, so the one button a row shows is always one that works. The slot it sits in stays
    /// reserved while the flag is set, so the menus on the empty rows still line up with it.
    /// </param>
    /// <param name="incomingShipName">
    /// The ship an offer on the tab would put in this berth if accepted, when the berth is empty
    /// and is where the offer lands. The row says so in place of "empty".
    /// </param>
    public DrydockBerthRow(DrydockBerthInfo berth, bool canRetrieve, string? incomingShipName = null)
    {
        RobustXamlLoader.Load(this);

        BerthId = berth.BerthId;
        OccupantShipId = berth.OccupantShipId;
        OccupantTransferId = berth.OccupantTransferId;

        // Class text is whatever the row was filed with, spaced for reading and otherwise shown
        // as-is: a berth or ship stored by an older build can name a class this one no longer has,
        // and a label beats a refused row.
        var slot = new FormattedMessage();
        slot.AddBold(Loc.GetString("shipyard-console-berth-row", ("berth", berth.BerthId)));
        slot.AddColored(" " + Loc.GetString("shipyard-console-berth-row-class", ("class", DrydockText.Class(berth.MaxSizeClass))), DrydockText.Dim);
        BerthLabel.SetMessage(slot);

        _occupantName = berth.OccupantName;
        _occupantClass = berth.OccupantSizeClass;

        RetrieveSlot.Visible = canRetrieve;

        if (berth.OccupantTransferId != null)
        {
            // In escrow: the row is marked, names who the ship was offered to and how long the
            // offer has left, and Cancel stands where the menu was. Nothing else can be done to
            // the ship until the offer is answered, withdrawn, or expires, so the menu is gone
            // rather than full of greyed entries.
            PanelOverride = EscrowFrame;
            _escrowText = Loc.GetString("shipyard-console-transfer-escrow",
                ("name", berth.OccupantOfferedTo ?? Loc.GetString("shipyard-console-transfer-someone")));
            CancelButton.Visible = true;
            MenuButton.Visible = false;
            SetTimeLeft(berth.OccupantOfferSecondsLeft ?? 0);
        }
        else if (berth.OccupantShipId == null && incomingShipName != null)
        {
            PanelOverride = IncomingFrame;
            var msg = new FormattedMessage();
            msg.AddColored(Loc.GetString("shipyard-console-berth-incoming", ("ship", incomingShipName)), DrydockText.Incoming);
            OccupantLabel.SetMessage(msg);
        }
        else
        {
            DrawOccupant(null);
            RetrieveButton.Visible = canRetrieve && berth.OccupantShipId != null && berth.OccupantState == "Stored";
        }
    }

    /// <summary>Redraws the escrow clock. The menu ticks this once a second from the last state it received.</summary>
    public void SetTimeLeft(int seconds)
    {
        if (_escrowText == null)
            return;

        DrawOccupant($"{_escrowText} · {DrydockText.Left(seconds)}");
    }

    /// <summary>
    /// The ship in the berth: its name in bold, then its class and whatever the row has to add
    /// about it in the dim colour. An empty berth says so in the empty colour and nothing else.
    /// </summary>
    private void DrawOccupant(string? trailing)
    {
        var msg = new FormattedMessage();

        if (_occupantName == null)
        {
            msg.AddColored(Loc.GetString("shipyard-console-berth-empty"), DrydockText.Empty);
            OccupantLabel.SetMessage(msg);
            return;
        }

        msg.AddBold(Loc.GetString("shipyard-console-berth-occupant", ("ship", _occupantName)));
        var detail = " " + Loc.GetString("shipyard-console-berth-occupant-class", ("class", DrydockText.Class(_occupantClass)));
        if (trailing != null)
            detail += $" · {trailing}";
        msg.AddColored(detail, DrydockText.Dim);

        OccupantLabel.SetMessage(msg);
    }
}
