using System.Linq;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Client._NF.Shipyard.BUI;
using Content.Shared._NF.Bank;
using Content.Shared._NF.Shipyard.BUI;
using Content.Shared._NF.Shipyard.Prototypes;
using Content.Shared._Triad.ShipSize;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._NF.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipyardConsoleMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _protoManager = default!;
    [Dependency] private IResourceCache _resourceCache = default!; // Triad: drydock tab, the lockout's fonts

    public event Action<ButtonEventArgs>? OnSellShip;
    public event Action<ButtonEventArgs>? OnSaveShip;
    public event Action<ButtonEventArgs>? OnOrderApproved;
    public event Action<ButtonEventArgs>? OnUnassignDeed;
    public event Action<string>? OnRenameShip;
    // Triad: drydock tab. Store carries only the berth to land in, because the server resolves the
    // ship from the card in the slot; retrieve carries the id of the row that was clicked.
    public event Action<int?>? OnStore;
    public event Action<Guid>? OnRetrieve;
    public event Action<string>? OnBuyBerth;
    public event Action<int>? OnSellBerth;
    public event Action<int>? OnUpgradeBerth;
    // A transfer names the ship and the account it goes to; the answers name the offer row.
    public event Action<Guid, Guid>? OnOfferTransfer;
    public event Action<long>? OnCancelTransfer;
    public event Action<long>? OnAcceptTransfer;
    public event Action<long>? OnDeclineTransfer;
    // Sell carries the name the player typed; the server compares it with the ship's own.
    public event Action<Guid, string>? OnSellStoredShip;
    public event Action<Guid, string>? OnRenameStoredShip;
    public event Action<Guid, int>? OnMoveStoredShip;

    /// <summary>
    /// Triad: the viewing account, so the tab can tell the operator from everyone else looking.
    /// One console state is shared by every viewer, so this is decided here.
    /// </summary>
    public Guid? LocalUserId;

    // The offer clocks. The state carries seconds left as of when the server built it; the tab
    // counts down from there between states rather than asking the server every second.
    private float _sinceState;
    private int _lastElapsed = -1;

    // Storing a hull serializes the whole grid and compresses it on the server's game thread, so
    // the server sends nothing at all while it works and cannot report how far along it is. The
    // client is a separate process and keeps drawing, so what it can honestly show is that the
    // press landed and the work is still going: a moving indicator, never a percentage.
    // Cleared by the next state, which the server pushes on success and on refusal alike.
    private float _storingFor = -1f;

    /// <summary>How long the indicator runs before giving the button back, if no state ever arrives.</summary>
    private const float StoreFeedbackTimeout = 30f;

    /// <summary>The last deed ship drawn, so the timeout can put the card back as it was.</summary>
    private DrydockDeedShipInfo? _lastDeedShip;

    // Retrieve has the same silence: the server loads the grid and docks it before it says a
    // word. Same indicator, on the row that was pressed, with every other Retrieve greyed.
    private float _retrievingFor = -1f;
    private DrydockBerthRow? _retrievingRow;
    private bool _lastCanRetrieve;
    private readonly List<(Label Label, int Seconds)> _offerClocks = new();
    private readonly List<(DrydockBerthRow Row, int Seconds)> _escrowRows = new();
    private List<DrydockCaptainInfo> _lastCaptains = new();

    /// <summary>The offers addressed to the viewer, as the last state listed them.</summary>
    private List<DrydockTransferOfferInfo> _lastOffers = new();

    /// <summary>How long an offer stands, for the sentence in the transfer prompt.</summary>
    private int _offerMinutes;
    private readonly List<VesselSize> _categoryStrings = new();
    private readonly List<VesselClass> _classStrings = new();
    private readonly List<VesselEngine> _engineStrings = new();
    private VesselSize? _category;
    private VesselClass? _class;
    private VesselEngine? _engine;

    private List<string> _lastAvailableProtos = new();
    private List<string> _lastUnavailableProtos = new();
    private bool _freeListings = false;
    private bool _validId = false;

    public ShipyardConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Title = Loc.GetString("shipyard-console-menu-title");
        SearchBar.OnTextChanged += OnSearchBarTextChanged;
        Categories.OnItemSelected += OnCategoryItemSelected;
        Classes.OnItemSelected += OnClassItemSelected;
        Engines.OnItemSelected += OnEngineItemSelected;
        SellShipButton.OnPressed += (args) => { OnSellShip?.Invoke(args); };
        UnassignDeedButton.OnPressed += (args) => { OnUnassignDeed?.Invoke(args); };
        RenameButton.OnPressed += OnRenameButtonPressed;

        // Triad: drydock tab
        Tabs.SetTabTitle(0, Loc.GetString("shipyard-console-tab-purchase"));
        Tabs.SetTabTitle(1, Loc.GetString("shipyard-console-tab-drydock"));
        BuyBerthButton.Text = Loc.GetString("shipyard-console-berth-buy-button") + DrydockText.Caret;
        // The lockout's two big lines at the sizes they were designed at; Nano names no face that large.
        var bold = _resourceCache.GetResource<FontResource>("/Fonts/NotoSans/NotoSans-Bold.ttf");
        var regular = _resourceCache.GetResource<FontResource>("/Fonts/NotoSans/NotoSans-Regular.ttf");
        LockoutTitle.FontOverride = new VectorFont(bold, 44);
        LockoutSubtitle.FontOverride = new VectorFont(regular, 14);
        SaveShipButton.OnPressed += (args) => { OnSaveShip?.Invoke(args); };
    }

    /// <summary>
    /// Triad: the offer clocks tick here, once a second, from the last state the server sent. A
    /// clock that reaches zero stays at zero until the next state says the offer is gone.
    /// </summary>
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _sinceState += args.DeltaSeconds;

        // Every frame, not once a second: this is the only thing moving while the server is busy,
        // so it has to look alive.
        if (_storingFor >= 0f)
        {
            _storingFor += args.DeltaSeconds;
            if (_storingFor >= StoreFeedbackTimeout)
            {
                // The server never answered. Give the button back rather than stranding the
                // operator at a console that looks permanently busy.
                _storingFor = -1f;
                PopulateDeedShip(_lastDeedShip);
            }
            else
            {
                var dots = new string('.', (int)(_storingFor * 2) % 4);
                StoreButton.Text = Loc.GetString("shipyard-console-storing-button") + dots;
            }
        }

        if (_retrievingFor >= 0f)
        {
            _retrievingFor += args.DeltaSeconds;
            if (_retrievingFor >= StoreFeedbackTimeout)
            {
                // The server never answered; redraw the rows as the last state had them.
                _retrievingFor = -1f;
                _retrievingRow = null;
                _escrowRows.Clear();
                PopulateBerths(_lastBerths, _lastCanRetrieve);
            }
            else if (_retrievingRow != null)
            {
                var dots = new string('.', (int)(_retrievingFor * 2) % 4);
                _retrievingRow.RetrieveButton.Text = Loc.GetString("shipyard-console-retrieving-button") + dots;
            }
        }

        var elapsed = (int)_sinceState;
        if (elapsed == _lastElapsed)
            return;

        _lastElapsed = elapsed;
        foreach (var (label, seconds) in _offerClocks)
            label.Text = DrydockText.Left(seconds - elapsed);
        foreach (var (row, seconds) in _escrowRows)
            row.SetTimeLeft(seconds - elapsed);
    }

    private List<StoredShipInfo> _lastShips = new();
    private List<DrydockBerthInfo> _lastBerths = new();

    private bool WouldLeaveAShipWithoutABerth(int consumes)
    {
        var free = _lastBerths.Count(b => b.OccupantShipId == null);
        var shipsOut = _lastShips.Count(s => s.State == "CheckedOut");
        return shipsOut > 0 && free - consumes < shipsOut;
    }


    private void OnCategoryItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetCategoryText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnClassItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetClassText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnEngineItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetEngineText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnRenameButtonPressed(ButtonEventArgs args)
    {
        var newName = RenameLineEdit.Text.Trim();
        if (string.IsNullOrEmpty(newName))
            return;

        // Validate length (30 characters max, matching ShuttleDeedComponent.MaxNameLength)
        if (newName.Length > 30)
        {
            newName = newName[..30];
        }

        OnRenameShip?.Invoke(newName);
        RenameLineEdit.Text = "";
    }

    private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
    {
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void SetCategoryText(int id)
    {
        _category = id == 0 ? null : _categoryStrings[id];
        Categories.SelectId(id);
    }
    private void SetClassText(int id)
    {
        _class = id == 0 ? null : _classStrings[id];
        Classes.SelectId(id);
    }
    private void SetEngineText(int id)
    {
        _engine = id == 0 ? null : _engineStrings[id];
        Engines.SelectId(id);
    }
    /// <summary>
    ///     Populates the list of products that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateProducts(List<string> availablePrototypes, List<string> unavailablePrototypes, bool free, bool canPurchase)
    {
        Vessels.RemoveAllChildren();

        var search = SearchBar.Text.Trim().ToLowerInvariant();

        var newVessels = GetVesselPrototypesFromIds(availablePrototypes);
        AddVesselsToControls(newVessels, search, free, canPurchase);

        var newUnavailableVessels = GetVesselPrototypesFromIds(unavailablePrototypes);
        AddVesselsToControls(newUnavailableVessels, search, free, false);

        _lastAvailableProtos = availablePrototypes;
        _lastUnavailableProtos = unavailablePrototypes;
    }

    /// <summary>
    /// Given a set of prototype IDs, returns a corresponding set of prototypes, ordered by name.
    /// </summary>
    private List<VesselPrototype?> GetVesselPrototypesFromIds(IEnumerable<string> protoIds)
    {
        var vesselList = protoIds.Select(it => _protoManager.TryIndex<VesselPrototype>(it, out var proto) ? proto : null)
            .Where(it => it != null)
            .ToList();

        vesselList.Sort((x, y) =>
            string.Compare(x!.Name, y!.Name, StringComparison.CurrentCultureIgnoreCase));
        return vesselList;
    }

    /// <summary>
    /// Adds all vessels in a given list of prototypes as VesselRows in the UI.
    /// </summary>
    private void AddVesselsToControls(IEnumerable<VesselPrototype?> vessels, string search, bool free, bool canPurchase)
    {
        foreach (var prototype in vessels)
        {
            // Filter any ships
            if (_category != null && !prototype!.Category.Equals(_category))
                continue;
            if (_class != null && !prototype!.Classes.Contains(_class.Value))
                continue;
            if (_engine != null && !prototype!.Engines.Contains(_engine.Value))
                continue;
            if (search.Length > 0 && !prototype!.Name.ToLowerInvariant().Contains(search))
                continue;

            string priceText;
            if (free)
                priceText = Loc.GetString("shipyard-console-menu-listing-free");
            else if (prototype != null && !prototype.Purchasable) // Mono
                priceText = Loc.GetString("shipyard-console-menu-listing-voucher");
            else
                priceText = BankSystemExtensions.ToSpesoString(prototype!.Price);

            var vesselEntry = new VesselRow
            {
                Vessel = prototype,
                VesselName = { Text = prototype!.Name },
                Purchase = { Text = Loc.GetString("shipyard-console-purchase-available"), Disabled = !canPurchase },
                Guidebook = { Disabled = prototype.GuidebookPage is null, TooltipDelay = 0.2f, ToolTip = prototype.Description },
                Price = { Text = priceText },
            };
            vesselEntry.Purchase.OnPressed += (args) => { OnOrderApproved?.Invoke(args); };
            Vessels.AddChild(vesselEntry);
        }
    }

    /// <summary>
    ///     Populates the list categories that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateCategories(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _categoryStrings.Clear();
        Categories.Clear();

        AddCategoriesFromPrototypes(availablePrototypes);
        AddCategoriesFromPrototypes(unavailablePrototypes);

        _categoryStrings.Sort();

        // Add "All" category at the top of the list
        _categoryStrings.Insert(0, VesselSize.All);

        foreach (var str in _categoryStrings)
        {
            Categories.AddItem(Loc.GetString($"shipyard-console-category-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship categories from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddCategoriesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            if (!_categoryStrings.Contains(prototype.Category) && prototype.Category != VesselSize.All)
            {
                _categoryStrings.Add(prototype.Category);
            }
        }
    }

    /// <summary>
    ///     Populates the list classes that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateClasses(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _classStrings.Clear();
        Classes.Clear();

        AddClassesFromPrototypes(availablePrototypes);
        AddClassesFromPrototypes(unavailablePrototypes);

        _classStrings.Sort();

        // Add "All" category at the top of the list
        _classStrings.Insert(0, VesselClass.All);

        foreach (var str in _classStrings)
        {
            Classes.AddItem(Loc.GetString($"shipyard-console-class-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship classes from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddClassesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            foreach (var cl in prototype.Classes)
            {
                if (!_classStrings.Contains(cl) && cl != VesselClass.All)
                {
                    _classStrings.Add(cl);
                }
            }
        }
    }

    /// <summary>
    ///     Populates the list engines that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateEngines(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _engineStrings.Clear();
        Engines.Clear();

        AddEnginesFromPrototypes(availablePrototypes);
        AddEnginesFromPrototypes(unavailablePrototypes);

        _engineStrings.Sort();

        // Add "All" category at the top of the list
        _engineStrings.Insert(0, VesselEngine.All);

        foreach (var str in _engineStrings)
        {
            Engines.AddItem(Loc.GetString($"shipyard-console-engine-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship engine power type from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddEnginesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            foreach (var cl in prototype.Engines)
            {
                if (!_engineStrings.Contains(cl) && cl != VesselEngine.All)
                {
                    _engineStrings.Add(cl);
                }
            }
        }
    }

    public void UpdateState(ShipyardConsoleInterfaceState state)
    {
        BalanceLabel.Text = BankSystemExtensions.ToSpesoString(state.Balance);
        var shipPrice = 0;
        if (!state.FreeListings)
            shipPrice = state.ShipSellValue;

        ShipAppraisalLabel.Text = $"{BankSystemExtensions.ToSpesoString(shipPrice)} ({state.SellRate * 100.0f:F1}%)";
        SellShipButton.Disabled = state.ShipDeedTitle == null;
        UnassignDeedButton.Disabled = state.ShipDeedTitle == null;

        // Show/hide and enable/disable rename controls based on whether there's a ship deed
        var hasShipDeed = state.ShipDeedTitle != null;
        RenameContainer.Visible = hasShipDeed;
        RenameLineEdit.Editable = hasShipDeed;
        RenameButton.Disabled = !hasShipDeed;

        SaveShipButton.Disabled = !state.IsTargetIdPresent;
        LoadShipButton.Disabled = !state.IsTargetIdPresent;
        LoadShipButton.ToolTip = state.IsTargetIdPresent
            ? null
            : Loc.GetString("shipyard-console-load-ship-no-id");
        TargetIdButton.Text = state.IsTargetIdPresent
            ? Loc.GetString("id-card-console-window-eject-button")
            : Loc.GetString("id-card-console-window-insert-button");
        if (state.ShipDeedTitle != null)
        {
            DeedTitle.Text = state.ShipDeedTitle;
        }
        else
        {
            DeedTitle.Text = $"None";
        }
        _freeListings = state.FreeListings;
        _validId = state.IsTargetIdPresent;
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);

        // Triad: drydock tab. Hidden outright when the master switch is off, rather than shown with
        // buttons that would every one of them come back refused.
        Tabs.SetTabVisible(1, state.DrydockEnabled);

        // The lockout: someone else's registered card in the slot. Decided here because one console
        // state is shared by every viewer and only the client knows which viewer it is.
        LockoutPanel.Visible = LocalUserId != null && state.DeedOwnerUserId is { } deedOwner && deedOwner != LocalUserId;

        _lastShips = state.StoredShips;
        _lastBerths = state.Berths;
        _lastCaptains = state.Captains;
        // Never an alert for one's own offer; the escrow row already says it.
        _lastOffers = state.TransferOffers.Where(o => LocalUserId == null || o.OfferedByUserId != LocalUserId).ToList();
        _offerMinutes = state.TransferOfferMinutes;
        _sinceState = 0f;
        _lastElapsed = -1;
        _offerClocks.Clear();
        _escrowRows.Clear();
        PopulateDeedShip(state.DeedShip);
        PopulateOffers();
        PopulateBerths(state.Berths, canRetrieve: state.IsTargetIdPresent && state.ShipDeedTitle == null);
        PopulateBuyMenu(state.BerthPrices);

        var free = state.Berths.Count(b => b.OccupantShipId == null);
        BerthSummaryLabel.Text = Loc.GetString("shipyard-console-berths-free", ("free", free), ("total", state.Berths.Count));
    }

    /// <summary>
    /// Triad: the card at the top. Store is a dropdown naming the berth the server would choose,
    /// and listing every free berth: the ones the hull fits can be picked, the ones too small stay
    /// listed and say so. Picking is what sends the store. With no free berth at all the button is
    /// out, and with none that fits it says so and every entry is greyed.
    /// </summary>
    private void PopulateDeedShip(DrydockDeedShipInfo? ship)
    {
        // A state arriving is the server answering, whether it stored the hull or refused it, so
        // the indicator stops here and the button is drawn fresh below.
        _storingFor = -1f;
        _lastDeedShip = ship;

        DeedShipPanel.Visible = ship != null;
        if (ship == null)
            return;

        // The hull's name carries the weight, a size up from everything else on the tab; its
        // class and how long it has been out sit behind it in the dim colour.
        var deed = new FormattedMessage();
        deed.AddBoldSized(ship.Name, 14);
        deed.AddColored(" " + (ship.MinutesOut is { } minutes
            ? Loc.GetString("shipyard-console-deed-ship-out", ("class", DrydockText.Class(ship.SizeClass)), ("time", DrydockText.Out(minutes)))
            : Loc.GetString("shipyard-console-deed-ship-new", ("class", DrydockText.Class(ship.SizeClass)))), DrydockText.Dim);
        DeedShipLabel.SetMessage(deed);

        StoreButton.Text = (ship.DefaultBerthId is { } berth
            ? Loc.GetString("shipyard-console-store-in-button", ("berth", berth))
            : Loc.GetString("shipyard-console-store-no-fit-button")) + DrydockText.Caret;

        var free = _lastBerths.Where(b => b.OccupantShipId == null).OrderBy(b => b.BerthId).ToList();
        StoreButton.SetItems(free.Select(b =>
        {
            var id = b.BerthId;
            var fits = ship.FittingBerthIds.Contains(id);
            return new DrydockMenuButton.Item(
                Loc.GetString("shipyard-console-store-item", ("berth", id), ("class", DrydockText.Class(b.MaxSizeClass))),
                fits ? null : Loc.GetString("shipyard-console-store-too-small"),
                fits && _validId,
                () =>
                {
                    BeginStoreFeedback();
                    OnStore?.Invoke(id);
                });
        }));

        // Storing into the berth an offer on the tab would land in takes that berth from the offer.
        var landing = _lastOffers.Where(o => o.LandsInBerthId != null).Select(o => o.LandsInBerthId!.Value).ToHashSet();
        StoreButton.Note = free.Any(b => landing.Contains(b.BerthId)) ? Loc.GetString("shipyard-console-store-takes-landing") : null;
        StoreButton.Disabled = free.Count == 0 || !_validId;
    }

    /// <summary>
    /// The press landed and the server has gone quiet to do the work. The button is taken away
    /// while it runs so a second press cannot be mistaken for the first not having registered. A
    /// second store is refused server-side by the in-progress sentinel regardless; this is about
    /// the operator knowing what is happening.
    /// </summary>
    private void BeginStoreFeedback()
    {
        _storingFor = 0f;
        StoreButton.Disabled = true;
    }

    /// <summary>
    /// The retrieve counterpart: every Retrieve on the list is taken away, since one card takes
    /// one ship and the server would refuse a second anyway, and the pressed row says what is
    /// happening until the next state redraws the list.
    /// </summary>
    private void BeginRetrieveFeedback(DrydockBerthRow row)
    {
        _retrievingFor = 0f;
        _retrievingRow = row;
        foreach (var other in Berths.Children.OfType<DrydockBerthRow>())
            other.RetrieveButton.Disabled = true;
    }

    /// <summary>
    /// Triad: one row per berth. Retrieve is the row's one button, shown only when it would work;
    /// the rarer verbs sit in the row's menu, ship verbs above a rule and berth verbs below it,
    /// with a disabled entry saying why. The berth an offer on the tab would land in says what is
    /// coming in place of "empty".
    /// </summary>
    private void PopulateBerths(List<DrydockBerthInfo> berths, bool canRetrieve)
    {
        Berths.RemoveAllChildren();

        // Fresh rows are the server answering, so any retrieve in flight is over.
        _retrievingFor = -1f;
        _retrievingRow = null;
        _lastCanRetrieve = canRetrieve;

        var incoming = new Dictionary<int, string>();
        foreach (var offer in _lastOffers)
        {
            if (offer.LandsInBerthId is { } lands)
                incoming.TryAdd(lands, offer.ShipName);
        }

        foreach (var berth in berths)
        {
            var row = new DrydockBerthRow(berth, canRetrieve, incoming.GetValueOrDefault(berth.BerthId));
            row.RetrieveButton.OnPressed += _ =>
            {
                if (row.OccupantShipId is not { } shipId)
                    return;

                BeginRetrieveFeedback(row);
                OnRetrieve?.Invoke(shipId);
            };

            if (berth.OccupantTransferId is { } transferId)
            {
                row.CancelButton.Disabled = !_validId;
                row.CancelButton.OnPressed += _ => OnCancelTransfer?.Invoke(transferId);
                _escrowRows.Add((row, berth.OccupantOfferSecondsLeft ?? 0));
            }

            var items = new List<DrydockMenuButton.Item>();
            var occupied = berth.OccupantShipId != null;

            if (berth.OccupantShipId is { } occupant && berth.OccupantState == "Stored")
            {
                var shipName = berth.OccupantName ?? "?";
                var shipClass = berth.OccupantSizeClass;
                var fromBerth = berth.BerthId;
                var elsewhere = berths.Where(b => b.BerthId != fromBerth && b.OccupantShipId == null && ClassFits(shipClass, b.MaxSizeClass)).ToList();

                items.Add(new DrydockMenuButton.Item(Loc.GetString("shipyard-console-menu-rename"), null, _validId,
                    () => OpenRenamePrompt(occupant, shipName)));
                items.Add(new DrydockMenuButton.Item(Loc.GetString("shipyard-console-menu-move"),
                    elsewhere.Count == 0 ? Loc.GetString("shipyard-console-menu-nowhere") : null, _validId && elsewhere.Count > 0,
                    () => OpenMovePicker(occupant, shipName, elsewhere)));
                items.Add(new DrydockMenuButton.Item(Loc.GetString("shipyard-console-menu-transfer"), null, _validId,
                    () => OpenTransferPicker(occupant, shipName, shipClass, fromBerth)));
                items.Add(new DrydockMenuButton.Item(Loc.GetString("shipyard-console-menu-sell"),
                    berth.OccupantSellPrice is { } sellPrice ? BankSystemExtensions.ToSpesoString(sellPrice) : Loc.GetString("shipyard-console-menu-no-appraisal"),
                    _validId && berth.OccupantSellPrice != null,
                    () => OpenSellPrompt(occupant, shipName, berth.OccupantSellPrice ?? 0, berth.OccupantAppraisal, fromBerth)));
            }

            // The berth verbs, under a rule when ship verbs precede them.
            var firstBerthVerb = items.Count;

            if (berth.UpgradePrice is { } price && berth.UpgradeClass != null)
            {
                items.Add(new DrydockMenuButton.Item(Loc.GetString("shipyard-console-menu-upgrade-berth"),
                    BankSystemExtensions.ToSpesoString(price), _validId,
                    () => OnUpgradeBerth?.Invoke(row.BerthId),
                    DividerAbove: firstBerthVerb > 0 && items.Count == firstBerthVerb));
            }

            items.Add(new DrydockMenuButton.Item(Loc.GetString("shipyard-console-menu-sell-berth"),
                occupied ? Loc.GetString("shipyard-console-menu-occupied") : $"+{BankSystemExtensions.ToSpesoString(berth.SellValue)}",
                !occupied && _validId,
                () => OnSellBerth?.Invoke(row.BerthId),
                DividerAbove: firstBerthVerb > 0 && items.Count == firstBerthVerb));

            row.MenuButton.SetItems(items);
            Berths.AddChild(row);
        }
    }

    /// <summary>Triad: Buy berth drops the class ladder with its prices.</summary>
    private void PopulateBuyMenu(Dictionary<string, int> prices)
    {
        BuyBerthButton.SetItems(prices.Select(pair => new DrydockMenuButton.Item(
            DrydockText.Class(pair.Key),
            BankSystemExtensions.ToSpesoString(pair.Value),
            _validId,
            () => OnBuyBerth?.Invoke(pair.Key))));
    }

    /// <summary>
    /// Triad: the picker for Transfer…, filled from the captains the last state listed with how
    /// many free berths each has, greyed when none of them would take the ship. Offer commits.
    /// </summary>
    private void OpenTransferPicker(Guid shipId, string shipName, string? shipClass, int berthId)
    {
        var items = _lastCaptains
            .OrderBy(c => c.Name, StringComparer.CurrentCultureIgnoreCase)
            .Select(captain =>
            {
                var fits = captain.FreeBerthClasses.Any(berthClass => ClassFits(shipClass, berthClass));
                var recipient = captain.UserId;
                return new DrydockListPicker.Item(
                    captain.Name,
                    fits
                        ? Loc.GetString("shipyard-console-transfer-picker-berths", ("count", captain.FreeBerthClasses.Count))
                        : Loc.GetString("shipyard-console-transfer-picker-no-berth"),
                    fits,
                    () => OnOfferTransfer?.Invoke(shipId, recipient));
            })
            .ToList();

        new DrydockListPicker(
            Loc.GetString("shipyard-console-transfer-picker-title", ("ship", shipName)),
            Loc.GetString("shipyard-console-transfer-picker-placeholder"),
            Loc.GetString("shipyard-console-transfer-picker-body", ("ship", shipName), ("berth", berthId), ("minutes", _offerMinutes)),
            Loc.GetString("shipyard-console-transfer-picker-button"),
            Loc.GetString("shipyard-console-transfer-picker-empty"),
            items).OpenCentered();
    }

    /// <summary>Triad: the picker for Move…, listing the operator's other empty berths the ship fits.</summary>
    private void OpenMovePicker(Guid shipId, string shipName, List<DrydockBerthInfo> targets)
    {
        var items = targets
            .Select(target =>
            {
                var berthId = target.BerthId;
                return new DrydockListPicker.Item(
                    Loc.GetString("shipyard-console-move-item", ("berth", berthId)),
                    DrydockText.Class(target.MaxSizeClass),
                    true,
                    () => OnMoveStoredShip?.Invoke(shipId, berthId));
            })
            .ToList();

        new DrydockListPicker(
            Loc.GetString("shipyard-console-move-title", ("ship", shipName)),
            null,
            null,
            Loc.GetString("shipyard-console-move-button"),
            Loc.GetString("shipyard-console-menu-nowhere"),
            items).OpenCentered();
    }

    /// <summary>Triad: Rename…, one sentence, the allowed shape as the placeholder, a counter beside the field.</summary>
    private void OpenRenamePrompt(Guid shipId, string shipName)
    {
        new DrydockTextPrompt(
            Loc.GetString("shipyard-console-rename-title", ("ship", shipName)),
            Loc.GetString("shipyard-console-rename-body"),
            null,
            Loc.GetString("shipyard-console-rename-placeholder"),
            Loc.GetString("shipyard-console-rename-button"),
            IsValidStoredShipName,
            30,
            destructive: false,
            name => OnRenameStoredShip?.Invoke(shipId, name.Trim())).OpenCentered();
    }

    /// <summary>
    /// Triad: Sell…, saying what the scrap pays against the hull's appraisal and which berth it
    /// frees, locked until the ship's exact name is typed. The server compares again.
    /// </summary>
    private void OpenSellPrompt(Guid shipId, string shipName, int price, int? appraisal, int berthId)
    {
        var basis = appraisal is > 0 ? appraisal.Value : price;
        var percent = basis > 0 ? (int)Math.Round(price * 100.0 / basis) : 100;

        new DrydockTextPrompt(
            Loc.GetString("shipyard-console-sell-title", ("ship", shipName)),
            Loc.GetString("shipyard-console-sell-body",
                ("ship", shipName),
                ("price", BankSystemExtensions.ToSpesoString(price)),
                ("percent", percent),
                ("appraisal", BankSystemExtensions.ToSpesoString(basis)),
                ("berth", berthId)),
            Loc.GetString("shipyard-console-sell-warning"),
            Loc.GetString("shipyard-console-sell-placeholder", ("ship", shipName)),
            Loc.GetString("shipyard-console-sell-button"),
            typed => string.Equals(typed.Trim(), shipName, StringComparison.Ordinal),
            null,
            destructive: true,
            typed => OnSellStoredShip?.Invoke(shipId, typed.Trim())).OpenCentered();
    }

    /// <summary>
    /// Triad: the same rule the server applies to a stored ship's new name, so the button greys
    /// on the same input the server would refuse. Thirty characters is the deed's own limit.
    /// </summary>
    private static bool IsValidStoredShipName(string name)
    {
        name = name.Trim();
        if (name.Length == 0 || name.Length > 30)
            return false;

        foreach (var c in name)
        {
            if (!char.IsAsciiLetterOrDigit(c) && c != ' ' && c != '-')
                return false;
        }

        return true;
    }

    /// <summary>
    /// Triad: the same ladder the server's berth check walks: a berth takes any hull of its class
    /// or smaller. Unparseable text on either side is "does not fit", never a crash.
    /// </summary>
    private static bool ClassFits(string? shipClass, string berthClass)
    {
        return Enum.TryParse<ShipSizeClass>(shipClass, out var ship)
            && Enum.TryParse<ShipSizeClass>(berthClass, out var berth)
            && berth >= ship;
    }

    /// <summary>
    /// Triad: one alert per offer addressed to the operator, drawn as a line in the escrow amber:
    /// who offers what and where it lands, the clock, Accept, Decline. The last-berth warning
    /// sits under the first line whenever taking the ship would leave one of the operator's own
    /// with nowhere to dock; Accept is disabled outright when no free berth fits.
    /// </summary>
    private void PopulateOffers()
    {
        Offers.RemoveAllChildren();

        foreach (var offer in _lastOffers)
        {
            var panel = new PanelContainer
            {
                Margin = new Thickness(0, 0, 0, 10),
                PanelOverride = new StyleBoxFlat
                {
                    BorderThickness = new Thickness(2),
                    BorderColor = DrydockText.AmberBorder,
                    BackgroundColor = DrydockText.AmberFill,
                },
            };
            var line = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(10, 6), VerticalAlignment = VAlignment.Center };
            panel.AddChild(line);

            var text = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, HorizontalExpand = true, VerticalAlignment = VAlignment.Center };
            var headline = new FormattedMessage();
            headline.AddBold(offer.OfferedBy);
            headline.AddColored(" " + Loc.GetString("shipyard-console-transfer-offers") + " ", DrydockText.Dim);
            headline.AddBold(offer.ShipName);
            headline.AddColored(" " + (offer.LandsInBerthId is { } berth
                ? Loc.GetString("shipyard-console-transfer-into", ("class", DrydockText.Class(offer.SizeClass)), ("berth", berth))
                : Loc.GetString("shipyard-console-transfer-no-room", ("class", DrydockText.Class(offer.SizeClass)))), DrydockText.Dim);
            var headlineLabel = new RichTextLabel();
            headlineLabel.SetMessage(headline);
            text.AddChild(headlineLabel);

            if (offer.LandsInBerthId != null && WouldLeaveAShipWithoutABerth(consumes: 1))
            {
                var stranded = _lastDeedShip?.Name
                    ?? _lastShips.FirstOrDefault(s => s.State == "CheckedOut")?.Name
                    ?? Loc.GetString("shipyard-console-transfer-your-ship");
                text.AddChild(new Label
                {
                    Text = Loc.GetString("shipyard-console-transfer-warning", ("ship", stranded)),
                    Modulate = DrydockText.Warning,
                });
            }
            line.AddChild(text);

            var clock = new Label { Text = DrydockText.Left(offer.SecondsLeft), Modulate = DrydockText.Dim, Margin = new Thickness(12, 0) };
            line.AddChild(clock);
            _offerClocks.Add((clock, offer.SecondsLeft));

            var accept = new Button
            {
                Text = Loc.GetString("shipyard-console-transfer-accept-button"),
                StyleClasses = { "ButtonSquare", StyleNano.ButtonPrimary },
                MinWidth = 84,
                Disabled = !_validId || offer.LandsInBerthId == null,
            };
            var decline = new Button
            {
                Text = Loc.GetString("shipyard-console-transfer-decline-button"),
                StyleClasses = { "ButtonSquare" },
                MinWidth = 84,
                Margin = new Thickness(8, 0, 0, 0),
                Disabled = !_validId,
            };
            line.AddChild(accept);
            line.AddChild(decline);

            var transferId = offer.TransferId;
            accept.OnPressed += _ => OnAcceptTransfer?.Invoke(transferId);
            decline.OnPressed += _ => OnDeclineTransfer?.Invoke(transferId);

            Offers.AddChild(panel);
        }
    }
}
