using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Client._NF.Shipyard.BUI;
using Content.Shared._NF.Bank;
using Content.Shared._NF.Shipyard.BUI;
using Content.Shared._NF.Shipyard.Prototypes;
using Content.Shared._Triad.ShipSize;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._NF.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipyardConsoleMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _protoManager = default!;

    public event Action<ButtonEventArgs>? OnSellShip;
    public event Action<ButtonEventArgs>? OnSaveShip;
    public event Action<ButtonEventArgs>? OnOrderApproved;
    public event Action<ButtonEventArgs>? OnUnassignDeed;
    public event Action<string>? OnRenameShip;
    // Triad: drydock tab. Store carries only the berth to land in, because the server resolves the
    // ship from the card in the slot; retrieve carries the id of the row that was clicked.
    public event Action<int?>? OnStore;
    public event Action<Guid>? OnRetrieve;
    public event Action<string>? OnBuyBerth;
    public event Action<int>? OnSellBerth;
    public event Action<int>? OnUpgradeBerth;
    // A transfer names the ship and the account it goes to; the answers name the offer row.
    public event Action<Guid, Guid>? OnOfferTransfer;
    public event Action<long>? OnCancelTransfer;
    public event Action<long>? OnAcceptTransfer;
    public event Action<long>? OnDeclineTransfer;
    // Sell carries the name the player typed; the server compares it with the ship's own.
    public event Action<Guid, string>? OnSellStoredShip;
    public event Action<Guid, string>? OnRenameStoredShip;
    public event Action<Guid, int>? OnMoveStoredShip;

    /// <summary>
    /// Triad: the viewing account, so the tab can tell the operator from everyone else looking.
    /// One console state is shared by every viewer, so this is decided here.
    /// </summary>
    public Guid? LocalUserId;

    private int? _defaultBerth;

    /// <summary>The offer whose Accept has been pressed once past the last-berth warning, if any.</summary>
    private long? _armedOffer;

    // The offer clocks. The state carries seconds left as of when the server built it; the tab
    // counts down from there between states rather than asking the server every second.
    private float _sinceState;
    private int _lastElapsed = -1;
    private readonly List<(Label Label, string Prefix, int Seconds)> _offerClocks = new();
    private readonly List<(DrydockBerthRow Row, int Seconds)> _escrowRows = new();
    private List<DrydockCaptainInfo> _lastCaptains = new();
    private readonly List<VesselSize> _categoryStrings = new();
    private readonly List<VesselClass> _classStrings = new();
    private readonly List<VesselEngine> _engineStrings = new();
    private VesselSize? _category;
    private VesselClass? _class;
    private VesselEngine? _engine;

    private List<string> _lastAvailableProtos = new();
    private List<string> _lastUnavailableProtos = new();
    private bool _freeListings = false;
    private bool _validId = false;

    public ShipyardConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Title = Loc.GetString("shipyard-console-menu-title");
        SearchBar.OnTextChanged += OnSearchBarTextChanged;
        Categories.OnItemSelected += OnCategoryItemSelected;
        Classes.OnItemSelected += OnClassItemSelected;
        Engines.OnItemSelected += OnEngineItemSelected;
        SellShipButton.OnPressed += (args) => { OnSellShip?.Invoke(args); };
        UnassignDeedButton.OnPressed += (args) => { OnUnassignDeed?.Invoke(args); };
        RenameButton.OnPressed += OnRenameButtonPressed;

        // Triad: drydock tab
        Tabs.SetTabTitle(0, Loc.GetString("shipyard-console-tab-purchase"));
        Tabs.SetTabTitle(1, Loc.GetString("shipyard-console-tab-drydock"));
        StoreButton.OnPressed += _ => OnStore?.Invoke(_defaultBerth);
        SaveShipButton.OnPressed += (args) => { OnSaveShip?.Invoke(args); };
    }

    /// <summary>
    /// Triad: the offer clocks tick here, once a second, from the last state the server sent. A
    /// clock that reaches zero stays at zero until the next state says the offer is gone.
    /// </summary>
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _sinceState += args.DeltaSeconds;
        var elapsed = (int)_sinceState;
        if (elapsed == _lastElapsed)
            return;

        _lastElapsed = elapsed;
        foreach (var (label, prefix, seconds) in _offerClocks)
            label.Text = $"{prefix} · {DrydockClock.Left(seconds - elapsed)}";
        foreach (var (row, seconds) in _escrowRows)
            row.SetTimeLeft(seconds - elapsed);
    }

    private List<StoredShipInfo> _lastShips = new();
    private List<DrydockBerthInfo> _lastBerths = new();

    private bool WouldLeaveAShipWithoutABerth(int consumes)
    {
        var free = _lastBerths.Count(b => b.OccupantShipId == null);
        var shipsOut = _lastShips.Count(s => s.State == "CheckedOut");
        return shipsOut > 0 && free - consumes < shipsOut;
    }


    private void OnCategoryItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetCategoryText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnClassItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetClassText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnEngineItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetEngineText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnRenameButtonPressed(ButtonEventArgs args)
    {
        var newName = RenameLineEdit.Text.Trim();
        if (string.IsNullOrEmpty(newName))
            return;

        // Validate length (30 characters max, matching ShuttleDeedComponent.MaxNameLength)
        if (newName.Length > 30)
        {
            newName = newName[..30];
        }

        OnRenameShip?.Invoke(newName);
        RenameLineEdit.Text = "";
    }

    private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
    {
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void SetCategoryText(int id)
    {
        _category = id == 0 ? null : _categoryStrings[id];
        Categories.SelectId(id);
    }
    private void SetClassText(int id)
    {
        _class = id == 0 ? null : _classStrings[id];
        Classes.SelectId(id);
    }
    private void SetEngineText(int id)
    {
        _engine = id == 0 ? null : _engineStrings[id];
        Engines.SelectId(id);
    }
    /// <summary>
    ///     Populates the list of products that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateProducts(List<string> availablePrototypes, List<string> unavailablePrototypes, bool free, bool canPurchase)
    {
        Vessels.RemoveAllChildren();

        var search = SearchBar.Text.Trim().ToLowerInvariant();

        var newVessels = GetVesselPrototypesFromIds(availablePrototypes);
        AddVesselsToControls(newVessels, search, free, canPurchase);

        var newUnavailableVessels = GetVesselPrototypesFromIds(unavailablePrototypes);
        AddVesselsToControls(newUnavailableVessels, search, free, false);

        _lastAvailableProtos = availablePrototypes;
        _lastUnavailableProtos = unavailablePrototypes;
    }

    /// <summary>
    /// Given a set of prototype IDs, returns a corresponding set of prototypes, ordered by name.
    /// </summary>
    private List<VesselPrototype?> GetVesselPrototypesFromIds(IEnumerable<string> protoIds)
    {
        var vesselList = protoIds.Select(it => _protoManager.TryIndex<VesselPrototype>(it, out var proto) ? proto : null)
            .Where(it => it != null)
            .ToList();

        vesselList.Sort((x, y) =>
            string.Compare(x!.Name, y!.Name, StringComparison.CurrentCultureIgnoreCase));
        return vesselList;
    }

    /// <summary>
    /// Adds all vessels in a given list of prototypes as VesselRows in the UI.
    /// </summary>
    private void AddVesselsToControls(IEnumerable<VesselPrototype?> vessels, string search, bool free, bool canPurchase)
    {
        foreach (var prototype in vessels)
        {
            // Filter any ships
            if (_category != null && !prototype!.Category.Equals(_category))
                continue;
            if (_class != null && !prototype!.Classes.Contains(_class.Value))
                continue;
            if (_engine != null && !prototype!.Engines.Contains(_engine.Value))
                continue;
            if (search.Length > 0 && !prototype!.Name.ToLowerInvariant().Contains(search))
                continue;

            string priceText;
            if (free)
                priceText = Loc.GetString("shipyard-console-menu-listing-free");
            else if (prototype != null && !prototype.Purchasable) // Mono
                priceText = Loc.GetString("shipyard-console-menu-listing-voucher");
            else
                priceText = BankSystemExtensions.ToSpesoString(prototype!.Price);

            var vesselEntry = new VesselRow
            {
                Vessel = prototype,
                VesselName = { Text = prototype!.Name },
                Purchase = { Text = Loc.GetString("shipyard-console-purchase-available"), Disabled = !canPurchase },
                Guidebook = { Disabled = prototype.GuidebookPage is null, TooltipDelay = 0.2f, ToolTip = prototype.Description },
                Price = { Text = priceText },
            };
            vesselEntry.Purchase.OnPressed += (args) => { OnOrderApproved?.Invoke(args); };
            Vessels.AddChild(vesselEntry);
        }
    }

    /// <summary>
    ///     Populates the list categories that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateCategories(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _categoryStrings.Clear();
        Categories.Clear();

        AddCategoriesFromPrototypes(availablePrototypes);
        AddCategoriesFromPrototypes(unavailablePrototypes);

        _categoryStrings.Sort();

        // Add "All" category at the top of the list
        _categoryStrings.Insert(0, VesselSize.All);

        foreach (var str in _categoryStrings)
        {
            Categories.AddItem(Loc.GetString($"shipyard-console-category-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship categories from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddCategoriesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            if (!_categoryStrings.Contains(prototype.Category) && prototype.Category != VesselSize.All)
            {
                _categoryStrings.Add(prototype.Category);
            }
        }
    }

    /// <summary>
    ///     Populates the list classes that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateClasses(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _classStrings.Clear();
        Classes.Clear();

        AddClassesFromPrototypes(availablePrototypes);
        AddClassesFromPrototypes(unavailablePrototypes);

        _classStrings.Sort();

        // Add "All" category at the top of the list
        _classStrings.Insert(0, VesselClass.All);

        foreach (var str in _classStrings)
        {
            Classes.AddItem(Loc.GetString($"shipyard-console-class-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship classes from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddClassesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            foreach (var cl in prototype.Classes)
            {
                if (!_classStrings.Contains(cl) && cl != VesselClass.All)
                {
                    _classStrings.Add(cl);
                }
            }
        }
    }

    /// <summary>
    ///     Populates the list engines that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateEngines(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _engineStrings.Clear();
        Engines.Clear();

        AddEnginesFromPrototypes(availablePrototypes);
        AddEnginesFromPrototypes(unavailablePrototypes);

        _engineStrings.Sort();

        // Add "All" category at the top of the list
        _engineStrings.Insert(0, VesselEngine.All);

        foreach (var str in _engineStrings)
        {
            Engines.AddItem(Loc.GetString($"shipyard-console-engine-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship engine power type from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddEnginesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            foreach (var cl in prototype.Engines)
            {
                if (!_engineStrings.Contains(cl) && cl != VesselEngine.All)
                {
                    _engineStrings.Add(cl);
                }
            }
        }
    }

    public void UpdateState(ShipyardConsoleInterfaceState state)
    {
        BalanceLabel.Text = BankSystemExtensions.ToSpesoString(state.Balance);
        var shipPrice = 0;
        if (!state.FreeListings)
            shipPrice = state.ShipSellValue;

        ShipAppraisalLabel.Text = $"{BankSystemExtensions.ToSpesoString(shipPrice)} ({state.SellRate * 100.0f:F1}%)";
        SellShipButton.Disabled = state.ShipDeedTitle == null;
        UnassignDeedButton.Disabled = state.ShipDeedTitle == null;

        // Show/hide and enable/disable rename controls based on whether there's a ship deed
        var hasShipDeed = state.ShipDeedTitle != null;
        RenameContainer.Visible = hasShipDeed;
        RenameLineEdit.Editable = hasShipDeed;
        RenameButton.Disabled = !hasShipDeed;

        SaveShipButton.Disabled = !state.IsTargetIdPresent;
        LoadShipButton.Disabled = !state.IsTargetIdPresent;
        LoadShipButton.ToolTip = state.IsTargetIdPresent
            ? null
            : Loc.GetString("shipyard-console-load-ship-no-id");
        TargetIdButton.Text = state.IsTargetIdPresent
            ? Loc.GetString("id-card-console-window-eject-button")
            : Loc.GetString("id-card-console-window-insert-button");
        if (state.ShipDeedTitle != null)
        {
            DeedTitle.Text = state.ShipDeedTitle;
        }
        else
        {
            DeedTitle.Text = $"None";
        }
        _freeListings = state.FreeListings;
        _validId = state.IsTargetIdPresent;
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);

        // Triad: drydock tab. Hidden outright when the master switch is off, rather than shown with
        // buttons that would every one of them come back refused.
        Tabs.SetTabVisible(1, state.DrydockEnabled);

        // The lockout: someone else's registered card in the slot. Decided here because one console
        // state is shared by every viewer and only the client knows which viewer it is.
        LockoutPanel.Visible = LocalUserId != null && state.DeedOwnerUserId is { } deedOwner && deedOwner != LocalUserId;

        _lastShips = state.StoredShips;
        _lastBerths = state.Berths;
        _lastCaptains = state.Captains;
        _armedOffer = null;
        _sinceState = 0f;
        _lastElapsed = -1;
        _offerClocks.Clear();
        _escrowRows.Clear();
        PopulateDeedShip(state.DeedShip);
        PopulateOffers(state.TransferOffers);
        PopulateBerths(state.Berths, canRetrieve: state.IsTargetIdPresent && state.ShipDeedTitle == null);
        PopulateBuyMenu(state.BerthPrices);

        var free = state.Berths.Count(b => b.OccupantShipId == null);
        BerthSummaryLabel.Text = Loc.GetString("shipyard-console-berths-free", ("free", free), ("total", state.Berths.Count));
    }

    /// <summary>
    /// Triad: the card at the top. Store lands in the server's preferred berth; the arrow beside it
    /// lists the other free berths the hull fits. With nothing that fits, Store says so and stays
    /// disabled rather than sending a request the server would refuse.
    /// </summary>
    private void PopulateDeedShip(DrydockDeedShipInfo? ship)
    {
        DeedShipPanel.Visible = ship != null;
        _defaultBerth = ship?.DefaultBerthId;
        if (ship == null)
            return;

        DeedShipLabel.Text = ship.MinutesOut is { } minutes
            ? Loc.GetString("shipyard-console-deed-ship-out", ("ship", ship.Name), ("class", ship.SizeClass ?? "?"), ("minutes", minutes))
            : Loc.GetString("shipyard-console-deed-ship-new", ("ship", ship.Name), ("class", ship.SizeClass ?? "?"));

        StoreButton.Text = ship.DefaultBerthId is { } berth
            ? Loc.GetString("shipyard-console-store-in-button", ("berth", berth))
            : Loc.GetString("shipyard-console-store-no-fit-button");
        StoreButton.Disabled = ship.DefaultBerthId == null || !_validId;

        StoreMenuButton.SetItems(ship.FittingBerthIds
            .Where(id => id != ship.DefaultBerthId)
            .Select(id => new DrydockMenuButton.Item(
                Loc.GetString("shipyard-console-store-in-button", ("berth", id)),
                _lastBerths.FirstOrDefault(b => b.BerthId == id)?.MaxSizeClass,
                _validId,
                () => OnStore?.Invoke(id))));
    }

    /// <summary>
    /// Triad: one row per berth. Retrieve is the row's one button, shown only when it would work;
    /// the rarer verbs sit in the row's menu, with a disabled entry saying why.
    /// </summary>
    private void PopulateBerths(List<DrydockBerthInfo> berths, bool canRetrieve)
    {
        Berths.RemoveAllChildren();

        foreach (var berth in berths)
        {
            var row = new DrydockBerthRow(berth, canRetrieve);
            row.RetrieveButton.OnPressed += _ =>
            {
                if (row.OccupantShipId is { } shipId)
                    OnRetrieve?.Invoke(shipId);
            };

            if (berth.OccupantTransferId is { } transferId)
            {
                row.CancelButton.Disabled = !_validId;
                row.CancelButton.OnPressed += _ => OnCancelTransfer?.Invoke(transferId);
                _escrowRows.Add((row, berth.OccupantOfferSecondsLeft ?? 0));
            }

            var items = new List<DrydockMenuButton.Item>();
            var occupied = berth.OccupantShipId != null;

            if (berth.OccupantShipId is { } occupant && berth.OccupantState == "Stored")
            {
                var shipName = berth.OccupantName ?? "?";
                var shipClass = berth.OccupantSizeClass;
                var fromBerth = berth.BerthId;
                var elsewhere = berths.Where(b => b.BerthId != fromBerth && b.OccupantShipId == null && ClassFits(shipClass, b.MaxSizeClass)).ToList();

                items.Add(new DrydockMenuButton.Item(Loc.GetString("shipyard-console-menu-rename"), null, _validId,
                    () => OpenRenamePrompt(occupant, shipName)));
                items.Add(new DrydockMenuButton.Item(Loc.GetString("shipyard-console-menu-move"),
                    elsewhere.Count == 0 ? Loc.GetString("shipyard-console-menu-nowhere") : null, _validId && elsewhere.Count > 0,
                    () => OpenMovePicker(occupant, shipName, elsewhere)));
                items.Add(new DrydockMenuButton.Item(Loc.GetString("shipyard-console-menu-transfer"), null, _validId,
                    () => OpenTransferPicker(occupant, shipName, shipClass)));
                items.Add(new DrydockMenuButton.Item(Loc.GetString("shipyard-console-menu-sell"),
                    berth.OccupantSellPrice is { } sellPrice ? BankSystemExtensions.ToSpesoString(sellPrice) : Loc.GetString("shipyard-console-menu-no-appraisal"),
                    _validId && berth.OccupantSellPrice != null,
                    () => OpenSellPrompt(occupant, shipName, berth.OccupantSellPrice ?? 0)));
            }

            if (berth.UpgradePrice is { } price && berth.UpgradeClass != null)
            {
                items.Add(new DrydockMenuButton.Item(Loc.GetString("shipyard-console-menu-upgrade-berth"),
                    $"{berth.UpgradeClass} {BankSystemExtensions.ToSpesoString(price)}", _validId,
                    () => OnUpgradeBerth?.Invoke(row.BerthId)));
            }

            items.Add(new DrydockMenuButton.Item(Loc.GetString("shipyard-console-menu-sell-berth"),
                occupied ? Loc.GetString("shipyard-console-menu-occupied") : $"+{BankSystemExtensions.ToSpesoString(berth.SellValue)}",
                !occupied && _validId,
                () => OnSellBerth?.Invoke(row.BerthId)));

            row.MenuButton.SetItems(items);
            Berths.AddChild(row);
        }
    }

    /// <summary>Triad: Buy berth drops the class ladder with its prices.</summary>
    private void PopulateBuyMenu(Dictionary<string, int> prices)
    {
        BuyBerthButton.SetItems(prices.Select(pair => new DrydockMenuButton.Item(
            pair.Key,
            BankSystemExtensions.ToSpesoString(pair.Value),
            _validId,
            () => OnBuyBerth?.Invoke(pair.Key))));
    }

    /// <summary>
    /// Triad: the picker for Transfer…, filled from the captains the last state listed, greyed
    /// when none of their free berths would take the ship.
    /// </summary>
    private void OpenTransferPicker(Guid shipId, string shipName, string? shipClass)
    {
        var items = _lastCaptains
            .OrderBy(c => c.Name, StringComparer.CurrentCultureIgnoreCase)
            .Select(captain =>
            {
                var fits = captain.FreeBerthClasses.Any(berthClass => ClassFits(shipClass, berthClass));
                var recipient = captain.UserId;
                return new DrydockListPicker.Item(
                    captain.Name,
                    fits ? string.Join(", ", captain.FreeBerthClasses.Distinct()) : Loc.GetString("shipyard-console-transfer-picker-no-berth"),
                    fits,
                    () => OnOfferTransfer?.Invoke(shipId, recipient));
            })
            .ToList();

        new DrydockListPicker(
            Loc.GetString("shipyard-console-transfer-picker-title", ("ship", shipName)),
            Loc.GetString("shipyard-console-transfer-picker-hint"),
            Loc.GetString("shipyard-console-transfer-picker-empty"),
            items).OpenCentered();
    }

    /// <summary>Triad: the picker for Move…, listing the operator's other empty berths the ship fits.</summary>
    private void OpenMovePicker(Guid shipId, string shipName, List<DrydockBerthInfo> targets)
    {
        var items = targets
            .Select(target =>
            {
                var berthId = target.BerthId;
                return new DrydockListPicker.Item(
                    Loc.GetString("shipyard-console-move-item", ("berth", berthId)),
                    target.MaxSizeClass,
                    true,
                    () => OnMoveStoredShip?.Invoke(shipId, berthId));
            })
            .ToList();

        new DrydockListPicker(
            Loc.GetString("shipyard-console-move-title", ("ship", shipName)),
            Loc.GetString("shipyard-console-move-hint"),
            Loc.GetString("shipyard-console-menu-nowhere"),
            items).OpenCentered();
    }

    /// <summary>Triad: Rename…, with the allowed shape as the placeholder and a counter beside the field.</summary>
    private void OpenRenamePrompt(Guid shipId, string shipName)
    {
        new DrydockTextPrompt(
            Loc.GetString("shipyard-console-rename-title", ("ship", shipName)),
            null,
            Loc.GetString("shipyard-console-rename-placeholder"),
            Loc.GetString("shipyard-console-rename-button"),
            IsValidStoredShipName,
            30,
            name => OnRenameStoredShip?.Invoke(shipId, name.Trim())).OpenCentered();
    }

    /// <summary>Triad: Sell…, locked until the ship's exact name is typed. The server compares again.</summary>
    private void OpenSellPrompt(Guid shipId, string shipName, int price)
    {
        new DrydockTextPrompt(
            Loc.GetString("shipyard-console-sell-title", ("ship", shipName)),
            Loc.GetString("shipyard-console-sell-body", ("ship", shipName), ("price", BankSystemExtensions.ToSpesoString(price))),
            Loc.GetString("shipyard-console-sell-placeholder", ("ship", shipName)),
            Loc.GetString("shipyard-console-sell-button"),
            typed => string.Equals(typed.Trim(), shipName, StringComparison.Ordinal),
            null,
            typed => OnSellStoredShip?.Invoke(shipId, typed.Trim())).OpenCentered();
    }

    /// <summary>
    /// Triad: the same rule the server applies to a stored ship's new name, so the button greys
    /// on the same input the server would refuse. Thirty characters is the deed's own limit.
    /// </summary>
    private static bool IsValidStoredShipName(string name)
    {
        name = name.Trim();
        if (name.Length == 0 || name.Length > 30)
            return false;

        foreach (var c in name)
        {
            if (!char.IsAsciiLetterOrDigit(c) && c != ' ' && c != '-')
                return false;
        }

        return true;
    }

    /// <summary>
    /// Triad: the same ladder the server's berth check walks: a berth takes any hull of its class
    /// or smaller. Unparseable text on either side is "does not fit", never a crash.
    /// </summary>
    private static bool ClassFits(string? shipClass, string berthClass)
    {
        return Enum.TryParse<ShipSizeClass>(shipClass, out var ship)
            && Enum.TryParse<ShipSizeClass>(berthClass, out var berth)
            && berth >= ship;
    }

    /// <summary>
    /// Triad: one alert per offer addressed to the operator. Accept is disabled outright when no
    /// free berth fits; the last-berth warning is armed by the first press of Accept and never
    /// shown pre-emptively, and a fresh state disarms it again.
    /// </summary>
    private void PopulateOffers(List<DrydockTransferOfferInfo> offers)
    {
        Offers.RemoveAllChildren();

        foreach (var offer in offers)
        {
            // Never an alert for one's own offer; the escrow row already says it.
            if (LocalUserId != null && offer.OfferedByUserId == LocalUserId)
                continue;

            var panel = new PanelContainer
            {
                Margin = new Thickness(0, 8, 0, 6),
                PanelOverride = new StyleBoxFlat
                {
                    BorderThickness = new Thickness(2),
                    BorderColor = Color.FromHex("#3e5e82"),
                    BackgroundColor = Color.FromHex("#1a2430"),
                },
            };
            var body = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(6, 4) };
            panel.AddChild(body);

            body.AddChild(new Label
            {
                Text = Loc.GetString("shipyard-console-transfer-offer",
                    ("owner", offer.OfferedBy), ("ship", offer.ShipName), ("class", offer.SizeClass ?? "?")),
            });

            var prefix = offer.LandsInBerthId is { } berth
                ? Loc.GetString("shipyard-console-transfer-lands-in", ("berth", berth))
                : Loc.GetString("shipyard-console-transfer-no-room");
            var clock = new Label { Text = $"{prefix} · {DrydockClock.Left(offer.SecondsLeft)}", Modulate = Color.FromHex("#999999") };
            body.AddChild(clock);
            _offerClocks.Add((clock, prefix, offer.SecondsLeft));

            var warning = new Label
            {
                Text = Loc.GetString("shipyard-console-transfer-warning"),
                Modulate = Color.FromHex("#d9a441"),
                Visible = false,
            };
            body.AddChild(warning);

            var buttons = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 4, 0, 0) };
            var accept = new Button
            {
                Text = Loc.GetString("shipyard-console-transfer-accept-button"),
                StyleClasses = { "ButtonSquare" },
                MinWidth = 120,
                Disabled = !_validId || offer.LandsInBerthId == null,
            };
            var decline = new Button
            {
                Text = Loc.GetString("shipyard-console-transfer-decline-button"),
                StyleClasses = { "ButtonSquare", "ButtonCaution" },
                MinWidth = 100,
                Margin = new Thickness(4, 0, 0, 0),
                Disabled = !_validId,
            };
            buttons.AddChild(accept);
            buttons.AddChild(decline);
            body.AddChild(buttons);

            var transferId = offer.TransferId;
            accept.OnPressed += _ =>
            {
                if (_armedOffer != transferId && WouldLeaveAShipWithoutABerth(consumes: 1))
                {
                    _armedOffer = transferId;
                    warning.Visible = true;
                    accept.Text = Loc.GetString("shipyard-console-transfer-confirm-button");
                    return;
                }

                OnAcceptTransfer?.Invoke(transferId);
            };
            decline.OnPressed += _ => OnDeclineTransfer?.Invoke(transferId);

            Offers.AddChild(panel);
        }
    }
}
