- type: job
  id: DirectorOfCare
  name: job-name-doc
  description: job-description-doc
  playTimeTracker: JobDirectorOfCare
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 81000 # Triad - 22.5 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # Triad - 10 hours
  alternateRequirementSets: # mono
    longerPlaytimeLessSec: # mono
    - !type:OverallPlaytimeRequirement # mono
      time: 234000 # mono 65 hours
  startingGear: DocGear
  alwaysUseSpawner: true
  assignedCompany: MD
  icon: "JobIconDoc"
  requireAdminNotify: true
  supervisors: job-supervisors-overseer # Triad
  weight: 170
  displayWeight: 60 # Second from the top # mono - first from top
  canBeAntag: false
  accessGroups:
  - DirectorOfCare # Triad
  ranks: # Triad, ranks
    RankDoC: []
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ] # Triad - re-add sec implant
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: NpcFactionMember
        factions:
        - MD # mono faction
        - TDF # Triad - They aren't apart of the TDF, but they are friendly and work with them
      - type: SurgerySpeedModifier
        SpeedModifier: 2
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: DocGear
  equipment:
    pocket1: HypoMini
    pocket2: MedicalAppraisalTool
  storage:
    back:
    - RubberStampDoc
    - BoxFolderMedicalDoctor
    - StationAdministrationConsoleFlatpack
    - PhoneInstrumentHigh
    - EncryptionKeyService # Colonial Staff
