- type: job
  id: TdfPatrolTeamLeader
  name: job-name-tdf-patrol-team-leader
  description: job-description-tdf-patrol-team-leader
  playTimeTracker: JobTdfPatrolTeamLeader
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 108000 # 30 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # 15 hours
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 450000 # 125 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 # 5 hours
  startingGear: TdfLeaderGear
  alwaysUseSpawner: true
  icon: JobIconTdfPatrolTeamLeader
  supervisors: job-supervisors-tdf-lieutenant
  weight: 140
  displayWeight: 50
  assignedCompany: TDF
  canBeAntag: false
  accessGroups:
  - GeneralTdfAccessBrig
  access:
  - TdfPatrolTeamLeader
  - Command
  - Medical
  - Chemistry
  - TdfPermitControl
  ranks:
    RankSeniorEnforcer: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TDF
    - type: ShipSavingBlacklist # TDF can't save ships
    - type: CryoSleepRadioOverride
      overrides:
      - Nfsd # TDF radio
    - type: ContrabandPermitOwnerBlacklist # No giving the TDF permits!
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: TdfLeaderGear
  equipment:
    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
  storage:
    back:
    - Magazine45_ACPPistolFMJ
    - BaseSecurityUplinkRadioPatrolTeamLeader
    - RadioHandheldNF
    - ShipVoucherTdfTier0
