using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Triad.Chemistry.UI;

/// <summary>
/// Client-side UI used to control a <see cref="SharedChemMaster"/>
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ModernChemMasterWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entityManager = default!;
    private readonly SpriteSystem _sprite;
    public event Action<BaseButton.ButtonEventArgs, ReagentButton>? OnReagentButtonPressed;
    public readonly Button[] PillTypeButtons;

    private const string PillsRsiPath = "/Textures/Objects/Specific/Chemistry/pills.rsi";

    private ChemMasterBoundUserInterfaceState? _lastState;
    private static bool _classicMode; // Static since if you selected it, you probably want this. Dunno why though.

    private ChemMasterReagentAmount _selectedAmount = ChemMasterReagentAmount.U5;

    // Amount configs for the 2x5 modern grid: 9 numeric amounts + All.
    private static readonly (string Label, ChemMasterReagentAmount Amount)[] AmountConfigs =
    {
        ("1",   ChemMasterReagentAmount.U1),
        ("5",   ChemMasterReagentAmount.U5),
        ("10",  ChemMasterReagentAmount.U10),
        ("15",  ChemMasterReagentAmount.U15),
        ("20",  ChemMasterReagentAmount.U20),
        ("25",  ChemMasterReagentAmount.U25),
        ("30",  ChemMasterReagentAmount.U30),
        ("50",  ChemMasterReagentAmount.U50),
        ("100", ChemMasterReagentAmount.U100),
        (Loc.GetString("chem-master-window-buffer-all-amount"), ChemMasterReagentAmount.All),
    };

    /// <summary>
    /// Create and initialize the chem master UI client-side. Creates the basic layout,
    /// actual data isn't filled in until the server sends data about the chem master.
    /// </summary>
    public ModernChemMasterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entityManager.System<SpriteSystem>();

        // Pill type selection buttons, in total there are 20 pills.
        var resourcePath = new ResPath(PillsRsiPath);
        var pillTypeGroup = new ButtonGroup();
        PillTypeButtons = new Button[20];
        for (uint i = 0; i < PillTypeButtons.Length; i++)
        {
            var styleBase = StyleBase.ButtonOpenBoth;
            var modulo = i % 10;
            if (i > 0 && modulo == 0)
                styleBase = StyleBase.ButtonOpenRight;
            else if (i > 0 && modulo == 9)
                styleBase = StyleBase.ButtonOpenLeft;
            else if (i == 0)
                styleBase = StyleBase.ButtonOpenRight;

            PillTypeButtons[i] = new Button
            {
                Access = AccessLevel.Public,
                StyleClasses = { styleBase },
                MaxSize = new Vector2(42, 28),
                Group = pillTypeGroup
            };

            var specifier = new SpriteSpecifier.Rsi(resourcePath, "pill" + (i + 1));
            var pillTypeTexture = new TextureRect
            {
                Texture = _sprite.Frame0(specifier),
                TextureScale = new Vector2(1.75f, 1.75f),
                Stretch = TextureRect.StretchMode.KeepCentered,
            };

            PillTypeButtons[i].AddChild(pillTypeTexture);
            Grid.AddChild(PillTypeButtons[i]);
        }

        PillDosage.InitDefaultButtons();
        PillNumber.InitDefaultButtons();
        BottleDosage.InitDefaultButtons();

        LabelLineEdit.IsValid = s => s.Length <= SharedChemMaster.LabelMaxLength;

        SearchBar.OnTextChanged += (_) => UpdateReagentPrototypes(SearchBar.Text);

        ClassicTabs.SetTabTitle(0, Loc.GetString("chem-master-window-input-tab"));
        ClassicTabs.SetTabTitle(1, Loc.GetString("chem-master-window-output-tab"));

        ModernTabs.SetTabTitle(0, Loc.GetString("chem-master-window-input-tab"));
        ModernTabs.SetTabTitle(1, Loc.GetString("chem-master-window-output-tab"));

        // Build the amount 'grid' (2x5)
        BuildAmountGrid(AmountGrid);

        ApplyLayout();

        if (FindControl<Button>("ModernModeButton") is { } modernBtn)
        {
            modernBtn.OnPressed += _ =>
            {
                _classicMode = false;
                ApplyLayout();
            };
        }

        if (FindControl<Button>("ClassicModeButton") is { } classicBtn)
        {
            classicBtn.OnPressed += _ =>
            {
                _classicMode = true;
                ApplyLayout();
            };
        }
    }

    /// <summary>
    /// Builds a 2x5 amount selection grid into the given GridContainer.
    /// Both modern tabs get their own grid instance but share the _selectedAmount state.
    /// </summary>
    private void BuildAmountGrid(GridContainer grid)
    {
        var amountGroup = new ButtonGroup();

        foreach (var (label, amount) in AmountConfigs)
        {
            var btn = new Button
            {
                Access = AccessLevel.Public,
                Text = label,
                ToggleMode = true,
                Group = amountGroup,
                MinSize = new Vector2(46, 0),
                Pressed = amount == _selectedAmount,
                StyleClasses = { StyleBase.ButtonOpenBoth },
            };

            var capturedAmount = amount;
            btn.OnPressed += _ =>
            {
                OnAmountSelected?.Invoke(capturedAmount);
            };

            grid.AddChild(btn);
        }
    }

    private void SyncGrid(GridContainer grid)
    {
        var i = 0;
        foreach (var child in grid.Children)
        {
            if (child is Button btn && i < AmountConfigs.Length)
            {
                btn.Pressed = AmountConfigs[i].Amount == _selectedAmount;
                i++;
            }
        }
    }

    private void ApplyLayout()
    {
        ModernTabs.Visible = !_classicMode;
        ClassicTabs.Visible = _classicMode;
        if (FindControl<Button>("ModernModeButton") is { } modernBtn)
            modernBtn.Disabled = !_classicMode;

        if (FindControl<Button>("ClassicModeButton") is { } classicBtn)
            classicBtn.Disabled = _classicMode;
    }

    private ReagentButton MakeReagentButton(string text, ChemMasterReagentAmount amount, ReagentId id, bool isBuffer, string styleClass)
    {
        var reagentTransferButton = new ReagentButton(text, amount, id, isBuffer, styleClass);
        reagentTransferButton.OnPressed += args
            => OnReagentButtonPressed?.Invoke(args, reagentTransferButton);
        return reagentTransferButton;
    }

    /// <summary>
    /// Classic mode only: generates the full set of per-row amount buttons.
    /// Modern mode rows are buttons themselves - this is not called for them.
    /// </summary>
    private List<ReagentButton> CreateReagentTransferButtons(ReagentId reagent, bool isBuffer, bool addReagentButtons)
    {
        if (!addReagentButtons)
            return new List<ReagentButton>();

        // Classic: full button strip
        var buttonConfigs = new (string text, ChemMasterReagentAmount amount, string styleClass)[]
        {
            ("1",   ChemMasterReagentAmount.U1,   StyleBase.ButtonOpenBoth),
            ("5",   ChemMasterReagentAmount.U5,   StyleBase.ButtonOpenBoth),
            ("10",  ChemMasterReagentAmount.U10,  StyleBase.ButtonOpenBoth),
            ("15",  ChemMasterReagentAmount.U15,  StyleBase.ButtonOpenBoth),
            ("25",  ChemMasterReagentAmount.U25,  StyleBase.ButtonOpenBoth),
            ("30",  ChemMasterReagentAmount.U30,  StyleBase.ButtonOpenBoth),
            ("50",  ChemMasterReagentAmount.U50,  StyleBase.ButtonOpenBoth),
            ("100", ChemMasterReagentAmount.U100, StyleBase.ButtonOpenBoth),
            (Loc.GetString("chem-master-window-buffer-all-amount"), ChemMasterReagentAmount.All, StyleBase.ButtonOpenLeft),
        };

        var buttons = new List<ReagentButton>();
        foreach (var (text, amount, styleClass) in buttonConfigs)
        {
            buttons.Add(MakeReagentButton(text, amount, reagent, isBuffer, styleClass));
        }

        return buttons;
    }

    /// <summary>
    /// Update the UI state when new state data is received from the server.
    /// </summary>
    public void UpdateState(BoundUserInterfaceState state)
    {
        var castState = (ChemMasterBoundUserInterfaceState)state;
        _lastState = castState;

        if (castState.UpdateLabel)
            LabelLine = GenerateLabel(castState);

        UpdatePanelInfo(castState);

        switch (castState.DrawSource)
        {
            case ChemMasterDrawSource.Internal:
                SetBufferText(castState.BufferCurrentVolume, "chem-master-output-buffer-draw");
                break;
            case ChemMasterDrawSource.External:
                SetBufferText(castState.InputContainerInfo?.CurrentVolume, "chem-master-output-beaker-draw");
                break;
            default:
                throw new($"ChemMaster {castState.OutputContainerInfo} draw source is not set");
        }

        InputEjectButton.Disabled = castState.InputContainerInfo is null;
        OutputEjectButton.Disabled = castState.OutputContainerInfo is null;
        CreateBottleButton.Disabled = castState.OutputContainerInfo?.Reagents == null;
        CreatePillButton.Disabled = castState.OutputContainerInfo?.Entities == null;

        UpdateDosageFields(castState);
    }

    private void UpdateDosageFields(ChemMasterBoundUserInterfaceState castState)
    {
        var output = castState.OutputContainerInfo;
        var remainingCapacity = output is null ? 0 : (output.MaxVolume - output.CurrentVolume).Int();
        var holdsReagents = output?.Reagents != null;
        var pillNumberMax = holdsReagents ? 0 : remainingCapacity;
        var bottleAmountMax = holdsReagents ? remainingCapacity : 0;
        var outputVolume = castState.DrawSource switch
        {
            ChemMasterDrawSource.Internal => castState.BufferCurrentVolume?.Int() ?? 0,
            ChemMasterDrawSource.External => castState.InputContainerInfo?.CurrentVolume.Int() ?? 0,
            _ => 0,
        };

        PillDosage.Value = (int)Math.Min(outputVolume, castState.PillDosageLimit);
        PillTypeButtons[castState.SelectedPillType].Pressed = true;

        PillNumber.IsValid = x => x >= 0 && x <= pillNumberMax;
        PillDosage.IsValid = x => x > 0 && x <= castState.PillDosageLimit;
        BottleDosage.IsValid = x => x >= 0 && x <= bottleAmountMax;

        if (PillNumber.Value > pillNumberMax)
            PillNumber.Value = pillNumberMax;
        if (BottleDosage.Value > bottleAmountMax)
            BottleDosage.Value = bottleAmountMax;

        PillNumber.Value = PillDosage.Value > 0 ? Math.Min(outputVolume / PillDosage.Value, pillNumberMax) : 0;

        BottleDosage.Value = Math.Min(bottleAmountMax, outputVolume);
    }

    private string GenerateLabel(ChemMasterBoundUserInterfaceState state)
    {
        var reagents = state.DrawSource switch
        {
            ChemMasterDrawSource.Internal => state.BufferReagents,
            ChemMasterDrawSource.External => state.InputContainerInfo?.Reagents ?? [],
            _ => throw new($"Chemmaster {state.OutputContainerInfo} draw source is not set"),
        };

        if (!reagents.Any())
            return "";

        var reagent = reagents.MinBy(r => r.Quantity).Reagent;
        _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto);
        return proto?.LocalizedName ?? "";
    }

    private void UpdatePanelInfo(ChemMasterBoundUserInterfaceState state)
    {
        BufferTransferButton.Pressed = state.Mode == ChemMasterMode.Transfer;
        BufferDiscardButton.Pressed = state.Mode == ChemMasterMode.Discard;

        // Modern layout containers
        BuildContainerUI(InputContainerInfo, state.InputContainerInfo, true, modernMode: true);
        BuildContainerUI(OutputContainerInfo, state.OutputContainerInfo, false, modernMode: true);

        // Classic layout containers
        BuildContainerUI(InputContainerInfoClassic, state.InputContainerInfo, true, modernMode: false);
        BuildContainerUI(OutputContainerInfoClassic, state.OutputContainerInfo, false, modernMode: false);

        BufferInfo.Children.Clear();
        BufferInfoClassic.Children.Clear();

        var sortLabel = state.SortingType switch
        {
            ChemMasterSortingType.Alphabetical => Loc.GetString("chem-master-window-sort-type-alphabetical"),
            ChemMasterSortingType.Quantity => Loc.GetString("chem-master-window-sort-type-quantity"),
            ChemMasterSortingType.Latest => Loc.GetString("chem-master-window-sort-type-latest"),
            _ => Loc.GetString("chem-master-window-sort-type-none")
        };
        BufferSortButton.Text = sortLabel;
        BufferSortButtonClassic.Text = sortLabel;

        OutputBufferDraw.Pressed = state.DrawSource == ChemMasterDrawSource.Internal;
        OutputBeakerDraw.Pressed = state.DrawSource == ChemMasterDrawSource.External;

        if (!state.BufferReagents.Any())
        {
            var emptyLabel = new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") };
            var emptyLabelClassic = new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") };
            BufferInfo.Children.Add(emptyLabel);
            BufferInfoClassic.Children.Add(emptyLabelClassic);
            return;
        }

        // Buffer volume header row
        void AddBufferHeader(BoxContainer target)
        {
            var hbox = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            hbox.AddChild(new Label { Text = $"{Loc.GetString("chem-master-window-buffer-label")} " });
            hbox.AddChild(new Label
            {
                Text = $"{state.BufferCurrentVolume}u",
                StyleClasses = { StyleNano.StyleClassLabelSecondaryColor }
            });
            target.AddChild(hbox);
        }
        AddBufferHeader(BufferInfo);
        AddBufferHeader(BufferInfoClassic);

        var reagentList = new List<(ReagentId reagentId, string name, Color color, FixedPoint2 quantity)>();
        foreach (var (reagent, quantity) in state.BufferReagents)
        {
            _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto);
            var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
            var reagentColor = proto?.SubstanceColor ?? default(Color);
            reagentList.Add((reagent, name, reagentColor, quantity));
        }

        reagentList = state.SortingType switch
        {
            ChemMasterSortingType.Alphabetical => reagentList.OrderBy(x => x.name).ToList(),
            ChemMasterSortingType.Quantity => reagentList.OrderByDescending(x => x.quantity).ToList(),
            ChemMasterSortingType.Latest => Enumerable.Reverse(reagentList).ToList(),
            _ => reagentList
        };

        var rowCount = 0;
        foreach (var reagent in reagentList)
        {
            BufferInfo.Children.Add(BuildReagentRow(reagent.color, rowCount, reagent.name, reagent.reagentId, reagent.quantity, true, true, modernMode: true));
            BufferInfoClassic.Children.Add(BuildReagentRow(reagent.color, rowCount, reagent.name, reagent.reagentId, reagent.quantity, true, true, modernMode: false));
            rowCount++;
        }

        if (!string.IsNullOrEmpty(SearchBar.Text))
            UpdateReagentPrototypes(SearchBar.Text);
    }

    private void BuildContainerUI(Control control, ContainerInfo? info, bool addReagentButtons, bool modernMode)
    {
        control.Children.Clear();

        if (info is null)
        {
            control.Children.Add(new Label { Text = Loc.GetString("chem-master-window-no-container-loaded-text") });
            return;
        }

        control.Children.Add(new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Children =
            {
                new Label { Text = $"{info.DisplayName}: " },
                new Label
                {
                    Text = $"{info.CurrentVolume}/{info.MaxVolume}",
                    StyleClasses = { StyleNano.StyleClassLabelSecondaryColor }
                }
            }
        });

        var rowCount = 0;

        if (info.Entities != null)
        {
            foreach (var (id, quantity) in info.Entities.Select(x => (x.Id, x.Quantity)))
            {
                control.Children.Add(BuildReagentRow(default, rowCount++, id, default, quantity, false, addReagentButtons, modernMode));
            }
        }

        if (info.Reagents != null)
        {
            foreach (var reagent in info.Reagents)
            {
                _prototypeManager.TryIndex(reagent.Reagent.Prototype, out ReagentPrototype? proto);
                var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
                var reagentColor = proto?.SubstanceColor ?? default(Color);
                control.Children.Add(BuildReagentRow(reagentColor, rowCount++, name, reagent.Reagent, reagent.Quantity, false, addReagentButtons, modernMode));
            }
        }
    }

    private Control BuildReagentRow(Color reagentColor, int rowCount, string name, ReagentId reagent, FixedPoint2 quantity, bool isBuffer, bool addReagentButtons, bool modernMode)
    {
        var rowColor1 = Color.FromHex("#1B1B1E");
        var rowColor2 = Color.FromHex("#202025");
        var currentRowColor = (rowCount % 2 == 1) ? rowColor1 : rowColor2;
        var hasColor = reagentColor != default(Color) && addReagentButtons;

        if (modernMode && addReagentButtons)
        {
            // Modern: the entire row is a ReagentButton. Amount is read from the _selectedAmount at click time.
            var rowBtn = new ReagentButton(string.Empty, _selectedAmount, reagent, isBuffer, StyleBase.ButtonSquare)
            {
                HorizontalExpand = true,
            };
            rowBtn.OnPressed += args =>
            {
                rowBtn.Amount = _selectedAmount;
                OnReagentButtonPressed?.Invoke(args, rowBtn);
            };

            // Color chip - small square before the name, blends into row if no color is available.
            var chip = new PanelContainer
            {
                MinSize = new Vector2(6, 30),
                Margin = new Thickness(2, 0, 4, 0),
                VerticalAlignment = VAlignment.Center,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = hasColor ? reagentColor : Color.Transparent,
                }
            };

            var inner = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                Children =
                {
                    chip,
                    new Label { Text = $"{name}: " },
                    new Label
                    {
                        Text = $"{quantity}u",
                        StyleClasses = { StyleNano.StyleClassLabelSecondaryColor }
                    },
                    new Control { HorizontalExpand = true },
                }
            };
            rowBtn.AddChild(inner);
            return rowBtn;
        }

        // Classic: striped PanelContainer with full per-row amount buttons
        if (reagentColor == default || !addReagentButtons)
            reagentColor = currentRowColor;

        var reagentButtonConstructors = CreateReagentTransferButtons(reagent, isBuffer, addReagentButtons);

        var rowContainer = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Children =
            {
                new PanelContainer
                {
                    Name = "colorPanel",
                    VerticalExpand = true,
                    MinWidth = 4,
                    PanelOverride = new StyleBoxFlat { BackgroundColor = reagentColor },
                    Margin = new Thickness(0, 1)
                },
                new Label { Text = $"{name}: " },
                new Label
                {
                    Text = $"{quantity}u",
                    StyleClasses = { StyleNano.StyleClassLabelSecondaryColor }
                },
                new Control { HorizontalExpand = true },
            }
        };

        foreach (var btn in reagentButtonConstructors)
        {
            rowContainer.AddChild(btn);
        }

        return new PanelContainer
        {
            PanelOverride = new StyleBoxFlat(currentRowColor),
            Children = { rowContainer }
        };
    }

    public string LabelLine
    {
        get => LabelLineEdit.Text;
        set
        {
            LabelLineEdit.Text = value;
            LabelLineEditClassic.Text = value;
        }
    }

    private void SetBufferText(FixedPoint2? volume, string text)
    {
        BufferCurrentVolume.Text = $" {volume ?? FixedPoint2.Zero}u";
        DrawSource.Text = Loc.GetString(text);
    }

    private void UpdateReagentPrototypes(string? filter = null)
    {
        if (_lastState == null)
            return;

        BufferInfo.Children.Clear();

        if (!_lastState.BufferReagents.Any())
        {
            BufferInfo.Children.Add(new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") });
            return;
        }

        var reagentList = new List<(ReagentId reagentId, string name, Color color, FixedPoint2 quantity)>();
        foreach (var (reagent, quantity) in _lastState.BufferReagents)
        {
            _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto);
            var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
            var reagentColor = proto?.SubstanceColor ?? default(Color);
            reagentList.Add((reagent, name, reagentColor, quantity));
        }

        if (!string.IsNullOrEmpty(filter))
        {
            var lowerFilter = filter.Trim().ToLowerInvariant();
            reagentList = reagentList
                .Where(r => r.name.ToLowerInvariant().Contains(lowerFilter)
                            || r.reagentId.Prototype.Id.ToLowerInvariant().Contains(lowerFilter))
                .ToList();
        }

        reagentList = _lastState.SortingType switch
        {
            ChemMasterSortingType.Alphabetical => reagentList.OrderBy(x => x.name).ToList(),
            ChemMasterSortingType.Quantity => reagentList.OrderByDescending(x => x.quantity).ToList(),
            ChemMasterSortingType.Latest => Enumerable.Reverse(reagentList).ToList(),
            _ => reagentList
        };

        var rowCount = 0;
        foreach (var reagent in reagentList)
        {
            BufferInfo.Children.Add(BuildReagentRow(reagent.color, rowCount++, reagent.name, reagent.reagentId, reagent.quantity, true, true, modernMode: true));
        }
    }

    public event Action<ChemMasterReagentAmount>? OnAmountSelected;

    public void SetSelectedAmount(ChemMasterReagentAmount amount)
    {
        _selectedAmount = amount;
        SyncGrid(AmountGrid);
    }
}

public sealed class ReagentButton : Button
{
    public ChemMasterReagentAmount Amount { get; set; }
    public bool IsBuffer = true;
    public ReagentId Id { get; set; }
    public ReagentButton(string text, ChemMasterReagentAmount amount, ReagentId id, bool isBuffer, string styleClass)
    {
        AddStyleClass(styleClass);
        Text = text;
        Amount = amount;
        Id = id;
        IsBuffer = isBuffer;
    }
}
