- type: job
  id: StationTrafficController
  name: job-name-stc
  description: job-description-stc
  playTimeTracker: JobStc
  startingGear: StcGear
  alwaysUseSpawner: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # Triad - 10 hours
  canBeAntag: false
  icon: "JobIconStc"
  assignedCompany: Colonial
  supervisors: job-supervisors-overseer # Triad
  weight: 160
  displayWeight: 50 # Second from the top
  setPreference: true
  access:
  - Command
  - Service
  - Maintenance
  - External
  - Frontier
  - StationTrafficController
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddComponentSpecial # Triad
    components:
      - type: ShipSavingBlacklist # Triad - can't save ships
      - type: NpcFactionMember
        factions:
        - TDF # Triad - They aren't apart of the TDF, but they are friendly and work with them
      - type: CryoSleepRadioOverride
        overrides:
        - Service # Colonial Staff radio

- type: startingGear
  id: StcGear
  equipment:
    id: StcPDA
  storage:
    back:
    - Flash
    - RubberStampStc
    - EncryptionKeyStationMasterSR # Triad
    - PhoneInstrumentHigh
