using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NotekeeperUiFragment : BoxContainer
{

    public event Action<string>? OnNoteAdded;
    public event Action<string>? OnNoteRemoved;

    public NotekeeperUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        // Triad: Enter and the button are the same action, and the button greys out until there is something
        // worth submitting, matching how TriTalk's send row behaves.
        Input.OnTextEntered += _ => SubmitNote();
        AddNoteButton.OnPressed += _ => SubmitNote();
        Input.OnTextChanged += args => AddNoteButton.Disabled = string.IsNullOrWhiteSpace(args.Text);

        UpdateState(new List<string>());
    }

    /// <summary>
    ///     Triad: commits whatever is in the input box as a note. Was inlined in the OnTextEntered handler, which
    ///     also meant it stored the raw text: a note of pure whitespace was accepted and became an invisible row.
    /// </summary>
    private void SubmitNote()
    {
        var note = Input.Text.Trim();
        if (string.IsNullOrEmpty(note))
            return;

        AddNote(note);
        OnNoteAdded?.Invoke(note);

        Input.Clear();
        AddNoteButton.Disabled = true;
    }

    public void UpdateState(List<string> notes)
    {
        MessageContainer.RemoveAllChildren();

        foreach (var note in notes)
        {
           AddNote(note);
        }
    }

    private void AddNote(string note)
    {
        var row = new BoxContainer();
        row.HorizontalExpand = true;
        row.Orientation = LayoutOrientation.Horizontal;
        row.Margin = new Thickness(4);

        var label = new Label();
        label.Text = note;
        label.HorizontalExpand = true;
        label.ClipText = true;

        var removeButton = new TextureButton();
        removeButton.AddStyleClass("windowCloseButton");
        removeButton.OnPressed += _ => OnNoteRemoved?.Invoke(label.Text);

        row.AddChild(label);
        row.AddChild(removeButton);

        MessageContainer.AddChild(row);
    }
}
