using System.Linq;
using System.Numerics;
// Triad: aliased rather than a plain `using System.Threading`, which would make `Timer` ambiguous against
// Robust.Shared.Timing.Timer.
using CancellationTokenSource = System.Threading.CancellationTokenSource;
using Content.Client._DV.NanoChat;
using Content.Shared._DV.CartridgeLoader.Cartridges;
using Content.Shared.Access.Components; // Triad: CCVars.MaxNameLength/MaxIdJobLength do not exist here
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Timing;
using Content.Shared.Input;
using Robust.Shared.GameObjects; // Triad: EntitySystem.Get<T>() for the typing-indicator system link

namespace Content.Client._DV.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatUiFragment : BoxContainer
{
    [Dependency] private readonly IGameTiming _timing = default!;

    // Triad: upstream Delta-V reads these from CCVars.MaxNameLength/MaxIdJobLength, which we do not carry.
    // Matches the server-side limits in NanoChatCartridgeSystem.
    private const int MaxNameLength = IdCardConsoleComponent.MaxFullNameLength;
    private const int MaxIdJobLength = IdCardConsoleComponent.MaxJobTitleLength;
    // End Triad

    private readonly NewChatPopup _newChatPopup;
    private readonly EditChatPopup _editChatPopup;
    private uint? _currentChat;
    private uint? _pendingChat;
    private uint _ownNumber;
    private bool _notificationsMuted;
    private bool _listNumber = true;
    private bool _canList; // Triad: false unless this is a legally issued ID
    private Dictionary<uint, NanoChatRecipient> _recipients = [];
    private Dictionary<uint, List<NanoChatMessage>> _messages = [];
    private HashSet<uint> _mutedChats = [];

    // Triad begin: typing indicator
    private readonly NanoChatSystem _nanoChatSystem;
    private uint? _typingSentTo; // the recipient we last told "I am typing", if any
    private TimeSpan _lastTypingSentAt;
    private uint? _typingFrom; // the recipient currently shown as "is typing" in our own thread
    private int _typingGeneration; // invalidates stale auto-clear timers when a fresher pulse arrives
    // Triad end

    /// <summary>
    ///     Triad: cancels work scheduled through Timer.Spawn when this fragment leaves the screen. Those callbacks
    ///     capture the fragment and touch its controls, so without this a PDA closed inside the delay window ends
    ///     up poking disposed controls.
    /// </summary>
    private CancellationTokenSource _deferredCts = new();

    /// <summary>
    ///     Triad: how close to the end still counts as "reading the tail", in pixels, when deciding whether new
    ///     messages should keep scrolling the view down.
    /// </summary>
    private const float ScrollBottomTolerance = 8f;

    /// <summary>
    ///     Triad: which chat the message list currently has bubbles for, so a rebuild can tell "same conversation,
    ///     keep the player's place" from "different conversation, start at the newest message".
    /// </summary>
    private uint? _renderedChat;

    /// <summary>
    ///     The chat the player is looking at: an unconfirmed selection if one is outstanding, otherwise the one
    ///     the server says is current.
    /// </summary>
    /// <remarks>
    ///     Triad: this was spelled out as <c>_pendingChat ?? _currentChat</c> at six call sites, and three others
    ///     (mute, edit, the send-button enable) read <see cref="_currentChat"/> on its own. Those three acted on
    ///     the previously selected chat when used in the window between clicking a contact and the server
    ///     confirming it, so muting or renaming right after a click hit the wrong conversation.
    /// </remarks>
    private uint? ActiveChat => _pendingChat ?? _currentChat;

    public event Action<NanoChatUiMessageType, uint?, string?, string?>? OnMessageSent;

    public NanoChatUiFragment()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _newChatPopup = new(MaxNameLength, MaxIdJobLength);
        _editChatPopup = new(MaxNameLength, MaxIdJobLength);
        SetupEventHandlers();

        // Triad: held here, but we only hand ourselves to it once we are actually on screen. See EnteredTree.
        _nanoChatSystem = EntitySystem.Get<NanoChatSystem>();
    }

    // Triad begin: tie the typing-indicator registration and every escapable resource to time-on-screen rather
    // than to construction. A fragment that is built and never attached must not capture the registration, and one
    // that leaves the screen must not keep a floating popup, a pending timer, or an unsent "still typing" state.
    protected override void EnteredTree()
    {
        base.EnteredTree();

        _nanoChatSystem.RegisterFragment(this);
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        Teardown();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing)
            return;

        Teardown();
    }

    /// <summary>
    ///     Releases everything that can outlive the control: the typing state the server still thinks we are in,
    ///     our typing-push registration, any deferred callback, and the popup windows. The popups are top-level
    ///     controls rather than children of this fragment, so nothing else would ever close them.
    ///     Safe to call more than once, since a detach is normally followed by a dispose.
    /// </summary>
    private void Teardown()
    {
        StopTyping();
        _nanoChatSystem.UnregisterFragment(this);

        // Cancel pending deferred work and arm a fresh token, so a fragment that gets re-attached still works.
        _deferredCts.Cancel();
        _deferredCts.Dispose();
        _deferredCts = new CancellationTokenSource();

        _newChatPopup.Close();
        _editChatPopup.Close();
    }
    // Triad end

    private void SetupEventHandlers()
    {
        _newChatPopup.OnChatCreated += (number, name, job) =>
        {
            OnMessageSent?.Invoke(NanoChatUiMessageType.NewChat, number, name, job);
        };

        _editChatPopup.OnContactEdited += (number, name, job) =>
        {
            OnMessageSent?.Invoke(NanoChatUiMessageType.EditChat, number, name, job);
        };

        NewChatButton.OnPressed += _ =>
        {
            _newChatPopup.ClearInputs();
            _newChatPopup.OpenCentered();
        };

        MuteChatButton.OnPressed += _ =>
        {
            if (ActiveChat is not uint activeChat) // Triad: was _currentChat, see ActiveChat
                return;

            // Remove if muted, otherwise add
            if (!_mutedChats.Remove(activeChat))
                _mutedChats.Add(activeChat);

            UpdateMuteChatButton();
            OnMessageSent?.Invoke(NanoChatUiMessageType.ToggleMuteChat, activeChat, null, null);
        };

        MuteButton.OnPressed += _ =>
        {
            _notificationsMuted = !_notificationsMuted;
            UpdateMuteButton();
            OnMessageSent?.Invoke(NanoChatUiMessageType.ToggleMute, null, null, null);
        };

        MessageInput.OnKeyBindDown += args =>
        {
            if (args.Function == ContentKeyFunctions.NanoChatNavigateUpUnread)
                CycleChannel(CycleDirection.Up, true);
            else if (args.Function == ContentKeyFunctions.NanoChatNavigateDownUnread)
                CycleChannel(CycleDirection.Down, true);
            else if (args.Function == ContentKeyFunctions.NanoChatNavigateUp)
                CycleChannel(CycleDirection.Up, false);
            else if (args.Function == ContentKeyFunctions.NanoChatNavigateDown)
                CycleChannel(CycleDirection.Down, false);
        };
        MessageInput.OnTextChanged += args =>
        {
            // Triad: measure what would actually be sent, so the button state and the character count agree with
            // SendMessage's own limit check instead of counting whitespace SendMessage trims away.
            var length = args.Text.Trim().Length;
            var isValid = length > 0 &&
                          length <= NanoChatMessage.MaxContentLength &&
                          ActiveChat != null;

            SendButton.Disabled = !isValid;

            // Show character count when over limit
            CharacterCount.Visible = length > NanoChatMessage.MaxContentLength;
            if (length > NanoChatMessage.MaxContentLength)
            {
                CharacterCount.Text = Loc.GetString("nano-chat-message-too-long",
                    ("current", length),
                    ("max", NanoChatMessage.MaxContentLength));
                CharacterCount.StyleClasses.Add("LabelDanger");
            }

            // Triad: typing indicator
            if (string.IsNullOrEmpty(args.Text))
                StopTyping();
            else if (ActiveChat is uint activeChat)
                SendTypingPulse(activeChat);
            // End Triad
        };

        LookupButton.OnPressed += _ => ToggleView();
        LookupView.OnStartChat += contact =>
        {
            if (OnMessageSent is { } handler)
            {
                handler(NanoChatUiMessageType.NewChat, contact.Number, contact.Name, contact.JobTitle);
                SelectChat(contact.Number);
                ToggleView();
            }
        };
        ListNumberButton.OnPressed += _ =>
        {
            // Triad: the server refuses this for unregistered cards anyway, this just keeps the button honest.
            if (!_canList)
            {
                UpdateListNumber();
                return;
            }

            _listNumber = !_listNumber;
            UpdateListNumber();
            OnMessageSent?.Invoke(NanoChatUiMessageType.ToggleListNumber, null, null, null);
        };

        MessageInput.OnTextEntered += _ => SendMessage();
        SendButton.OnPressed += _ => SendMessage();
        EditChatButton.OnPressed += _ => BeginEditChat();
        DeleteChatButton.OnPressed += _ => DeleteCurrentChat();
    }

    private void ToggleView()
    {
        ChatView.Visible = !ChatView.Visible;
        LookupView.Visible = !ChatView.Visible;
        LookupButton.Pressed = LookupView.Visible;
    }

    public enum CycleDirection : byte
    {
        Up,
        Down,
    };

    /// <summary>
    ///     Moves the selection one contact along, optionally skipping to the next one with unread messages.
    /// </summary>
    /// <remarks>
    ///     Triad: rewritten as a bounded walk. Upstream looped until the index came back around to its starting
    ///     value, but that starting value was <c>Count</c> when no chat was selected and <c>-1</c> when the
    ///     selected chat was not in the contact list, and a wrapped index can never equal either. So
    ///     "cycle to next unread" with nothing unread never terminated and hung the client outright. Easy to hit:
    ///     a PDA with no conversation selected and the unread keybind pressed.
    /// </remarks>
    private void CycleChannel(CycleDirection direction, bool onlyUnread)
    {
        if (_recipients.Count == 0)
            return;

        var ordered = _recipients.OrderBy(r => r.Value.Name).Select(r => r.Key).ToArray();

        // -1 when nothing is selected, so the first step lands on either end of the list depending on direction.
        var index = ActiveChat is uint activeChat ? Array.IndexOf(ordered, activeChat) : -1;
        var step = direction == CycleDirection.Up ? -1 : 1;

        // At most one full lap: every contact gets considered exactly once, then we stop.
        for (var i = 0; i < ordered.Length; i++)
        {
            index += step;

            if (index < 0)
                index = ordered.Length - 1;
            else if (index >= ordered.Length)
                index = 0;

            if (!onlyUnread || _recipients[ordered[index]].HasUnread)
            {
                SelectChat(ordered[index]);
                return;
            }
        }
    }

    private void SendMessage()
    {
        var activeChat = ActiveChat;
        if (activeChat == null || string.IsNullOrWhiteSpace(MessageInput.Text))
            return;

        // Triad: refuse an over-long message rather than silently truncating it. SendButton is disabled past the
        // limit, but MessageInput.OnTextEntered calls straight in here, so pressing Enter sent a quietly clipped
        // message while the UI was saying it was too long. The server truncates too, as the backstop for input it
        // cannot trust; this is the half that has to agree with what the player is being shown.
        var messageContent = MessageInput.Text.Trim();
        if (messageContent.Length > NanoChatMessage.MaxContentLength)
            return;

        // Add predicted message
        var predictedMessage = new NanoChatMessage(
            _timing.CurTime,
            messageContent,
            _ownNumber
        );

        if (!_messages.TryGetValue(activeChat.Value, out var value))
        {
            value = new List<NanoChatMessage>();
            _messages[activeChat.Value] = value;
        }

        value.Add(predictedMessage);

        // Update UI with predicted message. Triad: sending always jumps to the newest message, even if the player
        // was reading further up when they hit send.
        UpdateMessages(forceScrollToBottom: true);

        // Triad: a sent message ends our own typing state
        StopTyping();

        // Send message event
        OnMessageSent?.Invoke(NanoChatUiMessageType.SendMessage, activeChat, messageContent, null);

        // Clear input
        MessageInput.Text = string.Empty;
        SendButton.Disabled = true;
    }

    private void SelectChat(uint number)
    {
        // Don't reselect the chat we are already on. Triad: compares against ActiveChat, so clicking a chat whose
        // selection is still in flight no longer re-sends the same request.
        if (ActiveChat == number)
            return;

        // Triad: switching threads stops any typing signal we were sending to the old one
        StopTyping();

        _pendingChat = number;

        // Predict marking messages as read
        if (_recipients.TryGetValue(number, out var recipient))
        {
            recipient.HasUnread = false;
            _recipients[number] = recipient;
            UpdateChatList();
        }

        OnMessageSent?.Invoke(NanoChatUiMessageType.SelectChat, number, null, null);
        UpdateCurrentChat();
    }

    private void DeleteCurrentChat()
    {
        var activeChat = ActiveChat;
        if (activeChat == null)
            return;

        StopTyping(); // Triad
        OnMessageSent?.Invoke(NanoChatUiMessageType.DeleteChat, activeChat, null, null);
    }

    private void BeginEditChat()
    {
        // Triad: was keyed on _currentChat (see ActiveChat) and indexed _recipients directly, which threw
        // KeyNotFoundException for a selected chat that is not in the contact list.
        if (ActiveChat is not uint activeChat || !_recipients.TryGetValue(activeChat, out var recipient))
            return;

        _editChatPopup.ClearInputs();
        _editChatPopup.SetNumberInput(recipient.Number.ToString());
        _editChatPopup.SetNameInput(recipient.Name);
        _editChatPopup.SetJobInput(recipient.JobTitle ?? string.Empty);
        _editChatPopup.OpenCentered();
    }

    /// <summary>
    ///     Rebuilds the contact list from <see cref="_recipients"/>.
    /// </summary>
    /// <remarks>
    ///     Triad: took the dictionary as a parameter and assigned it to the field, which is how the fragment ended
    ///     up holding (and predicting onto) the networked state's own collection. The field is now the single
    ///     source and <see cref="UpdateState"/> owns filling it.
    /// </remarks>
    private void UpdateChatList()
    {
        ChatList.RemoveAllChildren();

        NoChatsLabel.Visible = _recipients.Count == 0;
        if (NoChatsLabel.Parent != ChatList)
        {
            NoChatsLabel.Parent?.RemoveChild(NoChatsLabel);
            ChatList.AddChild(NoChatsLabel);
        }

        foreach (var (number, recipient) in _recipients.OrderBy(r => r.Value.Name))
        {
            var entry = new NanoChatEntry(MaxNameLength, MaxIdJobLength);
            // For pending chat selection, always show it as selected even if unconfirmed
            var isSelected = (_pendingChat == number) || (_pendingChat == null && _currentChat == number);
            entry.SetRecipient(recipient, number, isSelected);
            entry.OnPressed += SelectChat;
            ChatList.AddChild(entry);
        }
    }

    private void UpdateCurrentChat()
    {
        var activeChat = ActiveChat;
        var hasActiveChat = activeChat != null;

        // Triad: a stale indicator from the previous thread shouldn't follow us to this one
        if (_typingFrom != activeChat)
        {
            _typingFrom = null;
            _typingGeneration++;
            UpdateTypingIndicator();
        }

        // Update UI state
        MessagesScroll.Visible = hasActiveChat;
        CurrentChatName.Visible = !hasActiveChat;
        MessageInputContainer.Visible = hasActiveChat;
        // Triad: the slot reserves a constant-height row while a conversation is open; only the label inside
        // toggles with actual typing. See the note in the XAML for why the height must not wobble.
        TypingIndicatorSlot.Visible = hasActiveChat;
        DeleteChatButton.Visible = hasActiveChat;
        EditChatButton.Visible = hasActiveChat;
        DeleteChatButton.Disabled = !hasActiveChat;

        // Triad: the placeholder and the header are two different things and upstream conflated them. It wrote the
        // contact's name into CurrentChatName, which is visible only when NO chat is selected, so the name it went
        // to the trouble of formatting could never appear on screen. CurrentChatName is the empty-state message
        // now; ChatHeaderLabel names whoever you are reading.
        CurrentChatName.Text = Loc.GetString("nano-chat-select-chat");

        if (activeChat != null && _recipients.TryGetValue(activeChat.Value, out var recipient))
        {
            ChatHeaderLabel.Text = recipient.Name +
                                   (string.IsNullOrEmpty(recipient.JobTitle) ? "" : $" ({recipient.JobTitle})");
            ChatHeaderLabel.Visible = true;
        }
        else
        {
            ChatHeaderLabel.Visible = false;
        }
    }

    /// <summary>
    ///     Rebuilds the message view from <see cref="_messages"/>. See <see cref="UpdateChatList"/> for why this
    ///     no longer takes the collection as a parameter.
    /// </summary>
    private void UpdateMessages(bool forceScrollToBottom = false)
    {
        // Triad: work out where we are BEFORE tearing the list down, while the old layout is still measurable.
        // Rebuilding resets the scroll, and this method runs on every state -- a mute toggle, a contact rename, a
        // message in some other conversation -- so unconditionally scrolling to the bottom yanked you out of the
        // backlog whenever anything at all happened. Follow the tail only if you were already reading the tail.
        var chatChanged = ActiveChat != _renderedChat;
        var stickToBottom = forceScrollToBottom || chatChanged || IsScrolledToBottom();
        var previousScroll = MessagesScroll.GetScrollValue();

        MessageList.RemoveAllChildren();
        _renderedChat = ActiveChat;

        if (ActiveChat is not uint activeChat || !_messages.TryGetValue(activeChat, out var chatMessages))
            return;

        foreach (var message in chatMessages)
        {
            var messageBubble = new NanoChatMessageBubble();
            messageBubble.SetMessage(message, message.SenderId == _ownNumber);
            MessageList.AddChild(messageBubble); // Spacing comes from MessageList's SeparationOverride.
        }

        MessageList.InvalidateMeasure();
        MessagesScroll.InvalidateMeasure();

        RestoreScroll(previousScroll, stickToBottom);
    }

    /// <summary>
    ///     Triad: whether the message view is scrolled to (or within a few pixels of) the end.
    /// </summary>
    private bool IsScrolledToBottom()
    {
        // The furthest we can scroll is however much taller the content is than the window onto it.
        var maxScroll = MathF.Max(0f, MessageList.Height - MessagesScroll.Height);
        return MessagesScroll.GetScrollValue().Y >= maxScroll - ScrollBottomTolerance;
    }

    /// <summary>
    ///     Triad: re-applies the reading position after the message list is rebuilt, either pinned to the end or
    ///     back where the player had it. Deferred a frame because setting the scroll value right after
    ///     InvalidateMeasure() reads against the OLD (pre-layout) content height -- most visibly wrong when the
    ///     typing indicator label above the input box is also changing visibility at the same moment, which
    ///     shrinks/grows the scroll viewport out from under an immediate scroll call.
    /// </summary>
    private void RestoreScroll(Vector2 previous, bool toBottom)
    {
        Timer.Spawn(TimeSpan.Zero,
            () =>
            {
                if (Disposed)
                    return;

                MessagesScroll.SetScrollValue(toBottom ? new Vector2(previous.X, float.MaxValue) : previous);
            },
            _deferredCts.Token);
    }

    // Triad begin: typing indicator
    // Resent at least this often while the box keeps changing, so the receiver's indicator never goes
    // quiet long enough to expire between pulses. Only costs network traffic while someone is actively typing.
    private static readonly TimeSpan TypingResendInterval = TimeSpan.FromSeconds(0.5);

    /// <summary>
    ///     Tells the server we're composing a message to <paramref name="recipient"/>, throttled so held-down
    ///     typing doesn't spam a network event every keystroke.
    /// </summary>
    private void SendTypingPulse(uint recipient)
    {
        if (_typingSentTo == recipient && _timing.CurTime - _lastTypingSentAt < TypingResendInterval)
            return;

        _typingSentTo = recipient;
        _lastTypingSentAt = _timing.CurTime;
        OnMessageSent?.Invoke(NanoChatUiMessageType.TypingStarted, recipient, null, null);
    }

    /// <summary>
    ///     Tells the server we've stopped composing, if we'd told it we were. Safe to call unconditionally.
    /// </summary>
    private void StopTyping()
    {
        if (_typingSentTo is not uint recipient)
            return;

        _typingSentTo = null;
        OnMessageSent?.Invoke(NanoChatUiMessageType.TypingStopped, recipient, null, null);
    }

    /// <summary>
    ///     Called by <see cref="NanoChat.NanoChatSystem"/> when a contact's typing state changes. Only
    ///     applies to the currently open thread; a self-clearing timer covers a dropped TypingStopped pulse.
    /// </summary>
    public void SetTyping(uint senderNumber, bool typing)
    {
        if (ActiveChat != senderNumber)
            return;

        _typingGeneration++;

        if (!typing)
        {
            _typingFrom = null;
            UpdateTypingIndicator();
            return;
        }

        _typingFrom = senderNumber;
        UpdateTypingIndicator();

        var generation = _typingGeneration;
        // Triad: 2x the sender's resend interval -- tolerates one dropped pulse before clearing, without
        // lingering long enough to look stale once they've actually stopped.
        Timer.Spawn(TimeSpan.FromSeconds(1),
            () =>
            {
                if (Disposed || generation != _typingGeneration)
                    return; // A fresher pulse (or an explicit stop) already landed; don't clobber it.

                _typingFrom = null;
                UpdateTypingIndicator();
            },
            _deferredCts.Token);
    }

    private void UpdateTypingIndicator()
    {
        if (_typingFrom is not uint senderNumber)
        {
            TypingIndicatorLabel.Visible = false;
            return;
        }

        var name = _recipients.TryGetValue(senderNumber, out var recipient) ? recipient.Name : $"#{senderNumber:D4}";
        TypingIndicatorLabel.Text = Loc.GetString("nano-chat-typing-indicator", ("name", name));
        TypingIndicatorLabel.Visible = true;
    }
    // Triad end

    private void UpdateMuteButton()
    {
        if (BellMutedIcon != null)
            BellMutedIcon.Visible = _notificationsMuted;
    }

    private void UpdateMuteChatButton()
    {
        if (BellMutedIconContact != null)
            BellMutedIconContact.Visible = ActiveChat is uint activeChat && _mutedChats.Contains(activeChat); // Triad: was _currentChat
    }

    private void UpdateListNumber()
    {
        if (ListNumberButton == null)
            return;

        ListNumberButton.Pressed = _listNumber && _canList;

        // Triad: an unregistered card can never be listed, so grey the toggle out rather than let it lie.
        ListNumberButton.Disabled = !_canList;
        ListNumberButton.ToolTip = _canList
            ? Loc.GetString("nano-chat-list-number-tooltip", ("status", _listNumber ? "shown" : "hidden"))
            : Loc.GetString("nano-chat-list-number-unregistered");
    }

    public void UpdateState(NanoChatUiState state)
    {
        _ownNumber = state.OwnNumber;
        _notificationsMuted = state.NotificationsMuted;
        _listNumber = state.ListNumber;
        _canList = state.CanList; // Triad

        // Triad: copy out of the state rather than aliasing it. This fragment predicts into these collections
        // (sent messages, read flags, mute toggles) and the engine caches the state object it handed us, replaying
        // it into the next BUI -- so predicting onto it wrote fiction into what the client later treats as truth.
        _mutedChats = new HashSet<uint>(state.MutedChats);
        _recipients = new Dictionary<uint, NanoChatRecipient>(state.Recipients);
        _messages = state.Messages.ToDictionary(chat => chat.Key, chat => new List<NanoChatMessage>(chat.Value));

        OwnNumberLabel.Text = $"#{state.OwnNumber:D4}";
        UpdateMuteButton();
        UpdateListNumber();

        // Update new chat button state based on recipient limit
        var atLimit = state.Recipients.Count >= state.MaxRecipients;
        NewChatButton.Disabled = atLimit;
        NewChatButton.ToolTip = atLimit
            ? Loc.GetString("nano-chat-max-recipients")
            : Loc.GetString("nano-chat-new-chat");

        // Triad: hold a pending selection until the server actually confirms it, or until the chat stops existing.
        // Upstream cleared it on the very next state whatever that state said, so any unrelated update landing in
        // the gap (an incoming message, a mute toggle) snapped the view back to the previously selected chat.
        if (_pendingChat is { } pendingChat && (state.CurrentChat == pendingChat || !_recipients.ContainsKey(pendingChat)))
            _pendingChat = null;

        _currentChat = state.CurrentChat;

        UpdateCurrentChat();
        UpdateMuteChatButton();
        UpdateChatList();
        UpdateMessages();
        LookupView.UpdateContactList(state);
    }
}
