// Triad: the drydock registry.
using System;
using System.Collections.Generic;
using Content.Client._NF.Shipyard.UI;
using Content.Client.Resources;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Content.Shared._Triad.Drydock;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Triad.Drydock.Registry;

/// <summary>
/// The drydock registry on the shuttle records console, drawn to the "Drydock Surfaces" canvas at
/// game scale. The admin panel's list column with nothing to press but search, the chips and the
/// page: what a dock clerk would know about each hull and no more.
///
/// <para>Strings are built with interpolation, never string.Format, for the sandbox reason the
/// admin window records.</para>
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DrydockRegistryWindow : FancyWindow
{
    private static readonly Color Dim = Color.FromHex("#8d8d8d");
    private static readonly Color Underway = Color.FromHex("#d9d941");

    private static StyleBoxFlat CardBox() => new()
    {
        BackgroundColor = Color.FromHex("#2b2b2e"),
        BorderColor = Color.FromHex("#1b1b1e"),
        BorderThickness = new Thickness(2),
    };

    /// <summary>The chips in reading order. Null is "All".</summary>
    private static readonly DrydockRegistryStatus?[] Chips =
    {
        null,
        DrydockRegistryStatus.Stored,
        DrydockRegistryStatus.Underway,
        DrydockRegistryStatus.Impounded,
        DrydockRegistryStatus.Deregistered,
    };

    /// <summary>Asks the server for a page: the search text, the chip, and the page index.</summary>
    public event Action<string?, DrydockRegistryStatus?, int>? OnRequestPage;

    private readonly List<(PanelContainer Panel, Label Text, DrydockRegistryStatus? Chip)> _chips = new();
    private readonly Font _bold;

    private DrydockRegistryStatus? _chip;
    private int _page;
    private int _totalPages = 1;

    public DrydockRegistryWindow()
    {
        RobustXamlLoader.Load(this);

        _bold = IoCManager.Resolve<IResourceCache>().NotoStack("Bold", 12);
        Title = Loc.GetString("drydock-registry-title");

        BuildChips();

        // Enter searches; the canvas draws no button.
        SearchInput.OnTextEntered += _ => RequestPage(0);
        PrevPageButton.OnPressed += _ => RequestPage(Math.Max(0, _page - 1));
        NextPageButton.OnPressed += _ => RequestPage(Math.Min(_totalPages - 1, _page + 1));
    }

    private void BuildChips()
    {
        foreach (var chip in Chips)
        {
            var label = new Label
            {
                Text = Loc.GetString($"drydock-registry-chip-{chip?.ToString() ?? "All"}"),
                Margin = new Thickness(8, 2),
                Align = Label.AlignMode.Center,
                HorizontalExpand = true,
                FontColorOverride = chip == null ? Color.White : DrydockText.ChipText,
            };

            var panel = new PanelContainer { PanelOverride = DrydockText.ChipBox(chip == null), HorizontalExpand = true };
            panel.AddChild(label);

            // Every cell of the grid expands, so the five columns share the width equally.
            var button = new ContainerButton { HorizontalExpand = true };
            button.AddChild(panel);

            var captured = chip;
            button.OnPressed += _ =>
            {
                _chip = captured;
                RequestPage(0);
            };

            _chips.Add((panel, label, chip));
            ChipGrid.AddChild(button);
        }
    }

    public void RequestPage(int page)
    {
        foreach (var (panel, label, chip) in _chips)
            DrydockText.RepaintChip(panel, label, chip == _chip);

        OnRequestPage?.Invoke(string.IsNullOrWhiteSpace(SearchInput.Text) ? null : SearchInput.Text, _chip, page);
    }

    public void ShowPage(DrydockRegistryPageMessage page)
    {
        _page = page.Page;
        _totalPages = Math.Max(1, (page.Total + page.PageSize - 1) / page.PageSize);

        ShipContainer.RemoveAllChildren();
        foreach (var ship in page.Ships)
            ShipContainer.AddChild(Card(ship));

        var empty = page.Total == 0;
        ShipScroll.Visible = !empty;
        EmptyPanel.Visible = empty;
        ShipScroll.SetScrollValue(default);

        CountLabel.Text = Loc.GetString("drydock-admin-count", ("total", page.Total));

        // The page label only when there is a page to name; Prev and Next only past one page.
        PageLabel.Visible = !empty;
        PageLabel.Text = Loc.GetString("drydock-admin-page", ("page", page.Page + 1), ("pages", _totalPages));
        PrevPageButton.Visible = NextPageButton.Visible = _totalPages > 1;
        PrevPageButton.Disabled = page.Page <= 0;
        NextPageButton.Disabled = page.Page + 1 >= _totalPages;
    }

    private Control Card(DrydockRegistryShipInfo ship)
    {
        var lines = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(8, 5),
        };

        // Every line clips rather than widening the card, as the admin panel's do.
        lines.AddChild(new Label { Text = DrydockText.CardTitle(ship.Name), FontOverride = _bold, ClipText = true });
        lines.AddChild(DrydockText.CardLine("drydock-admin-card-class", DrydockText.Class(ship.SizeClass), null));
        lines.AddChild(ship.CaptainName is { } captain
            ? DrydockText.CardLine("drydock-admin-card-owner", captain, null)
            : DrydockText.CardLine("drydock-admin-card-owner", Loc.GetString("drydock-registry-owner-unrecorded"), Dim));

        var (status, colour) = Status(ship);
        lines.AddChild(DrydockText.CardLine("drydock-admin-card-status", status, colour));

        if (ship.Status == DrydockRegistryStatus.Impounded && !string.IsNullOrWhiteSpace(ship.ImpoundReason))
            lines.AddChild(DrydockText.CardLine("drydock-registry-card-reason", ship.ImpoundReason, null));

        var panel = new PanelContainer
        {
            PanelOverride = CardBox(),
            Margin = new Thickness(0, 0, 0, 3),
        };
        panel.AddChild(lines);
        return panel;
    }

    /// <summary>
    /// The status as the card writes it: the status, the berth while stored, then the status's own
    /// figure (a pending transfer, the impound fee). The colour is the status's.
    /// </summary>
    private static (string Text, Color? Colour) Status(DrydockRegistryShipInfo ship)
    {
        var text = Loc.GetString($"drydock-registry-chip-{ship.Status}");

        switch (ship.Status)
        {
            case DrydockRegistryStatus.Stored:
                if (ship.BerthId is { } berth)
                    text = $"{text}, {Loc.GetString("drydock-admin-status-berth", ("berth", berth))}";
                if (!ship.TransferPending)
                    return (text, null);
                return ($"{text}, {Loc.GetString("drydock-registry-status-transfer")}", DrydockText.Warning);
            case DrydockRegistryStatus.Underway:
                return (text, Underway);
            case DrydockRegistryStatus.Impounded:
                return ($"{text}, {BankSystemExtensions.ToSpesoString(ship.ImpoundFee)}", DrydockText.Impound);
            default:
                return (text, Dim);
        }
    }
}
