using System;
using System.Collections.Generic;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared._Triad.Drydock.Admin;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._Triad.Drydock.Admin;

// The drydock admin panel, in the shape of the tamper audit panel beside it: a filtered list on
// the left, the selected hull on the right with its berths, revisions and timeline, and a footer
// that reports the last action. Every button sends a message and the server pushes the whole
// state back, so nothing here guesses at an outcome.
//
// Strings are built with interpolation, never string.Format, for the same sandbox reason the
// tamper window records: the multi-arg string.Format overload fails ILVerify in a Release client.
[GenerateTypedNameReferences]
public sealed partial class DrydockAdminWindow : DefaultWindow
{
    private const int PageSize = 50;

    private static readonly Color StoredColor = Color.FromHex("#6ec06e");
    private static readonly Color OutColor = Color.FromHex("#d9a441");
    private static readonly Color HeldColor = Color.FromHex("#cf4f4f");
    private static readonly Color AdminColor = Color.FromHex("#6fa8dc");
    private static readonly Color LabelColor = Color.FromHex("#8d8d8d");
    private static readonly StyleBoxFlat SelectedBox = new() { BackgroundColor = Color.FromHex("#3e5e82") };

    private static readonly string[] StateOptions = { "All", "Stored", "CheckedOut", "Held" };
    private static readonly string[] SizeClasses = { "Cutter", "Corvette", "Frigate", "Cruiser", "Capital", "SuperCapital" };

    private readonly DrydockAdminEui _eui;
    private DrydockAdminEuiState? _lastState;
    private int _currentPage;

    private readonly List<(PanelContainer Highlight, Guid ShipGuid)> _shipRows = new();
    private readonly List<int> _berthOptions = new();
    private Guid? _selected;

    public DrydockAdminWindow(DrydockAdminEui eui)
    {
        RobustXamlLoader.Load(this);
        _eui = eui;

        for (var i = 0; i < StateOptions.Length; i++)
            StateDropdown.AddItem(StateOptions[i], i);
        StateDropdown.OnItemSelected += args => StateDropdown.SelectId(args.Id);

        for (var i = 0; i < SizeClasses.Length; i++)
            GrantClassDropdown.AddItem(SizeClasses[i], i);
        GrantClassDropdown.OnItemSelected += args => GrantClassDropdown.SelectId(args.Id);

        BerthDropdown.OnItemSelected += args => BerthDropdown.SelectId(args.Id);

        ApplyButton.OnPressed += _ => RequestPage(0);
        PrevPageButton.OnPressed += _ => RequestPage(Math.Max(0, _currentPage - 1));
        NextPageButton.OnPressed += _ => RequestPage(Math.Min(LastPageIndex(), _currentPage + 1));

        SaveNotesButton.OnPressed += _ => WithSelected(id => _eui.Send(new DrydockAdminNotesMessage { ShipGuid = id, Notes = NotesInput.Text }));
        HoldButton.OnPressed += _ => WithSelected(id => _eui.Send(new DrydockAdminHoldMessage
        {
            ShipGuid = id,
            Hold = _lastState?.Selected?.Ship.State != "Held",
            Reason = Reason(),
        }));
        InvestigateButton.OnPressed += _ => WithSelected(id => _eui.Send(new DrydockAdminInvestigateMessage
        {
            ShipGuid = id,
            Investigating = _lastState?.Selected?.Ship.Investigating != true,
            Reason = Reason(),
        }));
        VacateButton.OnPressed += _ => WithSelected(id => _eui.Send(new DrydockAdminMoveMessage { ShipGuid = id, BerthId = null, Reason = Reason() }));
        DeleteShipButton.OnPressed += _ => WithSelected(id => _eui.Send(new DrydockAdminDeleteShipMessage { ShipGuid = id, Reason = Reason() }));
        RestoreButton.OnPressed += _ => WithSelectedBerth((id, berth) => _eui.Send(new DrydockAdminRestoreMessage { ShipGuid = id, BerthId = berth, Reason = Reason() }));
        MoveButton.OnPressed += _ => WithSelectedBerth((id, berth) => _eui.Send(new DrydockAdminMoveMessage { ShipGuid = id, BerthId = berth, Reason = Reason() }));
        GrantBerthButton.OnPressed += _ =>
        {
            if (_lastState?.Selected is not { } detail)
                return;

            _eui.Send(new DrydockAdminGrantBerthMessage
            {
                OwnerUserId = detail.Ship.OwnerUserId,
                MaxSizeClass = SizeClasses[Math.Clamp(GrantClassDropdown.SelectedId, 0, SizeClasses.Length - 1)],
            });
        };
    }

    public void UpdateState(DrydockAdminEuiState state)
    {
        _lastState = state;
        _currentPage = state.Page;
        _selected = state.Selected?.Ship.ShipGuid;

        RebuildShipList(state);
        RebuildDetail(state);

        NoticeLabel.Text = state.Notice ?? (state.Selected == null ? "Select a ship." : string.Empty);
    }

    private string? Reason() => string.IsNullOrWhiteSpace(ReasonInput.Text) ? null : ReasonInput.Text;

    private void WithSelected(Action<Guid> act)
    {
        if (_selected is { } id)
            act(id);
    }

    private void WithSelectedBerth(Action<Guid, int> act)
    {
        if (_selected is not { } id)
            return;

        var index = BerthDropdown.SelectedId;
        if (index < 0 || index >= _berthOptions.Count)
            return;

        act(id, _berthOptions[index]);
    }

    // ---------------------------------------------------------------- Ship list

    private void RebuildShipList(DrydockAdminEuiState state)
    {
        var scroll = ShipScroll.GetScrollValue();
        ShipContainer.RemoveAllChildren();
        _shipRows.Clear();

        foreach (var ship in state.Ships)
        {
            var msg = new FormattedMessage();
            msg.PushColor(StateColor(ship.State));
            msg.AddText(ship.Name);
            msg.Pop();
            Field(msg, "owner", ship.OwnerName ?? Short(ship.OwnerUserId));
            Field(msg, "state", ship.State);
            if (ship.SizeClass != null)
                Field(msg, "class", ship.SizeClass);
            if (ship.BerthId is { } berth)
                Field(msg, "berth", $"#{berth}");
            if (ship.CheckedOutRoundId is { } round)
                Field(msg, "out since round", round.ToString());
            if (ship.LiveThisRound)
                Field(msg, "live", "yes");
            if (ship.Investigating)
                Field(msg, "investigating", "yes");

            var rich = new RichTextLabel { HorizontalExpand = true, Margin = new Thickness(6, 3) };
            rich.SetMessage(msg);

            var highlight = new PanelContainer();
            highlight.StyleClasses.Add("PanelBackgroundBaseLight");
            highlight.AddChild(rich);
            if (ship.ShipGuid == _selected)
                highlight.PanelOverride = SelectedBox;

            var button = new ContainerButton { HorizontalExpand = true };
            button.AddChild(highlight);
            var captured = ship.ShipGuid;
            button.OnPressed += _ => _eui.Send(new DrydockAdminSelectShipMessage { ShipGuid = captured });

            _shipRows.Add((highlight, ship.ShipGuid));
            ShipContainer.AddChild(button);
            ShipContainer.AddChild(new HSeparator());
        }

        CountLabel.Text = $"Showing {state.Ships.Count} on this page · {state.TotalShips} match the filter";

        var totalPages = Math.Max(1, (state.TotalShips + PageSize - 1) / PageSize);
        PageLabel.Text = $"Page {state.Page + 1} / {totalPages}";
        PrevPageButton.Disabled = state.Page <= 0;
        NextPageButton.Disabled = state.Page + 1 >= totalPages;

        ShipScroll.SetScrollValue(scroll);
    }

    private int LastPageIndex()
        => _lastState == null ? 0 : Math.Max(0, (_lastState.TotalShips - 1) / PageSize);

    private void RequestPage(int page)
    {
        var stateIndex = Math.Clamp(StateDropdown.SelectedId, 0, StateOptions.Length - 1);
        _eui.Send(new DrydockAdminRequestPageMessage
        {
            Page = page,
            PageSize = PageSize,
            Owner = string.IsNullOrWhiteSpace(OwnerInput.Text) ? null : OwnerInput.Text,
            ShipNameContains = string.IsNullOrWhiteSpace(ShipNameInput.Text) ? null : ShipNameInput.Text,
            State = stateIndex == 0 ? null : StateOptions[stateIndex],
            StrandedOnly = StrandedOnly.Pressed,
        });
    }

    // ---------------------------------------------------------------- Detail

    private void RebuildDetail(DrydockAdminEuiState state)
    {
        BerthContainer.RemoveAllChildren();
        RevisionContainer.RemoveAllChildren();
        TimelineContainer.RemoveAllChildren();
        BerthDropdown.Clear();
        _berthOptions.Clear();

        var detail = state.Selected;
        var hasSelection = detail != null;

        HoldButton.Disabled = !hasSelection;
        InvestigateButton.Disabled = !hasSelection;
        DeleteShipButton.Disabled = !hasSelection;
        GrantBerthButton.Disabled = !hasSelection;
        SaveNotesButton.Disabled = !hasSelection;

        if (detail == null)
        {
            HeaderLabel.SetMessage(FormattedMessage.FromUnformatted("No ship selected."));
            NotesInput.Text = string.Empty;
            VacateButton.Disabled = true;
            RestoreButton.Disabled = true;
            MoveButton.Disabled = true;
            return;
        }

        var ship = detail.Ship;
        var header = new FormattedMessage();
        header.PushColor(StateColor(ship.State));
        header.AddText(ship.Name);
        header.Pop();
        Field(header, "id", ship.ShipGuid.ToString());
        Field(header, "owner", $"{ship.OwnerName ?? "(unknown)"} ({ship.OwnerUserId})");
        Field(header, "state", ship.State);
        Field(header, "class", ship.SizeClass ?? "?");
        Field(header, "vessel", ship.VesselProto ?? "?");
        Field(header, "berth", ship.BerthId is { } b ? $"#{b}" : "none");
        Field(header, "revision", ship.CurrentRevision.ToString());
        Field(header, "since", $"{ship.StateChangedAt:yyyy-MM-dd HH:mm}");
        if (ship.CheckedOutRoundId is { } r)
            Field(header, "out since round", r.ToString());
        Field(header, "live this round", ship.LiveThisRound ? "YES" : "no");
        if (ship.Investigating)
            Field(header, "investigating", "YES");
        HeaderLabel.SetMessage(header);

        NotesInput.Text = detail.AdminNotes ?? string.Empty;
        HoldButton.Text = ship.State == "Held" ? "Release Hold" : "Hold";
        InvestigateButton.Text = ship.Investigating ? "Close Investigation" : "Open Investigation";
        VacateButton.Disabled = ship.BerthId == null;

        // Berths the owner has, as restore and move targets. An occupied berth is listed but named
        // as occupied so the refusal that follows is not a surprise.
        foreach (var berth in state.OwnerBerths)
        {
            var occupant = berth.OccupantName != null ? $" (holds {berth.OccupantName})" : " (empty)";
            BerthDropdown.AddItem($"#{berth.BerthId} {berth.MaxSizeClass}{occupant}", _berthOptions.Count);
            _berthOptions.Add(berth.BerthId);
        }

        var hasBerths = _berthOptions.Count > 0;
        RestoreButton.Disabled = !hasBerths || ship.State == "Stored" || ship.LiveThisRound;
        MoveButton.Disabled = !hasBerths || ship.State != "Stored";
        if (hasBerths)
            BerthDropdown.SelectId(0);

        foreach (var berth in state.OwnerBerths)
        {
            var msg = new FormattedMessage();
            msg.AddText($"#{berth.BerthId} {berth.MaxSizeClass}");
            Field(msg, "kind", berth.Kind);
            Field(msg, "paid", berth.PricePaid.ToString());
            Field(msg, "holds", berth.OccupantName ?? "nothing");

            var rich = new RichTextLabel { HorizontalExpand = true, Margin = new Thickness(6, 2) };
            rich.SetMessage(msg);

            var delete = new Button { Text = "Delete", Disabled = berth.OccupantShipGuid != null };
            var captured = berth.BerthId;
            delete.OnPressed += _ => _eui.Send(new DrydockAdminDeleteBerthMessage { BerthId = captured });

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(rich);
            row.AddChild(delete);
            BerthContainer.AddChild(row);
        }

        foreach (var revision in detail.Revisions)
        {
            var msg = new FormattedMessage();
            msg.PushColor(revision.Revision == ship.CurrentRevision ? StoredColor : LabelColor);
            msg.AddText($"r{revision.Revision}");
            msg.Pop();
            Field(msg, "kind", revision.Kind);
            Field(msg, "at", $"{revision.CreatedAt:yyyy-MM-dd HH:mm}");
            if (revision.RoundId is { } round)
                Field(msg, "round", round.ToString());
            Field(msg, "by", revision.ActorName ?? (revision.ActorUserId is { } a ? Short(a) : "system"));
            Field(msg, "size", $"{revision.SizeBytes / 1024} KB");
            if (revision.DerivedFromRevision is { } from)
                Field(msg, "from", $"r{from}");
            Field(msg, "document", revision.HasBlob ? "kept" : "pruned");

            var rich = new RichTextLabel { HorizontalExpand = true, Margin = new Thickness(6, 2) };
            rich.SetMessage(msg);

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(rich);

            if (revision.HasBlob && revision.Revision != ship.CurrentRevision)
            {
                var promote = new Button { Text = "Promote" };
                var captured = revision.Revision;
                promote.OnPressed += _ => WithSelected(id => _eui.Send(new DrydockAdminPromoteRevisionMessage
                {
                    ShipGuid = id,
                    Revision = captured,
                    Reason = Reason(),
                }));
                row.AddChild(promote);
            }

            RevisionContainer.AddChild(row);
        }

        foreach (var entry in detail.Timeline)
        {
            var msg = new FormattedMessage();
            msg.PushColor(LabelColor);
            msg.AddText($"{entry.At:yyyy-MM-dd HH:mm:ss} ");
            msg.Pop();
            msg.PushColor(ActionColor(entry.Action));
            msg.AddText(entry.Action);
            msg.Pop();
            Field(msg, "by", entry.ActorName ?? (entry.ActorUserId is { } a ? Short(a) : "system"));
            if (entry.SubjectUserId is { } s)
                Field(msg, "to", entry.SubjectName ?? Short(s));
            if (entry.Revision is { } rev)
                Field(msg, "revision", rev.ToString());
            if (entry.BerthId is { } berth)
                Field(msg, "berth", $"#{berth}");
            if (entry.RoundId is { } round)
                Field(msg, "round", round.ToString());
            if (!string.IsNullOrEmpty(entry.Reason))
                Field(msg, "reason", $"\"{entry.Reason}\"");

            var rich = new RichTextLabel { HorizontalExpand = true, Margin = new Thickness(6, 2) };
            rich.SetMessage(msg);
            TimelineContainer.AddChild(rich);
            TimelineContainer.AddChild(new HSeparator());
        }
    }

    private static void Field(FormattedMessage msg, string label, string value)
    {
        msg.PushColor(LabelColor);
        msg.AddText($", {label}=");
        msg.Pop();
        msg.AddText(value);
    }

    private static string Short(Guid id) => id.ToString("N")[..8];

    private static Color StateColor(string state) => state switch
    {
        "Stored" => StoredColor,
        "CheckedOut" => OutColor,
        "Held" => HeldColor,
        _ => Color.Gray,
    };

    private static Color ActionColor(string action) => action switch
    {
        "Store" or "Retrieve" => StoredColor,
        "Fallback" => OutColor,
        "Hold" or "Release" or "Restore" or "Delete" or "InvestigationOpened" or "InvestigationClosed" or "BerthMove" or "BerthGrant" or "BerthDelete" => AdminColor,
        _ => Color.Gray,
    };
}
