// Triad: the drydock admin panel.
using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client._NF.Shipyard.UI;
using Content.Client.Resources;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Content.Shared._NF.Shipyard.BUI;
using Content.Shared._Triad.Drydock;
using Content.Shared._Triad.Drydock.Admin;
using Content.Shared._Triad.ShipSize;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Triad.Drydock.Admin;

/// <summary>
/// The drydock admin panel, drawn to the "Drydock Surfaces" canvas at game scale. The left column
/// finds a hull; the right side is the selected hull's verbs, its owner's berths (the same row the
/// player's console uses) and its whole life on the timeline. Nothing is said twice: a fact on a
/// card is not repeated in a header, and a fact on the timeline is not repeated in a card.
///
/// <para>The verb row is one fixed set, rebuilt on every state: a verb the state refuses is greyed
/// with its reason as the tooltip, so an admin can see everything the panel can do. Every button
/// sends a message and the server pushes the whole state back; the server checks each choice again
/// on receipt, so a row that went stale between the state and the click is a refusal rather than a
/// wrong result.</para>
///
/// <para>Strings are built with interpolation, never string.Format, for the same sandbox reason
/// the tamper window records: the multi-arg string.Format overload fails ILVerify in a Release
/// client.</para>
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DrydockAdminWindow : FancyWindow
{
    private const int PageSize = 50;

    private static readonly Color Dim = Color.FromHex("#8d8d8d");
    private static readonly Color Out = Color.FromHex("#d9d941");
    private static readonly Color Sold = Color.FromHex("#ff8080");
    private static readonly Color Destroyed = Color.FromHex("#8b3a3a");
    private static readonly Color Abandoned = Color.FromHex("#a08c72");

    /// <summary>The faint caution stripes on a berth whose ship is in escrow: a white tile, tinted.</summary>
    private const string StripesTexture = "/Textures/_Triad/Interface/drydock_caution_stripes.png";
    private static readonly Color StripesTint = DrydockText.Warning.WithAlpha(0.22f);

    private static StyleBoxFlat RowBox(bool selected) => new()
    {
        BackgroundColor = Color.FromHex("#2b2b2e"),
        BorderColor = selected ? Color.FromHex("#5b86b8") : Color.FromHex("#1b1b1e"),
        BorderThickness = new Thickness(2),
    };

    private static StyleBoxFlat TimelineRule() => new()
    {
        BackgroundColor = Color.Transparent,
        BorderColor = Color.FromHex("#26262a"),
        BorderThickness = new Thickness(0, 0, 0, 1),
    };

    /// <summary>
    /// A greyed button as the canvas draws it: clear, a thin border and dim text. Nano's own
    /// disabled look tints the box to the panel's colour and draws no border, so on this panel a
    /// disabled button reads as bare text. The margins and padding are the square button's, so a
    /// button keeps its size as it greys.
    /// </summary>
    private static readonly StyleBoxFlat DisabledButtonBox = CreateDisabledButtonBox();
    private static readonly Color DisabledButtonText = Color.FromHex("#6a6a6a");

    private static StyleBoxFlat CreateDisabledButtonBox()
    {
        var box = new StyleBoxFlat
        {
            BackgroundColor = Color.Transparent,
            BorderColor = Color.FromHex("#3a3a3e"),
            BorderThickness = new Thickness(1),
        };
        box.SetContentMarginOverride(StyleBox.Margin.Vertical, 2);
        box.SetContentMarginOverride(StyleBox.Margin.Horizontal, 8);
        box.SetPadding(StyleBox.Margin.Left, 1);
        box.SetPadding(StyleBox.Margin.Right, 2);
        return box;
    }

    /// <summary>
    /// The chips in the grid's reading order, a row per meaning: every hull and the two a player
    /// is using, the two held states and the one that needs a decision, then the three that are
    /// over. Null is "All"; "Stranded" is derived by the server from a round that is over rather
    /// than read off a row; every other name is a <c>DrydockShipState</c> spelled exactly as
    /// <c>ToString</c> gives it, which is also how the <c>drydock-admin-chip-</c> key is built.
    /// </summary>
    private static readonly string?[] Chips =
    {
        null, "Stored", "CheckedOut",
        "InEscrow", "Impounded", "Stranded",
        "Sold", "Abandoned", "Destroyed",
    };

    private readonly DrydockAdminEui _eui;
    private readonly List<(PanelContainer Panel, Label Text, string? Chip)> _chips = new();

    /// <summary>
    /// The canvas draws three sizes besides body text: section headings, timestamps, and a hull's
    /// callsign and name in bold. Sizes are points, so 12 is the 16px body the canvas draws.
    /// </summary>
    private readonly Font _heading;
    private readonly Font _small;
    private readonly Font _bold;

    private readonly StyleBoxTexture _stripes;

    private DrydockAdminEuiState? _lastState;
    private string? _chip;
    private Guid? _selected;

    public DrydockAdminWindow(DrydockAdminEui eui)
    {
        RobustXamlLoader.Load(this);
        _eui = eui;

        var fonts = IoCManager.Resolve<IResourceCache>();
        _heading = fonts.NotoStack("Bold", 13);
        _small = fonts.NotoStack(size: 11);
        _bold = fonts.NotoStack("Bold", 12);
        _stripes = new StyleBoxTexture
        {
            Texture = fonts.GetTexture(StripesTexture),
            Mode = StyleBoxTexture.StretchMode.Tile,
            Modulate = StripesTint,
        };

        BerthsTitle.FontOverride = _heading;
        NotesTitle.FontOverride = _heading;
        TimelineTitle.FontOverride = _heading;

        Title = Loc.GetString("drydock-admin-title");
        GrantBerthButton.Text = Loc.GetString("drydock-admin-grant-berth") + DrydockText.Caret;

        BuildChips();

        // Enter searches; the canvas draws no button.
        SearchInput.OnTextEntered += _ => RequestPage(0);
        PrevPageButton.OnPressed += _ => RequestPage(Math.Max(0, (_lastState?.Page ?? 0) - 1));
        NextPageButton.OnPressed += _ => RequestPage(Math.Min(LastPageIndex(), (_lastState?.Page ?? 0) + 1));

        // The canvas gives notes no Save button, so they commit on leaving the box; Enter is a
        // newline there, the box being a few lines tall. TextEdit is sealed and raises no
        // focus-exit event, so FrameUpdate below watches for the loss of focus, and a close with
        // the cursor still in the box commits on the way out.
        NotesInput.Placeholder = new Rope.Leaf(Loc.GetString("drydock-admin-notes-placeholder"));
        OnClose += SaveNotes;
    }

    private bool _notesFocused;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var focused = NotesInput.HasKeyboardFocus();
        if (_notesFocused && !focused)
            SaveNotes();
        _notesFocused = focused;
    }

    public void UpdateState(DrydockAdminEuiState state)
    {
        _lastState = state;
        _selected = state.Selected?.Ship.ShipGuid;

        RebuildShipList(state);
        RebuildDetail(state);

        NoticeLabel.Text = state.Notice ?? string.Empty;
        NoticeLabel.Visible = !string.IsNullOrWhiteSpace(state.Notice);
    }

    // ---------------------------------------------------------------- Search and chips

    private void BuildChips()
    {
        foreach (var chip in Chips)
        {
            var label = new Label
            {
                Text = Loc.GetString($"drydock-admin-chip-{chip ?? "All"}"),
                Margin = new Thickness(8, 2),
                Align = Label.AlignMode.Center,
                HorizontalExpand = true,
                FontColorOverride = chip == null ? Color.White : DrydockText.ChipText,
            };

            var panel = new PanelContainer { PanelOverride = DrydockText.ChipBox(chip == null), HorizontalExpand = true };
            panel.AddChild(label);

            // Every cell of the grid expands, so the three columns share the width equally.
            var button = new ContainerButton { HorizontalExpand = true };
            button.AddChild(panel);

            // Stranded is the one chip whose meaning is not its own name.
            if (chip == "Stranded")
                button.ToolTip = Loc.GetString("drydock-admin-chip-Stranded-tooltip");

            var captured = chip;
            button.OnPressed += _ =>
            {
                _chip = captured;
                RequestPage(0);
            };

            _chips.Add((panel, label, chip));
            ChipGrid.AddChild(button);
        }
    }

    private void RequestPage(int page)
    {
        foreach (var (panel, label, chip) in _chips)
            DrydockText.RepaintChip(panel, label, chip == _chip);

        _eui.Send(new DrydockAdminRequestPageMessage
        {
            Page = page,
            PageSize = PageSize,
            Search = string.IsNullOrWhiteSpace(SearchInput.Text) ? null : SearchInput.Text,
            Chip = _chip,
        });
    }

    private int LastPageIndex()
        => _lastState == null ? 0 : Math.Max(0, (_lastState.TotalShips - 1) / PageSize);

    private string? Reason() => string.IsNullOrWhiteSpace(ReasonInput.Text) ? null : ReasonInput.Text;

    private void SaveNotes()
    {
        if (_selected is not { } id || _lastState?.Selected is not { } detail)
            return;

        // Only when it actually changed: focus leaves this box on every click elsewhere.
        var notes = Rope.Collapse(NotesInput.TextRope);
        if ((detail.AdminNotes ?? string.Empty) == notes)
            return;

        _eui.Send(new DrydockAdminNotesMessage { ShipGuid = id, Notes = notes });
    }

    // ---------------------------------------------------------------- The hulls that matched

    private void RebuildShipList(DrydockAdminEuiState state)
    {
        var scroll = ShipScroll.GetScrollValue();
        ShipContainer.RemoveAllChildren();

        foreach (var ship in state.Ships)
        {
            var (status, colour) = Status(ship);

            var lines = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(8, 5),
            };
            // Every line clips rather than widening the card: a clipped Label measures to nothing,
            // so a long name cannot push the card past the column.
            lines.AddChild(new Label { Text = DrydockText.CardTitle(ship.Name), FontOverride = _bold, ClipText = true });
            lines.AddChild(DrydockText.CardLine("drydock-admin-card-class", DrydockText.Class(ship.SizeClass), null));
            lines.AddChild(DrydockText.CardLine("drydock-admin-card-owner", ship.OwnerName ?? Short(ship.OwnerUserId), null));
            lines.AddChild(DrydockText.CardLine("drydock-admin-card-status", status, colour));

            var panel = new PanelContainer
            {
                PanelOverride = RowBox(ship.ShipGuid == _selected),
                Margin = new Thickness(0, 0, 0, 3),
            };
            panel.AddChild(lines);

            var button = new ContainerButton { HorizontalExpand = true };
            button.AddChild(panel);

            var captured = ship.ShipGuid;
            button.OnPressed += _ => _eui.Send(new DrydockAdminSelectShipMessage { ShipGuid = captured });

            ShipContainer.AddChild(button);
        }

        CountLabel.Text = Loc.GetString("drydock-admin-count", ("total", state.TotalShips));

        var totalPages = Math.Max(1, (state.TotalShips + PageSize - 1) / PageSize);
        PageLabel.Text = Loc.GetString("drydock-admin-page", ("page", state.Page + 1), ("pages", totalPages));

        // Prev and Next exist only when there is somewhere to go; one page is just its label.
        PrevPageButton.Visible = NextPageButton.Visible = totalPages > 1;
        SetEnabled(PrevPageButton, state.Page > 0);
        SetEnabled(NextPageButton, state.Page + 1 < totalPages);

        ShipScroll.SetScrollValue(scroll);
    }

    /// <summary>
    /// A hull's status as the card writes it: the state, the berth when it holds one, then the
    /// state's own figure (the round it went out in, when an offer runs out, the fee and whether it
    /// is locked, the sale price). The colour is the state's.
    /// </summary>
    private static (string Text, Color? Colour) Status(DrydockAdminShipDto ship)
    {
        // Keying off the state's name means a state nobody wrote an arm for renders a missing key
        // rather than passing for one it is not, which is the direction an unhandled state should
        // fail in on an adjudication panel.
        var parts = new List<string> { Loc.GetString($"drydock-admin-chip-{ship.State}") };
        if (ship.BerthId is { } berth)
            parts.Add(Loc.GetString("drydock-admin-status-berth", ("berth", berth)));

        Color? colour = null;
        switch (ship.State)
        {
            case "CheckedOut":
                if (ship.CheckedOutRoundId is { } round)
                    parts.Add(Loc.GetString("drydock-admin-status-round", ("round", round)));
                colour = Out;
                break;
            case "InEscrow":
                parts.Add(ExpiresIn(ship.EscrowExpiresAt));
                colour = DrydockText.Warning;
                break;
            case "Impounded":
                parts.Add(BankSystemExtensions.ToSpesoString(ship.ImpoundFee));
                if (!ship.ImpoundRedeemable)
                    parts.Add(Loc.GetString("drydock-admin-status-locked"));
                colour = DrydockText.Impound;
                break;
            case "Sold":
                // A sale with no price on record keeps the bare word.
                if (ship.LastSalePrice is { } price)
                    parts.Add(BankSystemExtensions.ToSpesoString(price));
                colour = Sold;
                break;
            case "Destroyed":
                colour = Destroyed;
                break;
            case "Abandoned":
                colour = Abandoned;
                break;
        }

        return (string.Join(", ", parts), colour);
    }

    private static string ExpiresIn(DateTime? expires)
    {
        if (expires is not { } at || at <= DateTime.UtcNow)
            return Loc.GetString("drydock-admin-status-expired");

        return Loc.GetString("drydock-admin-status-expires", ("minutes", (int)Math.Ceiling((at - DateTime.UtcNow).TotalMinutes)));
    }

    // ---------------------------------------------------------------- The selected hull

    private void RebuildDetail(DrydockAdminEuiState state)
    {
        VerbRow.RemoveAllChildren();
        BerthContainer.RemoveAllChildren();
        TimelineContainer.RemoveAllChildren();

        var detail = state.Selected;
        EmptyPanel.Visible = detail == null;
        DetailPanel.Visible = detail != null;
        EscrowPanel.Visible = detail?.Escrow != null;
        NotesInput.Editable = detail != null;

        if (detail == null)
        {
            NotesInput.TextRope = new Rope.Leaf(string.Empty);
            GrantBerthButton.SetItems(Array.Empty<DrydockMenuButton.Item>());
            return;
        }

        var ship = detail.Ship;

        BuildEscrowCard(detail);
        BuildVerbs(state, detail);

        // Every verb pushes a fresh state; a push that lands while the admin is typing a note must
        // not overwrite what they have typed, so the box is only reset when it is not theirs.
        if (!NotesInput.HasKeyboardFocus())
            NotesInput.TextRope = new Rope.Leaf(detail.AdminNotes ?? string.Empty);

        BuildGrantMenu(ship.OwnerUserId);
        BuildBerths(state, ship);
        BuildTimeline(detail);
    }

    /// <summary>The one fact about a standing offer the card and timeline do not carry: where the ship would land.</summary>
    private void BuildEscrowCard(DrydockAdminShipDetailDto detail)
    {
        if (detail.Escrow is not { } escrow)
            return;

        EscrowLandsLabel.Text = escrow.LandsInBerthId is { } lands
            ? Loc.GetString("drydock-admin-escrow-lands-berth", ("berth", lands))
            : Loc.GetString("drydock-admin-escrow-lands-none");
    }

    /// <summary>
    /// Every verb, every time, in one fixed order, so an admin learns the row once and can see the
    /// whole set of things the panel can do (user, 2026-09-12). A verb the state refuses is greyed
    /// rather than absent and its tooltip says why: the engine's hover path never reads
    /// <c>Disabled</c>, so a greyed button still shows one. The server checks each choice again on
    /// receipt regardless.
    /// </summary>
    private void BuildVerbs(DrydockAdminEuiState state, DrydockAdminShipDetailDto detail)
    {
        var ship = detail.Ship;

        // Impound takes a hull that is somewhere: berthed or in the world. On a terminal row the
        // state IS the verdict and the verb would overwrite it (on a sale it would also take
        // restore-from-sale with it, since that button reads State); in escrow the server refuses
        // until the offer is withdrawn; in the lot it has already happened.
        var impoundWhy = ship.State switch
        {
            "Impounded" => "drydock-admin-impound-why-impounded",
            "InEscrow" => "drydock-admin-impound-why-escrow",
            "Sold" or "Destroyed" or "Abandoned" => "drydock-admin-impound-why-terminal",
            _ => null,
        };
        var impound = Verb("drydock-admin-impound", "drydock-admin-impound-tooltip", "ButtonCaution", impoundWhy);
        impound.OnPressed += _ => OpenImpoundDialog(detail);
        VerbRow.AddChild(impound);

        // Release is one press out of the lot into the hull's last berth; Restore to… below is the
        // same exit with the berth chosen.
        var release = Verb("drydock-admin-release", "drydock-admin-release-tooltip", StyleNano.ButtonPrimary,
            ship.State == "Impounded" ? null : "drydock-admin-release-why");
        release.OnPressed += _ => _eui.Send(new DrydockAdminReleaseImpoundMessage { ShipGuid = ship.ShipGuid, Reason = Reason() });
        VerbRow.AddChild(release);

        // Restore puts a hull that is out, impounded, destroyed or abandoned back into a berth; a
        // stored one is home, an escrow one is spoken for, and a sold one comes back only through
        // the sale reversal, which decides about the money before anything else.
        var restoreWhy = ship.State switch
        {
            "Stored" => "drydock-admin-restore-to-why-stored",
            "InEscrow" => "drydock-admin-restore-to-why-escrow",
            "Sold" => "drydock-admin-restore-to-why-sold",
            _ => null,
        };
        var restoreTo = new DrydockMenuButton
        {
            Text = Loc.GetString("drydock-admin-restore-to") + DrydockText.Caret,
            StyleClasses = { "ButtonSquare" },
            MinWidth = 130,
            Margin = new Thickness(0, 0, 4, 0),
        };
        restoreTo.SetItems(restoreWhy == null
            ? BerthTargets(state, ship, berthId => _eui.Send(new DrydockAdminRestoreMessage
            {
                ShipGuid = ship.ShipGuid,
                BerthId = berthId,
                Reason = Reason(),
            }))
            : Array.Empty<DrydockMenuButton.Item>());
        // SetItems greys a menu with nothing to list, which is also an owner with no berths at all.
        if (restoreWhy == null && restoreTo.Disabled)
            restoreWhy = "drydock-admin-restore-to-why-no-berths";
        restoreTo.ToolTip = Loc.GetString(restoreWhy ?? "drydock-admin-restore-to-tooltip");
        SetEnabled(restoreTo, restoreWhy == null);
        VerbRow.AddChild(restoreTo);

        var sale = ship.State == "Sold" ? detail.LastSale : null;
        var restoreSale = Verb("drydock-admin-restore-from-sale", "drydock-admin-restore-from-sale-tooltip", StyleNano.ButtonPrimary,
            sale != null ? null
            : ship.State == "Sold" ? "drydock-admin-restore-from-sale-why-no-record"
            : "drydock-admin-restore-from-sale-why");
        if (sale != null)
            restoreSale.OnPressed += _ => OpenRestoreSaleDialog(state, ship, sale);
        VerbRow.AddChild(restoreSale);

        var escrow = detail.Escrow;
        var cancel = Verb("drydock-admin-cancel-offer", "drydock-admin-cancel-offer-tooltip", "ButtonCaution",
            escrow != null ? null : "drydock-admin-cancel-offer-why");
        if (escrow != null)
            cancel.OnPressed += _ => _eui.Send(new DrydockAdminCancelOfferMessage { TransferId = escrow.TransferId, Reason = Reason() });
        VerbRow.AddChild(cancel);

        var more = new DrydockMenuButton
        {
            Text = Loc.GetString("drydock-admin-more"),
            StyleClasses = { "ButtonSquare" },
            MinWidth = 34,
            AlignRight = true,
        };
        more.SetItems(OverflowItems(detail));
        SetEnabled(more, !more.Disabled);
        VerbRow.AddChild(more);
    }

    /// <summary>
    /// The rare verbs. Promoting a revision lives here rather than in a panel of its own: the
    /// question an admin asks is what happened to the hull, and that is the timeline.
    /// </summary>
    private List<DrydockMenuButton.Item> OverflowItems(DrydockAdminShipDetailDto detail)
    {
        var ship = detail.Ship;

        // Vacating is the repair for a hull that is out and still shown in its slot. A stored ship
        // lives in its berth and is moved, never vacated; an escrow ship keeps its berth for the
        // offer to hand over. The entry says which, and the server refuses both regardless.
        var items = new List<DrydockMenuButton.Item>
        {
            new(Loc.GetString("drydock-admin-vacate"),
                VacateReason(ship),
                ship.BerthId != null && ship.State is not ("Stored" or "InEscrow"),
                () => _eui.Send(new DrydockAdminMoveMessage { ShipGuid = ship.ShipGuid, BerthId = null, Reason = Reason() })),
        };

        foreach (var revision in detail.Revisions)
        {
            if (!revision.HasBlob || revision.Revision == ship.CurrentRevision)
                continue;

            var captured = revision.Revision;
            items.Add(new DrydockMenuButton.Item(
                Loc.GetString("drydock-admin-promote", ("revision", captured)),
                revision.AppraisedValue is { } value
                    ? Loc.GetString("drydock-admin-revision-appraisal", ("value", value))
                    : $"{revision.CreatedAt:MM-dd HH:mm}",
                true,
                () => _eui.Send(new DrydockAdminPromoteRevisionMessage
                {
                    ShipGuid = ship.ShipGuid,
                    Revision = captured,
                    Reason = Reason(),
                })));
        }

        items.Add(new DrydockMenuButton.Item(
            Loc.GetString("drydock-admin-delete-ship"),
            ship.LiveThisRound ? Loc.GetString("drydock-admin-live") : null,
            !ship.LiveThisRound,
            () => _eui.Send(new DrydockAdminDeleteShipMessage { ShipGuid = ship.ShipGuid, Reason = Reason() })));

        return items;
    }

    /// <summary>Why Vacate is greyed, for the two states that hold a berth on purpose; null when it is offered.</summary>
    private static string? VacateReason(DrydockAdminShipDto ship)
    {
        if (ship.BerthId == null)
            return null;

        return ship.State switch
        {
            "Stored" => Loc.GetString("drydock-admin-vacate-stored"),
            "InEscrow" => Loc.GetString("drydock-admin-vacate-escrow"),
            _ => null,
        };
    }

    /// <summary>A verb button; greyed when <paramref name="why"/> names a reason, which then replaces its tooltip.</summary>
    private static Button Verb(string label, string tooltip, string? extraClass, string? why)
    {
        var button = new Button
        {
            Text = Loc.GetString(label),
            Margin = new Thickness(0, 0, 4, 0),
            ToolTip = Loc.GetString(why ?? tooltip),
        };
        button.StyleClasses.Add("ButtonSquare");
        if (extraClass != null)
            button.StyleClasses.Add(extraClass);

        SetEnabled(button, why == null);
        return button;
    }

    /// <summary>
    /// Enables a button, or greys it the way the canvas draws a greyed button. The style sheet's
    /// disabled tint is overridden to white so it cannot darken the drawn box into the panel, and
    /// the caution and primary fills go with it, so every greyed verb reads the same.
    /// </summary>
    private static void SetEnabled(Button button, bool enabled)
    {
        button.Disabled = !enabled;
        button.StyleBoxOverride = enabled ? null : DisabledButtonBox;
        button.ModulateSelfOverride = enabled ? null : Color.White;
        button.Label.FontColorOverride = enabled ? null : DisabledButtonText;
    }

    /// <summary>
    /// The owner's berths as targets for one action. An unusable berth stays listed and names why,
    /// because "there is nowhere to put it" is the answer the admin came for.
    /// </summary>
    private static List<DrydockMenuButton.Item> BerthTargets(DrydockAdminEuiState state, DrydockAdminShipDto ship, Action<int> pick)
    {
        var items = new List<DrydockMenuButton.Item>();

        foreach (var berth in state.OwnerBerths)
        {
            var occupied = berth.OccupantShipGuid != null && berth.OccupantShipGuid != ship.ShipGuid;
            var fits = ShipSizeRules.Fits(ship.SizeClass, berth.MaxSizeClass);
            var id = berth.BerthId;

            items.Add(new DrydockMenuButton.Item(
                $"#{berth.BerthId} {berth.MaxSizeClass}",
                BerthReason(!occupied, fits),
                !occupied && fits,
                () => pick(id)));
        }

        return items;
    }

    private void BuildGrantMenu(Guid owner)
    {
        var items = Enum.GetValues<ShipSizeClass>()
            .Select(cls => new DrydockMenuButton.Item(cls.ToString(), null, true,
                () => _eui.Send(new DrydockAdminGrantBerthMessage { OwnerUserId = owner, MaxSizeClass = cls.ToString() })))
            .ToList();

        GrantBerthButton.SetItems(items);
    }

    /// <summary>
    /// The owner's berths, drawn by the same row the player's console uses. The occupant is written
    /// the way the card writes a hull, callsign first; an empty berth that the unberthed selected
    /// hull last sat in says so, since that is where Release puts it; and a berth whose ship is in
    /// escrow carries the caution stripes instead of a badge.
    /// </summary>
    private void BuildBerths(DrydockAdminEuiState state, DrydockAdminShipDto ship)
    {
        var free = state.OwnerBerths.Count(b => b.OccupantShipGuid == null);
        BerthsTitle.Text = Loc.GetString("drydock-admin-berths-title", ("owner", ship.OwnerName ?? Short(ship.OwnerUserId)));
        BerthsCount.Text = Loc.GetString("drydock-admin-berths-count", ("free", free), ("total", state.OwnerBerths.Count));

        foreach (var berth in state.OwnerBerths)
        {
            // The player's row also draws escrow and a sale price; an admin berth carries neither,
            // so those arrive null and the row simply does not draw them.
            var info = new DrydockBerthInfo(
                berth.BerthId,
                berth.MaxSizeClass,
                sellValue: 0,
                upgradePrice: null,
                upgradeClass: null,
                occupantShipId: berth.OccupantShipGuid,
                occupantName: berth.OccupantName,
                occupantSizeClass: berth.OccupantSizeClass,
                occupantState: berth.OccupantState,
                occupantSellPrice: null,
                occupantTransferId: null,
                occupantOfferedTo: null,
                occupantOfferSecondsLeft: null);

            var row = new DrydockBerthRow(info, canRetrieve: false) { Margin = new Thickness(0, 0, 0, 3) };
            row.OccupantLabel.SetMessage(Occupant(berth, ship));

            if (berth.OccupantState == "InEscrow")
            {
                // The row is a panel, so a child fills its inside; put first, it draws under the text.
                // A styled panel rather than a TextureRect, whose Tile mode the engine never
                // implemented: it draws the tile once in the corner.
                var stripes = new PanelContainer { PanelOverride = _stripes };
                row.AddChild(stripes);
                stripes.SetPositionFirst();
            }

            var empty = berth.OccupantShipGuid == null;
            var fits = ShipSizeRules.Fits(ship.SizeClass, berth.MaxSizeClass);
            var id = berth.BerthId;

            row.MenuButton.SetItems(new List<DrydockMenuButton.Item>
            {
                new(Loc.GetString("drydock-admin-berth-restore-here"),
                    BerthReason(empty, fits),
                    empty && fits && ship.State is not ("Stored" or "InEscrow" or "Sold"),
                    () => _eui.Send(new DrydockAdminRestoreMessage { ShipGuid = ship.ShipGuid, BerthId = id, Reason = Reason() })),
                new(Loc.GetString("drydock-admin-berth-move-here"),
                    BerthReason(empty, fits),
                    empty && fits && ship.State == "Stored",
                    () => _eui.Send(new DrydockAdminMoveMessage { ShipGuid = ship.ShipGuid, BerthId = id, Reason = Reason() })),
                new(Loc.GetString("drydock-admin-berth-delete"),
                    empty ? null : Loc.GetString("drydock-admin-berth-occupied"),
                    empty,
                    () => _eui.Send(new DrydockAdminDeleteBerthMessage { BerthId = id })),
            });

            BerthContainer.AddChild(row);
        }
    }

    /// <summary>What a berth row says about what is in it.</summary>
    private static FormattedMessage Occupant(DrydockAdminBerthDto berth, DrydockAdminShipDto selected)
    {
        var msg = new FormattedMessage();

        if (berth.OccupantName != null)
        {
            msg.AddText(DrydockText.CardTitle(berth.OccupantName));
            return msg;
        }

        var isLastBerth = selected.BerthId == null && selected.LastBerthId == berth.BerthId;
        msg.PushColor(Dim);
        msg.AddText(isLastBerth
            ? Loc.GetString("drydock-admin-berth-last", ("ship", DrydockNameRules.SplitShuttleName(selected.Name).Name))
            : Loc.GetString("shipyard-console-berth-empty"));
        msg.Pop();
        return msg;
    }

    private static string? BerthReason(bool empty, bool fits)
    {
        if (!empty)
            return Loc.GetString("drydock-admin-berth-occupied");

        return fits ? null : Loc.GetString("drydock-admin-berth-too-small");
    }

    /// <summary>
    /// The hull's whole life: a fixed timestamp column, then what happened, actor before subject.
    /// Today's rows carry the time, the first of them marked as today; older rows carry the date.
    /// A refused-access row is the only one a console never produces, so it is coloured and says
    /// so on hover.
    /// </summary>
    private void BuildTimeline(DrydockAdminShipDetailDto detail)
    {
        var today = DateTime.UtcNow.Date;
        var markedToday = false;

        foreach (var entry in detail.Timeline)
        {
            var refused = entry.Action == "AccessRefused";

            string stamp;
            if (entry.At.Date != today)
                stamp = $"{entry.At:yyyy-MM-dd HH:mm}";
            else if (markedToday)
                stamp = $"{entry.At:HH:mm}";
            else
            {
                stamp = Loc.GetString("drydock-admin-timeline-today", ("time", $"{entry.At:HH:mm}"));
                markedToday = true;
            }

            var when = new Label
            {
                Text = stamp,
                FontOverride = _small,
                FontColorOverride = Dim,
                MinWidth = 120,
                Margin = new Thickness(0, 0, 10, 0),
                VerticalAlignment = VAlignment.Top,
            };

            var msg = new FormattedMessage();
            msg.PushColor(refused ? Sold : Color.White);
            msg.AddBold(Loc.GetString($"drydock-admin-action-{entry.Action}"));
            msg.Pop();

            msg.AddText($" {entry.ActorName ?? (entry.ActorUserId is { } a ? Short(a) : "system")}");
            if (entry.SubjectUserId is { } subject && entry.SubjectUserId != entry.ActorUserId)
                msg.AddText($" → {entry.SubjectName ?? Short(subject)}");

            msg.PushColor(DrydockText.Dim);
            if (entry.BerthId is { } berth)
                msg.AddText($" · #{berth}");
            if (entry.Revision is { } rev)
                msg.AddText($" · r{rev}");
            if (entry.RoundId is { } round)
                msg.AddText($" · round {round}");
            if (!string.IsNullOrEmpty(entry.Reason))
                msg.AddText($" · {entry.Reason}");
            msg.Pop();

            var what = new RichTextLabel { HorizontalExpand = true };
            what.SetMessage(msg);

            var line = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 4),
            };
            line.AddChild(when);
            line.AddChild(what);

            var rule = new PanelContainer { PanelOverride = TimelineRule(), HorizontalExpand = true };
            rule.AddChild(line);
            if (refused)
                rule.ToolTip = Loc.GetString("drydock-admin-refused-tooltip");

            TimelineContainer.AddChild(rule);
        }
    }

    /// <summary>
    /// The fee is quoted against the current revision's appraisal, which is the figure the server
    /// charges against for a berthed hull; the dialog says when the hull is live and will be
    /// appraised again. The dialog's own reason is what the owner reads, and the panel's inline
    /// reason box stands in when it is left empty.
    /// </summary>
    private void OpenImpoundDialog(DrydockAdminShipDetailDto detail)
    {
        var ship = detail.Ship;
        var appraisal = detail.Revisions.FirstOrDefault(r => r.Revision == ship.CurrentRevision)?.AppraisedValue;

        var dialog = new DrydockImpoundDialog(ship, appraisal, _lastState?.ImpoundDefaultPercent ?? 50, (percent, redeemable, reason) =>
            _eui.Send(new DrydockAdminImpoundMessage
            {
                ShipGuid = ship.ShipGuid,
                FeePercent = percent,
                Redeemable = redeemable,
                Reason = reason ?? Reason(),
            }));

        dialog.OpenCentered();
    }

    private void OpenRestoreSaleDialog(DrydockAdminEuiState state, DrydockAdminShipDto ship, DrydockAdminSaleDto sale)
    {
        var targets = state.OwnerBerths
            .Where(b => b.OccupantShipGuid == null && ShipSizeRules.Fits(ship.SizeClass, b.MaxSizeClass))
            .Select(b => b.BerthId)
            .ToList();

        var dialog = new DrydockRestoreSaleDialog(ship, sale, targets, ship.LastBerthId, (berthId, takeMoney, reason) =>
            _eui.Send(new DrydockAdminRestoreFromSaleMessage
            {
                ShipGuid = ship.ShipGuid,
                BerthId = berthId,
                TakeMoneyBack = takeMoney,
                Reason = reason,
            }));

        dialog.OpenCentered();
    }

    // ---------------------------------------------------------------- Shared reads

    private static string Short(Guid id) => id.ToString("N")[..8];
}
