// Triad: the drydock admin panel.
using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client._NF.Shipyard.UI;
using Content.Client.Resources;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Content.Shared._NF.Shipyard.BUI;
using Content.Shared._Triad.Drydock.Admin;
using Content.Shared._Triad.ShipSize;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Triad.Drydock.Admin;

/// <summary>
/// The drydock admin panel, drawn to the "Drydock Surfaces" canvas. A hull's whole life is the
/// timeline; the berths beside it are the same rows the player sees on their console, so both
/// sides of a dispute are looking at the same picture.
///
/// <para>The verb row is one fixed set, rebuilt on every state: a verb the state refuses is greyed
/// with its reason as the tooltip, so an admin can see everything the panel can do. Every button
/// sends a message and the server pushes the whole state back; the server checks each choice again
/// on receipt, so a row that went stale between the state and the click is a refusal rather than a
/// wrong result.</para>
///
/// <para>Strings are built with interpolation, never string.Format, for the same sandbox reason
/// the tamper window records: the multi-arg string.Format overload fails ILVerify in a Release
/// client.</para>
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DrydockAdminWindow : FancyWindow
{
    private const int PageSize = 50;

    private static readonly Color Dim = Color.FromHex("#8d8d8d");
    private const string KeyHex = "#999999";
    private static readonly Color Key = Color.FromHex(KeyHex);
    private static readonly Color Empty = Color.FromHex("#777777");
    private static readonly Color Escrow = Color.FromHex("#d9a441");
    private static readonly Color Out = Color.FromHex("#d9d941");
    private static readonly Color Sold = Color.FromHex("#ff8080");
    private static readonly Color Impounded = Color.FromHex("#cf4f4f");
    private static readonly Color Destroyed = Color.FromHex("#8b3a3a");
    private static readonly Color Abandoned = Color.FromHex("#a08c72");
    private static readonly Color Plain = Color.FromHex("#cfcfcf");

    private static StyleBoxFlat RowBox(bool selected) => new()
    {
        BackgroundColor = Color.FromHex("#2b2b2e"),
        BorderColor = selected ? Color.FromHex("#5b86b8") : Color.FromHex("#1b1b1e"),
        BorderThickness = new Thickness(2),
    };

    private static StyleBoxFlat ChipBox(bool on) => new()
    {
        BackgroundColor = on ? Color.FromHex("#2f4c6f") : Color.FromHex("#222226"),
        BorderColor = on ? Color.FromHex("#5b86b8") : Color.FromHex("#3a3a3e"),
        BorderThickness = new Thickness(1),
    };

    private static StyleBoxFlat PillBox(Color border) => new()
    {
        BackgroundColor = Color.Transparent,
        BorderColor = border,
        BorderThickness = new Thickness(1),
    };

    private static StyleBoxFlat TimelineRule() => new()
    {
        BackgroundColor = Color.Transparent,
        BorderColor = Color.FromHex("#26262a"),
        BorderThickness = new Thickness(0, 0, 0, 1),
    };

    /// <summary>
    /// The chips in the order the canvas draws them. Null is "All" and "Stranded" is derived by the
    /// server from a round that is over rather than read off a row; every other name is a
    /// <c>DrydockShipState</c> spelled exactly as <c>ToString</c> gives it, which is also how the
    /// <c>drydock-admin-chip-</c> key is built.
    /// </summary>
    private static readonly string?[] Chips =
    {
        null, "Stored", "CheckedOut", "InEscrow", "Impounded", "Sold", "Abandoned", "Destroyed", "Stranded",
    };

    private readonly DrydockAdminEui _eui;
    private readonly List<(PanelContainer Panel, Label Text, string? Chip)> _chips = new();

    /// <summary>
    /// The canvas draws four sizes and nothing else: the hull's name, the section headings, body,
    /// and the small print on state tags, timestamps, counts and hints. Body is the stylesheet's
    /// default and needs no font of its own; these three are the rest, plus body in bold for a
    /// hull's name on a list row, and every label this window builds or names is set to one of
    /// them, so nothing inherits a size from a style class that happens to be nearby.
    /// </summary>
    private readonly Font _title;
    private readonly Font _heading;
    private readonly Font _small;
    private readonly Font _bold;

    private DrydockAdminEuiState? _lastState;
    private string? _chip;
    private Guid? _selected;

    public DrydockAdminWindow(DrydockAdminEui eui)
    {
        RobustXamlLoader.Load(this);
        _eui = eui;

        var fonts = IoCManager.Resolve<IResourceCache>();
        _title = fonts.GetFont("/Fonts/NotoSans/NotoSans-Bold.ttf", 15);
        _heading = fonts.GetFont("/Fonts/NotoSans/NotoSans-Bold.ttf", 13);
        _small = fonts.GetFont("/Fonts/NotoSans/NotoSans-Regular.ttf", 11);
        _bold = fonts.GetFont("/Fonts/NotoSans/NotoSans-Bold.ttf", 12);

        BerthsTitle.FontOverride = _heading;
        NotesTitle.FontOverride = _heading;
        TimelineTitle.FontOverride = _heading;
        BerthsHint.FontOverride = _small;
        TimelineHint.FontOverride = _small;
        CountLabel.FontOverride = _small;
        PageLabel.FontOverride = _small;
        NoticeLabel.FontOverride = _small;
        ImpoundFeeLabel.FontOverride = _title;
        ImpoundFeeNote.FontOverride = _small;

        Title = Loc.GetString("drydock-admin-title");

        BuildChips();

        // Enter searches; the canvas draws no button.
        SearchInput.OnTextEntered += _ => RequestPage(0);
        PrevPageButton.OnPressed += _ => RequestPage(Math.Max(0, (_lastState?.Page ?? 0) - 1));
        NextPageButton.OnPressed += _ => RequestPage(Math.Min(LastPageIndex(), (_lastState?.Page ?? 0) + 1));

        // The canvas gives notes no Save button, so they commit on leaving the box; Enter is a
        // newline there, the box being a few lines tall. TextEdit is sealed and raises no
        // focus-exit event, so FrameUpdate below watches for the loss of focus, and a close with
        // the cursor still in the box commits on the way out.
        NotesInput.Placeholder = new Rope.Leaf(Loc.GetString("drydock-admin-notes-placeholder"));
        OnClose += SaveNotes;
    }

    private bool _notesFocused;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var focused = NotesInput.HasKeyboardFocus();
        if (_notesFocused && !focused)
            SaveNotes();
        _notesFocused = focused;
    }

    public void UpdateState(DrydockAdminEuiState state)
    {
        _lastState = state;
        _selected = state.Selected?.Ship.ShipGuid;

        RebuildShipList(state);
        RebuildDetail(state);

        NoticeLabel.Text = state.Notice ?? string.Empty;
        NoticeLabel.Visible = !string.IsNullOrWhiteSpace(state.Notice);
    }

    // ---------------------------------------------------------------- Search and chips

    private void BuildChips()
    {
        foreach (var chip in Chips)
        {
            var label = new Label
            {
                Text = Loc.GetString($"drydock-admin-chip-{chip ?? "All"}"),
                Margin = new Thickness(8, 2),
                Modulate = chip == null ? Color.White : Color.FromHex("#b0b0b0"),
            };

            var panel = new PanelContainer { PanelOverride = ChipBox(chip == null) };
            panel.AddChild(label);

            var button = new ContainerButton { Margin = new Thickness(0, 0, 3, 0) };
            button.AddChild(panel);

            // Stranded is the one chip whose meaning is not its own name.
            if (chip == "Stranded")
                button.ToolTip = Loc.GetString("drydock-admin-chip-Stranded-tooltip");

            var captured = chip;
            button.OnPressed += _ =>
            {
                _chip = captured;
                RequestPage(0);
            };

            _chips.Add((panel, label, chip));
            ChipRow.AddChild(button);
        }
    }

    private void RequestPage(int page)
    {
        foreach (var (panel, label, chip) in _chips)
        {
            var on = chip == _chip;
            panel.PanelOverride = ChipBox(on);
            label.Modulate = on ? Color.White : Color.FromHex("#b0b0b0");
        }

        _eui.Send(new DrydockAdminRequestPageMessage
        {
            Page = page,
            PageSize = PageSize,
            Search = string.IsNullOrWhiteSpace(SearchInput.Text) ? null : SearchInput.Text,
            Chip = _chip,
        });
    }

    private int LastPageIndex()
        => _lastState == null ? 0 : Math.Max(0, (_lastState.TotalShips - 1) / PageSize);

    private string? Reason() => string.IsNullOrWhiteSpace(ReasonInput.Text) ? null : ReasonInput.Text;

    private void SaveNotes()
    {
        if (_selected is not { } id || _lastState?.Selected is not { } detail)
            return;

        // Only when it actually changed: focus leaves this box on every click elsewhere.
        var notes = Rope.Collapse(NotesInput.TextRope);
        if ((detail.AdminNotes ?? string.Empty) == notes)
            return;

        _eui.Send(new DrydockAdminNotesMessage { ShipGuid = id, Notes = notes });
    }

    // ---------------------------------------------------------------- The hulls that matched

    private void RebuildShipList(DrydockAdminEuiState state)
    {
        var scroll = ShipScroll.GetScrollValue();
        ShipContainer.RemoveAllChildren();

        foreach (var ship in state.Ships)
        {
            // The name keeps its full width and the class and owner behind it clip. A horizontal
            // box never shrinks a child below what it measured, and a clipped Label is the one text
            // control that measures to nothing, so this is what keeps the state tag and the berth
            // column inside the row on a long name.
            var name = new Label { Text = ship.Name, FontOverride = _bold, VerticalAlignment = VAlignment.Center };
            var key = new Label
            {
                Text = $" · {ship.SizeClass ?? "?"} · {ship.OwnerName ?? Short(ship.OwnerUserId)}",
                Modulate = Key,
                ClipText = true,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            };

            var line = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(8, 0),
            };
            line.AddChild(name);
            line.AddChild(key);
            line.AddChild(StatePill(ship));

            // The berth sits in its own right-hand column so the numbers line up down the list.
            line.AddChild(new Label
            {
                Text = ship.BerthId is { } berth ? $"#{berth}" : string.Empty,
                FontOverride = _small,
                Modulate = Dim,
                MinWidth = 60,
                Align = Label.AlignMode.Right,
                Margin = new Thickness(8, 0, 0, 0),
            });

            var panel = new PanelContainer
            {
                PanelOverride = RowBox(ship.ShipGuid == _selected),
                MinHeight = 40,
                Margin = new Thickness(0, 0, 0, 3),
            };
            panel.AddChild(line);

            var button = new ContainerButton { HorizontalExpand = true };
            button.AddChild(panel);

            var captured = ship.ShipGuid;
            button.OnPressed += _ => _eui.Send(new DrydockAdminSelectShipMessage { ShipGuid = captured });

            ShipContainer.AddChild(button);
        }

        CountLabel.Text = Loc.GetString("drydock-admin-count", ("total", state.TotalShips));

        var totalPages = Math.Max(1, (state.TotalShips + PageSize - 1) / PageSize);
        PageLabel.Text = Loc.GetString("drydock-admin-page", ("page", state.Page + 1), ("pages", totalPages));
        PrevPageButton.Disabled = state.Page <= 0;
        NextPageButton.Disabled = state.Page + 1 >= totalPages;

        ShipScroll.SetScrollValue(scroll);
    }

    /// <summary>The state tag, carrying its own number: the round it went out in, the time an offer has left.</summary>
    private Control StatePill(DrydockAdminShipDto ship)
    {
        var (text, colour) = ship.State switch
        {
            "CheckedOut" => (Loc.GetString("drydock-admin-row-out", ("round", ship.CheckedOutRoundId ?? 0)), Out),
            "InEscrow" => (Loc.GetString("drydock-admin-row-escrow", ("left", TimeLeft(ship.EscrowExpiresAt))), Escrow),
            // The price on the row, as the canvas draws it; a sale with no price on record keeps the bare word.
            "Sold" => (ship.LastSalePrice is { } price
                ? Loc.GetString("drydock-admin-row-sold", ("price", BankSystemExtensions.ToSpesoString(price)))
                : Loc.GetString("drydock-admin-chip-Sold"), Sold),
            // The fee on the row, as the canvas draws it, and a locked one says so: the two are the
            // same state at the same number of credits and read very differently to an admin.
            "Impounded" => (Loc.GetString(ship.ImpoundRedeemable ? "drydock-admin-row-impounded" : "drydock-admin-row-impounded-locked",
                ("fee", BankSystemExtensions.ToSpesoString(ship.ImpoundFee))), Impounded),
            "Destroyed" => (Loc.GetString("drydock-admin-chip-Destroyed"), Destroyed),
            "Abandoned" => (Loc.GetString("drydock-admin-chip-Abandoned"), Abandoned),
            // Stored lands here, and so does a state nobody wrote an arm for: keying off the name
            // means the next one renders a missing key rather than claiming to be berthed, which is
            // the direction an unhandled state should fail in on an adjudication panel.
            _ => (Loc.GetString($"drydock-admin-chip-{ship.State}"), Plain),
        };

        return Pill(text, colour);
    }

    private Control Pill(string text, Color colour)
    {
        var panel = new PanelContainer { PanelOverride = PillBox(colour), VerticalAlignment = VAlignment.Center };
        panel.AddChild(new Label { Text = text, FontOverride = _small, Modulate = colour, Margin = new Thickness(6, 1) });
        return panel;
    }

    private static string TimeLeft(DateTime? expires)
    {
        if (expires is not { } at)
            return Loc.GetString("drydock-admin-expired");

        var left = at - DateTime.UtcNow;
        return left <= TimeSpan.Zero
            ? Loc.GetString("drydock-admin-expired")
            : Loc.GetString("drydock-admin-minutes-left", ("minutes", (int)Math.Ceiling(left.TotalMinutes)));
    }

    // ---------------------------------------------------------------- The selected hull

    private void RebuildDetail(DrydockAdminEuiState state)
    {
        HeaderRow.RemoveAllChildren();
        VerbRow.RemoveAllChildren();
        BerthContainer.RemoveAllChildren();
        TimelineContainer.RemoveAllChildren();

        var detail = state.Selected;
        EscrowPanel.Visible = detail?.Escrow != null;
        ImpoundPanel.Visible = detail?.Impound != null;
        // The reason box belongs to a selected hull's verbs; with nothing selected the canvas draws
        // no header at all.
        ReasonInput.Visible = detail != null;
        GrantBerthButton.Disabled = detail == null;
        NotesInput.Editable = detail != null;

        if (detail == null)
        {
            HeaderRow.AddChild(new Label { Text = Loc.GetString("drydock-admin-no-selection"), Modulate = Dim });
            BerthsTitle.Text = Loc.GetString("drydock-admin-berths-title-empty");
            BerthsCount.Text = string.Empty;
            NotesInput.TextRope = new Rope.Leaf(string.Empty);
            GrantBerthButton.SetItems(Array.Empty<DrydockMenuButton.Item>());
            return;
        }

        var ship = detail.Ship;

        BuildHeader(ship);
        BuildEscrowCard(detail);
        BuildImpoundCard(detail);
        BuildVerbs(state, detail);

        // Every verb pushes a fresh state; a push that lands while the admin is typing a note must
        // not overwrite what they have typed, so the box is only reset when it is not theirs.
        if (!NotesInput.HasKeyboardFocus())
            NotesInput.TextRope = new Rope.Leaf(detail.AdminNotes ?? string.Empty);

        BuildGrantMenu(ship.OwnerUserId);
        BuildBerths(state, ship);
        BuildTimeline(detail);
    }

    private void BuildHeader(DrydockAdminShipDto ship)
    {
        HeaderRow.AddChild(new Label
        {
            Text = ship.Name,
            FontOverride = _title,
            VerticalAlignment = VAlignment.Center,
        });

        var detail = new RichTextLabel { VerticalAlignment = VAlignment.Center, Margin = new Thickness(10, 0, 0, 0) };
        var msg = new FormattedMessage();
        msg.PushColor(Key);
        msg.AddText(Loc.GetString("drydock-admin-header",
            ("class", ship.SizeClass ?? "?"),
            ("id", Short(ship.ShipGuid)),
            ("revision", ship.CurrentRevision),
            ("owner", ship.OwnerName ?? "?"),
            ("account", Short(ship.OwnerUserId))));
        msg.Pop();
        detail.SetMessage(msg);
        HeaderRow.AddChild(detail);

        HeaderRow.AddChild(new Control { HorizontalExpand = true });

        // The one fact that refuses a restore, so it sits in the header rather than in a menu.
        if (ship.LiveThisRound)
            HeaderRow.AddChild(Pill(Loc.GetString("drydock-admin-header-live"), Out));

        HeaderRow.AddChild(StatePill(ship));
    }

    private void BuildEscrowCard(DrydockAdminShipDetailDto detail)
    {
        if (detail.Escrow is not { } escrow)
            return;

        var body = new FormattedMessage();
        body.AddText(Loc.GetString("drydock-admin-escrow-body",
            ("to", escrow.ToName ?? Short(escrow.ToUserId)),
            ("toAccount", Short(escrow.ToUserId)),
            ("made", $"{escrow.CreatedAt:HH:mm}")));
        body.PushColor(Key);
        body.AddText(" ");
        body.AddText(escrow.LandsInBerthId is { } lands
            ? Loc.GetString("drydock-admin-escrow-lands", ("berth", lands))
            : Loc.GetString("drydock-admin-escrow-no-room"));
        body.Pop();
        EscrowBodyLabel.SetMessage(body);

        var second = new FormattedMessage();
        second.PushColor(Key);
        second.AddText(Loc.GetString("drydock-admin-escrow-expiry",
            ("expires", $"{escrow.ExpiresAt:HH:mm}"),
            ("left", TimeLeft(escrow.ExpiresAt))));
        second.Pop();
        EscrowLandsLabel.SetMessage(second);
    }

    /// <summary>
    /// The impound card, to the AdminImpounded artboard: who took the hull and when, the share and
    /// appraisal the fee was cut from, whether the owner may act on it, and where Release would seat
    /// it, with the frozen fee large beside it. An admin's own words go on the first line; the sweep
    /// has none worth repeating, since its reason is the sentence the line already says.
    /// </summary>
    private void BuildImpoundCard(DrydockAdminShipDetailDto detail)
    {
        if (detail.Impound is not { } impound)
            return;

        var by = impound.TakenByName ?? (impound.TakenByUserId is { } id ? Short(id) : Loc.GetString("drydock-admin-impound-card-sweep"));
        var at = $"{impound.TakenAt:HH:mm}";
        var taken = impound.RoundId is { } round
            ? Loc.GetString("drydock-admin-impound-card-taken", ("by", FormattedMessage.EscapeText(by)), ("at", at), ("round", round))
            : Loc.GetString("drydock-admin-impound-card-taken-no-round", ("by", FormattedMessage.EscapeText(by)), ("at", at));
        if (impound.TakenByUserId != null && !string.IsNullOrWhiteSpace(impound.Reason))
            taken += " " + Loc.GetString("drydock-admin-impound-card-reason", ("reason", FormattedMessage.EscapeText(impound.Reason)));

        var basis = impound.Appraisal is { } appraisal && appraisal > 0
            ? Loc.GetString("drydock-admin-impound-card-basis",
                ("percent", (int)Math.Round(impound.Fee * 100.0 / appraisal)),
                ("appraisal", BankSystemExtensions.ToSpesoString(appraisal)))
            : Loc.GetString("drydock-admin-impound-card-basis-unknown");

        var owner = Loc.GetString(impound.Redeemable ? "drydock-admin-impound-card-redeemable" : "drydock-admin-impound-card-locked");
        var seat = impound switch
        {
            { LastBerthFree: true, LastBerthId: { } last } => Loc.GetString("drydock-admin-impound-card-seat-last", ("berth", last), ("class", impound.LastBerthClass ?? "?")),
            { FallbackBerthId: { } other } => Loc.GetString("drydock-admin-impound-card-seat-other", ("berth", other), ("class", impound.FallbackBerthClass ?? "?")),
            _ => Loc.GetString("drydock-admin-impound-card-seat-none"),
        };

        ImpoundBodyLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
            $"{taken}\n[color={KeyHex}]{basis}[/color]\n[color={KeyHex}]{owner} {seat}[/color]"));
        ImpoundFeeLabel.Text = BankSystemExtensions.ToSpesoString(impound.Fee);
    }

    /// <summary>
    /// Every verb, every time, in one fixed order, so an admin learns the row once and can see the
    /// whole set of things the panel can do (user, 2026-09-12). A verb the state refuses is greyed
    /// rather than absent and its tooltip says why: the engine's hover path never reads
    /// <c>Disabled</c>, so a greyed button still shows one. The server checks each choice again on
    /// receipt regardless.
    /// </summary>
    private void BuildVerbs(DrydockAdminEuiState state, DrydockAdminShipDetailDto detail)
    {
        var ship = detail.Ship;

        // Impound takes a hull that is somewhere: berthed or in the world. On a terminal row the
        // state IS the verdict and the verb would overwrite it (on a sale it would also take
        // restore-from-sale with it, since that button reads State); in escrow the server refuses
        // until the offer is withdrawn; in the lot it has already happened.
        var impoundWhy = ship.State switch
        {
            "Impounded" => "drydock-admin-impound-why-impounded",
            "InEscrow" => "drydock-admin-impound-why-escrow",
            "Sold" or "Destroyed" or "Abandoned" => "drydock-admin-impound-why-terminal",
            _ => null,
        };
        var impound = Verb("drydock-admin-impound", "drydock-admin-impound-tooltip", "ButtonCaution", impoundWhy);
        impound.OnPressed += _ => OpenImpoundDialog(detail);
        VerbRow.AddChild(impound);

        // Release is one press out of the lot into the hull's last berth; Restore to… below is the
        // same exit with the berth chosen.
        var release = Verb("drydock-admin-release", "drydock-admin-release-tooltip", StyleNano.ButtonPrimary,
            ship.State == "Impounded" ? null : "drydock-admin-release-why");
        release.OnPressed += _ => _eui.Send(new DrydockAdminReleaseImpoundMessage { ShipGuid = ship.ShipGuid, Reason = Reason() });
        VerbRow.AddChild(release);

        // Restore puts a hull that is out, impounded, written off or abandoned back into a berth; a
        // stored one is home, an escrow one is spoken for, and a sold one comes back only through
        // the sale reversal, which decides about the money before anything else.
        var restoreWhy = ship.State switch
        {
            "Stored" => "drydock-admin-restore-to-why-stored",
            "InEscrow" => "drydock-admin-restore-to-why-escrow",
            "Sold" => "drydock-admin-restore-to-why-sold",
            _ => null,
        };
        var restoreTo = new DrydockMenuButton
        {
            Text = Loc.GetString("drydock-admin-restore-to"),
            StyleClasses = { "ButtonSquare" },
            MinWidth = 130,
            Margin = new Thickness(0, 0, 4, 0),
        };
        restoreTo.SetItems(restoreWhy == null
            ? BerthTargets(state, ship, berthId => _eui.Send(new DrydockAdminRestoreMessage
            {
                ShipGuid = ship.ShipGuid,
                BerthId = berthId,
                Reason = Reason(),
            }))
            : Array.Empty<DrydockMenuButton.Item>());
        // SetItems greys a menu with nothing to list, which is also an owner with no berths at all.
        if (restoreWhy == null && restoreTo.Disabled)
            restoreWhy = "drydock-admin-restore-to-why-no-berths";
        restoreTo.ToolTip = Loc.GetString(restoreWhy ?? "drydock-admin-restore-to-tooltip");
        VerbRow.AddChild(restoreTo);

        var sale = ship.State == "Sold" ? detail.LastSale : null;
        var restoreSale = Verb("drydock-admin-restore-from-sale", "drydock-admin-restore-from-sale-tooltip", StyleNano.ButtonPrimary,
            sale != null ? null
            : ship.State == "Sold" ? "drydock-admin-restore-from-sale-why-no-record"
            : "drydock-admin-restore-from-sale-why");
        if (sale != null)
            restoreSale.OnPressed += _ => OpenRestoreSaleDialog(state, ship, sale);
        VerbRow.AddChild(restoreSale);

        var escrow = detail.Escrow;
        var cancel = Verb("drydock-admin-cancel-offer", "drydock-admin-cancel-offer-tooltip", "ButtonCaution",
            escrow != null ? null : "drydock-admin-cancel-offer-why");
        if (escrow != null)
            cancel.OnPressed += _ => _eui.Send(new DrydockAdminCancelOfferMessage { TransferId = escrow.TransferId, Reason = Reason() });
        VerbRow.AddChild(cancel);

        var more = new DrydockMenuButton
        {
            Text = Loc.GetString("drydock-admin-more"),
            StyleClasses = { "ButtonSquare" },
            MinWidth = 34,
            AlignRight = true,
        };
        more.SetItems(OverflowItems(detail));
        VerbRow.AddChild(more);
    }

    /// <summary>
    /// The rare verbs. Promoting a revision lives here rather than in a panel of its own: the
    /// question an admin asks is what happened to the hull, and that is the timeline.
    /// </summary>
    private List<DrydockMenuButton.Item> OverflowItems(DrydockAdminShipDetailDto detail)
    {
        var ship = detail.Ship;

        // Vacating is the repair for a hull that is out and still shown in its slot. A stored ship
        // lives in its berth and is moved, never vacated; an escrow ship keeps its berth for the
        // offer to hand over. The entry says which, and the server refuses both regardless.
        var items = new List<DrydockMenuButton.Item>
        {
            new(Loc.GetString("drydock-admin-vacate"),
                VacateReason(ship),
                ship.BerthId != null && ship.State is not ("Stored" or "InEscrow"),
                () => _eui.Send(new DrydockAdminMoveMessage { ShipGuid = ship.ShipGuid, BerthId = null, Reason = Reason() })),
        };

        foreach (var revision in detail.Revisions)
        {
            if (!revision.HasBlob || revision.Revision == ship.CurrentRevision)
                continue;

            var captured = revision.Revision;
            items.Add(new DrydockMenuButton.Item(
                Loc.GetString("drydock-admin-promote", ("revision", captured)),
                revision.AppraisedValue is { } value
                    ? Loc.GetString("drydock-admin-revision-appraisal", ("value", value))
                    : $"{revision.CreatedAt:MM-dd HH:mm}",
                true,
                () => _eui.Send(new DrydockAdminPromoteRevisionMessage
                {
                    ShipGuid = ship.ShipGuid,
                    Revision = captured,
                    Reason = Reason(),
                })));
        }

        items.Add(new DrydockMenuButton.Item(
            Loc.GetString("drydock-admin-delete-ship"),
            ship.LiveThisRound ? Loc.GetString("drydock-admin-header-live") : null,
            !ship.LiveThisRound,
            () => _eui.Send(new DrydockAdminDeleteShipMessage { ShipGuid = ship.ShipGuid, Reason = Reason() })));

        return items;
    }

    /// <summary>Why Vacate is greyed, for the two states that hold a berth on purpose; null when it is offered.</summary>
    private static string? VacateReason(DrydockAdminShipDto ship)
    {
        if (ship.BerthId == null)
            return null;

        return ship.State switch
        {
            "Stored" => Loc.GetString("drydock-admin-vacate-stored"),
            "InEscrow" => Loc.GetString("drydock-admin-vacate-escrow"),
            _ => null,
        };
    }

    /// <summary>A verb button; greyed when <paramref name="why"/> names a reason, which then replaces its tooltip.</summary>
    private static Button Verb(string label, string tooltip, string? extraClass, string? why)
    {
        var button = new Button
        {
            Text = Loc.GetString(label),
            Margin = new Thickness(0, 0, 4, 0),
            ToolTip = Loc.GetString(why ?? tooltip),
            Disabled = why != null,
        };
        button.StyleClasses.Add("ButtonSquare");
        if (extraClass != null)
            button.StyleClasses.Add(extraClass);

        return button;
    }

    /// <summary>
    /// The owner's berths as targets for one action. An unusable berth stays listed and names why,
    /// because "there is nowhere to put it" is the answer the admin came for.
    /// </summary>
    private static List<DrydockMenuButton.Item> BerthTargets(DrydockAdminEuiState state, DrydockAdminShipDto ship, Action<int> pick)
    {
        var items = new List<DrydockMenuButton.Item>();

        foreach (var berth in state.OwnerBerths)
        {
            var occupied = berth.OccupantShipGuid != null && berth.OccupantShipGuid != ship.ShipGuid;
            var fits = ClassFits(ship.SizeClass, berth.MaxSizeClass);
            var id = berth.BerthId;

            items.Add(new DrydockMenuButton.Item(
                $"#{berth.BerthId} {berth.MaxSizeClass}",
                BerthReason(!occupied, fits),
                !occupied && fits,
                () => pick(id)));
        }

        return items;
    }

    private void BuildGrantMenu(Guid owner)
    {
        var items = Enum.GetValues<ShipSizeClass>()
            .Select(cls => new DrydockMenuButton.Item(cls.ToString(), null, true,
                () => _eui.Send(new DrydockAdminGrantBerthMessage { OwnerUserId = owner, MaxSizeClass = cls.ToString() })))
            .ToList();

        GrantBerthButton.SetItems(items);
    }

    /// <summary>The owner's berths, drawn by the same row the player's console uses, so both sides read alike.</summary>
    private void BuildBerths(DrydockAdminEuiState state, DrydockAdminShipDto ship)
    {
        var free = state.OwnerBerths.Count(b => b.OccupantShipGuid == null);
        BerthsTitle.Text = Loc.GetString("drydock-admin-berths-title", ("owner", ship.OwnerName ?? Short(ship.OwnerUserId)));
        BerthsCount.Text = Loc.GetString("drydock-admin-berths-count", ("free", free), ("total", state.OwnerBerths.Count));

        foreach (var berth in state.OwnerBerths)
        {
            // The player's row also draws escrow and a sale price; an admin berth carries neither,
            // so those arrive null and the row simply does not draw them.
            var info = new DrydockBerthInfo(
                berth.BerthId,
                berth.MaxSizeClass,
                sellValue: 0,
                upgradePrice: null,
                upgradeClass: null,
                occupantShipId: berth.OccupantShipGuid,
                occupantName: berth.OccupantName,
                occupantSizeClass: berth.OccupantSizeClass,
                occupantState: berth.OccupantState,
                occupantSellPrice: null,
                occupantTransferId: null,
                occupantOfferedTo: null,
                occupantOfferSecondsLeft: null);

            var row = new DrydockBerthRow(info, canRetrieve: false) { Margin = new Thickness(0, 0, 0, 3) };

            var empty = berth.OccupantShipGuid == null;
            var fits = ClassFits(ship.SizeClass, berth.MaxSizeClass);
            var id = berth.BerthId;

            row.MenuButton.SetItems(new List<DrydockMenuButton.Item>
            {
                new(Loc.GetString("drydock-admin-berth-restore-here"),
                    BerthReason(empty, fits),
                    empty && fits && ship.State is not ("Stored" or "InEscrow" or "Sold"),
                    () => _eui.Send(new DrydockAdminRestoreMessage { ShipGuid = ship.ShipGuid, BerthId = id, Reason = Reason() })),
                new(Loc.GetString("drydock-admin-berth-move-here"),
                    BerthReason(empty, fits),
                    empty && fits && ship.State == "Stored",
                    () => _eui.Send(new DrydockAdminMoveMessage { ShipGuid = ship.ShipGuid, BerthId = id, Reason = Reason() })),
                new(Loc.GetString("drydock-admin-berth-delete"),
                    empty ? null : Loc.GetString("drydock-admin-berth-occupied"),
                    empty,
                    () => _eui.Send(new DrydockAdminDeleteBerthMessage { BerthId = id })),
            });

            BerthContainer.AddChild(row);
        }
    }

    private static string? BerthReason(bool empty, bool fits)
    {
        if (!empty)
            return Loc.GetString("drydock-admin-berth-occupied");

        return fits ? null : Loc.GetString("drydock-admin-berth-too-small");
    }

    /// <summary>
    /// The hull's whole life: a fixed timestamp column, then what happened, actor before subject.
    /// A refused-access row is the only one a console never produces, so it is coloured and says
    /// so on hover.
    /// </summary>
    private void BuildTimeline(DrydockAdminShipDetailDto detail)
    {
        foreach (var entry in detail.Timeline)
        {
            var refused = entry.Action == "AccessRefused";

            var when = new Label
            {
                Text = $"{entry.At:MM-dd HH:mm}",
                FontOverride = _small,
                Modulate = Dim,
                MinWidth = 110,
                VerticalAlignment = VAlignment.Top,
            };

            var msg = new FormattedMessage();
            msg.PushColor(refused ? Sold : Color.White);
            msg.AddText(Loc.GetString($"drydock-admin-action-{entry.Action}"));
            msg.Pop();

            msg.AddText($" {entry.ActorName ?? (entry.ActorUserId is { } a ? Short(a) : "system")}");
            if (entry.SubjectUserId is { } subject && entry.SubjectUserId != entry.ActorUserId)
                msg.AddText($" → {entry.SubjectName ?? Short(subject)}");

            msg.PushColor(Key);
            if (entry.BerthId is { } berth)
                msg.AddText($" · #{berth}");
            if (entry.Revision is { } rev)
                msg.AddText($" · r{rev}");
            if (entry.RoundId is { } round)
                msg.AddText($" · round {round}");
            if (!string.IsNullOrEmpty(entry.Reason))
                msg.AddText($" · {entry.Reason}");
            msg.Pop();

            var what = new RichTextLabel { HorizontalExpand = true };
            what.SetMessage(msg);

            var line = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 4),
            };
            line.AddChild(when);
            line.AddChild(what);

            var rule = new PanelContainer { PanelOverride = TimelineRule(), HorizontalExpand = true };
            rule.AddChild(line);
            if (refused)
                rule.ToolTip = Loc.GetString("drydock-admin-refused-tooltip");

            TimelineContainer.AddChild(rule);
        }
    }

    /// <summary>
    /// The fee is quoted against the current revision's appraisal, which is the figure the server
    /// charges against for a berthed hull; the dialog says when the hull is live and will be
    /// appraised again. The dialog's own reason is what the owner reads, and the panel's inline
    /// reason box stands in when it is left empty.
    /// </summary>
    private void OpenImpoundDialog(DrydockAdminShipDetailDto detail)
    {
        var ship = detail.Ship;
        var appraisal = detail.Revisions.FirstOrDefault(r => r.Revision == ship.CurrentRevision)?.AppraisedValue;

        var dialog = new DrydockImpoundDialog(ship, appraisal, _lastState?.ImpoundDefaultPercent ?? 50, (percent, redeemable, reason) =>
            _eui.Send(new DrydockAdminImpoundMessage
            {
                ShipGuid = ship.ShipGuid,
                FeePercent = percent,
                Redeemable = redeemable,
                Reason = reason ?? Reason(),
            }));

        dialog.OpenCentered();
    }

    private void OpenRestoreSaleDialog(DrydockAdminEuiState state, DrydockAdminShipDto ship, DrydockAdminSaleDto sale)
    {
        var targets = state.OwnerBerths
            .Where(b => b.OccupantShipGuid == null && ClassFits(ship.SizeClass, b.MaxSizeClass))
            .Select(b => b.BerthId)
            .ToList();

        var dialog = new DrydockRestoreSaleDialog(ship, sale, targets, ship.LastBerthId, (berthId, takeMoney, reason) =>
            _eui.Send(new DrydockAdminRestoreFromSaleMessage
            {
                ShipGuid = ship.ShipGuid,
                BerthId = berthId,
                TakeMoneyBack = takeMoney,
                Reason = reason,
            }));

        dialog.OpenCentered();
    }

    // ---------------------------------------------------------------- Shared reads

    /// <summary>
    /// The same rule the player's console applies: a berth holds its class or smaller, and text
    /// that parses as neither is "does not fit" rather than a crash. The server checks it again.
    /// </summary>
    private static bool ClassFits(string? shipClass, string berthClass)
    {
        return Enum.TryParse<ShipSizeClass>(shipClass, out var ship)
            && Enum.TryParse<ShipSizeClass>(berthClass, out var berth)
            && berth >= ship;
    }

    private static string Short(Guid id) => id.ToString("N")[..8];
}
