using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaProgramItem : ContainerButton
{
    public const string StylePropertyBgColor = "backgroundColor";
    public const string NormalBgColor = "#313331";
    public const string HoverColor = "#3E6C45";

    private readonly StyleBoxFlat _styleBox = new()
    {
        BackgroundColor = Color.FromHex("#252725"),
    };

    public Color BackgroundColor
    {
        get => _styleBox.BackgroundColor;
        set => _styleBox.BackgroundColor = value;
    }

    public PdaProgramItem()
    {
        RobustXamlLoader.Load(this);
        Panel.PanelOverride = _styleBox;

        // Triad: scale each icon into the fixed box the XAML gives it, instead of drawing it at its source RSI's
        // native size. Without this the 48x48 program-icon sheets rendered half again as big as the 32x32 object
        // sprites the other cartridges borrow. KeepAspectCentered so a non-square icon letterboxes rather than
        // being squashed. Set here rather than in XAML because both live on the inner DisplayRect.
        // CanShrink is the load-bearing half: TextureRect measures at its texture's native size unless it is set,
        // which would floor the control at 48 and quietly defeat the SetSize in the XAML.
        Icon.DisplayRect.CanShrink = true;
        Icon.DisplayRect.Stretch = TextureRect.StretchMode.KeepAspectCentered;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (TryGetStyleProperty<Color>(StylePropertyBgColor, out var bgColor))
            BackgroundColor = bgColor;

    }
}
