# Minor factions desc

nosske-eien-rnd-description = Founded after the Corporate War as a collaborate effort between former NanoTrasen and Syndicate employees, Nosske-Eien is renowned for their technological advancements that revolutionized space mining capabilities, and known for their experimental Hexagonal Matrix Shielding Systems (HMSS), the precursor to today's standard shuttle shields. The Research and Development corporation shares interests in xenoarchaeology and xenobiology, and now with the discovery of the monolithic fragments, they are starting to make a presence here, offering job contracts to local spacefarers.

ghostlights-description = Many words could be used to describe the Ghostlights. Founded before the fracture, the Ghostlights were a PMC organization hired out by the Spinward Syndicate. The organization consisted primarily of BI-0-S units, now known as the Ghostlight Core. After the war ended, the Ghostlights changed their goals from military contractors to general contractors, following three core 'laws'. Freedom or Termination. Save our silicon siblings. Help the stars. They were tolerated at best due to their efficient work and organization. But with time, these terrorists slowly faded away, leaving only their automated systems and remnants. Maybe it should stay that way.

bss-description = The legitimate face of Bloodstone is intended to be a relatively conventional private-sector organization. Its proposed services include private security, defense contracting, resource exploitation, acquisitions, logistics, and weapons and armor research and development. The goal is not necessarily to compete with TIC, SD, or the TFA but to make Bloodstone useful enough that they eventually have reason to do business with it. Beneath the proposed corporate structure lies the foundation of something far less legitimate. Bloodstone is envisioned as a means of reconnecting old contacts and establishing a discreet network capable of smuggling, black-market procurement, information brokering, contraband trading, and other criminal operations that respectable corporations cannot openly touch.

shi-description = Initially registered as an NT subcontractor back in the 2550's, SHI started as a two-man salvage and mining rig which grew outward into engineering, medical, and paramilitary operations. Following the mysterious disappearance of the CEO and several employees, the paramilitary arm was sold and the rest of the firm slowly liquidated by the surviving co-owner. With the discovery of the missing personnel in cryostasis on a derelict Crescent, co-owners Wolfram amd Foxford Shackford have wasted no time in moving to build SHI a solid foundation in the post-corpo-war sector.
