# Triad Defense Force ranks
- type: rank
  id: RankJuniorEnforcer
  name: Junior Enforcer
  prefix: Jr. Enf.
  paygrade: TDF-1

- type: rank
  id: RankEnforcer
  name: Enforcer
  prefix: Enf.
  paygrade: TDF-2

- type: rank
  id: RankSeniorEnforcer
  name: Senior Enforcer
  prefix: Sr. Enf.
  paygrade: TDF-3

- type: rank
  id: RankLieutenant
  name: Lieutenant Enforcer
  prefix: Lt. Enf.
  paygrade: TDF-4

- type: rank
  id: RankChiefEnforcer
  name: Chief Enforcer
  prefix: Chief Enf.
  paygrade: TDF-5
