using System;
using System.Collections.Generic;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared._Triad.Shipyard.Admin;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._Triad.Shipyard.Admin;

// Admin-log-style tamper panel. One window, two views (Audit feed / Permits) selected by the EUI
// state's View. Each event renders as a colour-coded, wrapping RichTextLabel row of labelled,
// comma-separated fields (Name="...", Key=..., Ship=..., Player="...") on a lighter panel band,
// divided by HSeparators, so the data reads as structured info like the engine admin logs.
// Selecting a row drives the footer, which folds in trusted-key management (trust/untrust the row's
// key) and one-click permit granting (the row already carries the player + full ship hash).
//
// Filtering is round-centric and server-side: the feed is scoped to one game round (prev/next arrows
// walk rounds), with optional round-time window, player, ship-name, and per-action (event type)
// filters. The server does the filtering, so the count and paging reflect it.
//
// Strings are built with interpolation, never string.Format: a multi-arg string.Format binds to the
// SDK-10 params ReadOnlySpan<object?> overload, whose InlineArrayAsReadOnlySpan helper fails the
// Robust client sandbox's ILVerify and crashes the Release client at load. FormattedMessage.AddText
// also keeps user-controlled text (ship/player names) literal, so it cannot inject colour markup.
[GenerateTypedNameReferences]
public sealed partial class TriadTamperAdminWindow : DefaultWindow
{
    private const int AuditPageSize = 50;

    // Lighter panel band used for each entry row; selection overrides it with a distinct accent.
    private const string RowPanelClass = "PanelBackgroundBaseLight";

    private static readonly Color InfoColor = Color.FromHex("#6ec06e");
    private static readonly Color NoticeColor = Color.FromHex("#d9a441");
    private static readonly Color RejectColor = Color.FromHex("#cf4f4f");
    private static readonly Color AdminColor = Color.FromHex("#6fa8dc");

    // Dim grey for field labels and the timestamp, so the values read as the primary content.
    private static readonly Color LabelColor = Color.FromHex("#8d8d8d");

    private static readonly StyleBoxFlat SelectedBox = new() { BackgroundColor = Color.FromHex("#3e5e82") };

    private readonly TriadTamperAdminEui _eui;
    private TriadTamperAdminEuiState? _lastState;
    private int _currentPage;

    private int _selectedRound;
    private int _currentRound;

    // Player filter dropdown options, parallel to the OptionButton items: index 0 is "All players"
    // (null), the rest are the round's players. Held so a selected id maps back to a player guid.
    private readonly List<Guid?> _playerOptions = new();
    private Guid? _selectedPlayer;

    // Action filter checkboxes, each paired with the event type name(s) it covers. Most boxes map to a
    // single type; the Rejected box covers the generic LoadRejected plus its reason-specific variants
    // (unsigned / invalid signature / foreign key). All checked = no filter.
    private readonly List<(CheckBox Box, string[] EventTypes)> _actionBoxes;

    private readonly List<FeedRow> _feedRows = new();
    private AuditRowDto? _selectedRow;

    public TriadTamperAdminWindow(TriadTamperAdminEui eui)
    {
        RobustXamlLoader.Load(this);
        _eui = eui;

        ApplyButton.OnPressed += _ => RequestAuditPage(0);
        PrevPageButton.OnPressed += _ => RequestAuditPage(Math.Max(0, _currentPage - 1));
        NextPageButton.OnPressed += _ => RequestAuditPage(Math.Min(LastAuditPageIndex(), _currentPage + 1));

        // Round arrows step the round and re-query from page 0; the server clamps to [1, current].
        PrevRoundButton.OnPressed += _ => { _selectedRound -= 1; RequestAuditPage(0); };
        NextRoundButton.OnPressed += _ => { _selectedRound += 1; RequestAuditPage(0); };

        PlayerDropdown.OnItemSelected += OnPlayerSelected;

        _actionBoxes = new List<(CheckBox, string[])>
        {
            (ActionSaveSigned, new[] { "SaveSigned" }),
            (ActionVerifiedTrusted, new[] { "LoadVerifiedTrusted" }),
            (ActionVerifiedUntrusted, new[] { "LoadVerifiedUntrusted" }),
            (ActionUnsigned, new[] { "LoadUnsigned" }),
            (ActionInvalidSignature, new[] { "LoadInvalidSignature" }),
            (ActionMigrated, new[] { "LoadMigrated" }),
            // The Rejected box catches every blocked load: the generic reject plus the reason variants.
            (ActionRejected, new[]
            {
                "LoadRejected",
                "LoadRejectedUnsigned",
                "LoadRejectedInvalidSignature",
                "LoadRejectedForeignKey",
            }),
            (ActionPermitGranted, new[] { "PermitGranted" }),
            (ActionPermitRevoked, new[] { "PermitRevoked" }),
        };
        foreach (var (box, _) in _actionBoxes)
            box.Pressed = true;

        GrantPermitButton.OnPressed += _ => GrantPermitForSelected();
    }

    public void UpdateState(TriadTamperAdminEuiState state)
    {
        // A same-page refresh (the live tail re-pulling page 0, or a trust/permit action) keeps the
        // admin's place; navigating to another page or applying filters resets it.
        var samePageRefresh = state.AuditPage_Index == _currentPage;

        _lastState = state;
        _currentPage = state.AuditPage_Index;

        RebuildFeed(state, samePageRefresh);
    }

    // Append a dim ", label=" tag followed by its value, so fields are self-describing and
    // comma-separated. Caller writes the first token (timestamp/event or Player) without a comma.
    private static void Field(FormattedMessage msg, string label, string value)
    {
        msg.PushColor(LabelColor);
        msg.AddText($", {label}=");
        msg.Pop();
        msg.AddText(value);
    }

    private static string ShortHash(string hex, int len = 12)
        => hex.Length <= len ? hex : $"{hex[..len]}…";

    // ---------------------------------------------------------------- Audit feed

    private void RebuildFeed(TriadTamperAdminEuiState state, bool preservePlace)
    {
        UpdateRoundControls(state);
        RebuildPlayerDropdown(state);

        // Capture place before tearing the feed down, so a live refresh doesn't yank an admin who's
        // mid-action on a selected row or reading further down the page.
        var previouslySelectedId = preservePlace ? _selectedRow?.Id : null;
        var scroll = preservePlace ? FeedScroll.GetScrollValue() : default;

        FeedContainer.RemoveAllChildren();
        _feedRows.Clear();
        _selectedRow = null;

        foreach (var r in state.AuditPage)
        {
            var msg = new FormattedMessage();
            msg.PushColor(LabelColor);
            msg.AddText($"{r.At:HH:mm:ss}: ");
            msg.Pop();
            // Whole sentence tinted by the outcome's severity, like the engine admin-log feed.
            msg.PushColor(Bucket(r.EventType));
            msg.AddText(Describe(r));
            msg.Pop();

            var rich = new RichTextLabel { HorizontalExpand = true, Margin = new Thickness(6, 3) };
            rich.SetMessage(msg);

            var highlight = new PanelContainer();
            highlight.StyleClasses.Add(RowPanelClass);
            highlight.AddChild(rich);

            var button = new ContainerButton { HorizontalExpand = true };
            button.AddChild(highlight);

            var captured = r;
            button.OnPressed += _ => Select(captured);

            var separator = new HSeparator();

            _feedRows.Add(new FeedRow
            {
                Row = r,
                Highlight = highlight,
                Button = button,
                Separator = separator,
            });
            FeedContainer.AddChild(button);
            FeedContainer.AddChild(separator);
        }

        CountLabel.Text = $"Showing {state.AuditPage.Count} on this page · {state.AuditTotalCount} match the filter";
        UpdatePager(state);

        // Re-select the same entry by id if it survived into the refreshed page (Select also redraws
        // the footer); otherwise fall back to the empty-selection footer.
        AuditRowDto? reselect = null;
        if (previouslySelectedId is { } id)
        {
            foreach (var r in state.AuditPage)
            {
                if (r.Id == id)
                {
                    reselect = r;
                    break;
                }
            }
        }

        if (reselect != null)
            Select(reselect);
        else
            UpdateFooter();

        if (preservePlace)
            FeedScroll.SetScrollValue(scroll);

        RebuildAuditPermits(state);
    }

    private void UpdateRoundControls(TriadTamperAdminEuiState state)
    {
        _selectedRound = state.SelectedRoundId;

        RoundLabel.Text = $"Round {state.SelectedRoundId}";
        PrevRoundButton.Disabled = state.SelectedRoundId <= 1;
        NextRoundButton.Disabled = state.SelectedRoundId >= state.CurrentRoundId;
    }

    // Repopulate the player dropdown from the round's players, keeping the current selection if that
    // player is still in the round and resetting to "All players" otherwise.
    private void RebuildPlayerDropdown(TriadTamperAdminEuiState state)
    {
        PlayerDropdown.Clear();
        _playerOptions.Clear();

        PlayerDropdown.AddItem("All players", 0);
        _playerOptions.Add(null);

        var selectedIndex = 0;
        var id = 1;
        foreach (var p in state.RoundPlayers)
        {
            var label = string.IsNullOrEmpty(p.Name) ? p.UserId.ToString() : p.Name;
            PlayerDropdown.AddItem(label, id);
            _playerOptions.Add(p.UserId);
            if (_selectedPlayer == p.UserId)
                selectedIndex = id;
            id++;
        }

        // Selected player dropped out of the round (e.g. after a round change): fall back to "All".
        if (selectedIndex == 0)
            _selectedPlayer = null;

        PlayerDropdown.SelectId(selectedIndex);
    }

    private void OnPlayerSelected(OptionButton.ItemSelectedEventArgs args)
    {
        PlayerDropdown.SelectId(args.Id);
        _selectedPlayer = args.Id >= 0 && args.Id < _playerOptions.Count ? _playerOptions[args.Id] : null;
    }

    // Player / admin display name, falling back to the raw id (short, for the admin) when no name
    // resolved. Shared by the in-line strip and the full Permits view.
    private static string PlayerDisplay(PermitDto p)
        => string.IsNullOrEmpty(p.PlayerName) ? p.PlayerUserId.ToString() : p.PlayerName;

    private static string AdminDisplay(PermitDto p)
        => string.IsNullOrEmpty(p.AdminName) ? ShortHash(p.GrantedByAdmin.ToString(), 8) : p.AdminName;

    // Compact active-permits strip shown under the audit feed: Time, Player, Admin, Revoke. Lets an
    // admin grant from a rejected-load row and immediately see / revoke the grant without switching view.
    private void RebuildAuditPermits(TriadTamperAdminEuiState state)
    {
        AuditPermitsContainer.RemoveAllChildren();

        foreach (var p in state.Permits)
        {
            var msg = new FormattedMessage();
            msg.PushColor(LabelColor);
            msg.AddText($"{p.GrantedAt:HH:mm:ss}  Player=");
            msg.Pop();
            msg.AddText($"\"{PlayerDisplay(p)}\"");
            Field(msg, "Admin", $"\"{AdminDisplay(p)}\"");
            if (!string.IsNullOrEmpty(p.Notes))
                Field(msg, "Notes", $"\"{p.Notes}\"");

            var rich = new RichTextLabel { HorizontalExpand = true, Margin = new Thickness(6, 2) };
            rich.SetMessage(msg);

            var captured = p;
            var revoke = new Button { Text = "Revoke" };
            revoke.OnPressed += _ => _eui.Send(new TriadTamperAdminRevokePermitMessage
            {
                Target = captured.PlayerUserId,
            });

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(rich);
            row.AddChild(revoke);
            AuditPermitsContainer.AddChild(row);
        }

        if (state.Permits.Count == 0)
        {
            var rich = new RichTextLabel { Margin = new Thickness(6, 2) };
            var msg = new FormattedMessage();
            msg.AddText("No active permits.");
            rich.SetMessage(msg);
            AuditPermitsContainer.AddChild(rich);
        }
    }

    private void Select(AuditRowDto row)
    {
        _selectedRow = row;
        foreach (var fr in _feedRows)
            fr.Highlight.PanelOverride = fr.Row.Id == row.Id ? SelectedBox : null;
        UpdateFooter();
    }

    private void UpdateFooter()
    {
        var r = _selectedRow;
        if (r == null)
        {
            SelectedLabel.Text = "Select an entry to grant a permit.";
            GrantPermitButton.Disabled = true;
            return;
        }

        // Permit-action rows (PermitGranted/PermitRevoked) carry no ship and an admin actor, not a
        // loadable ship. Granting off one would re-grant for that player against a row that shows no
        // ship, so disable the affordance and say why instead of rendering a dangling Ship=.
        if (r.EventType is "PermitGranted" or "PermitRevoked")
        {
            SelectedLabel.Text = "Selected a permit action (no ship to grant against).";
            GrantPermitButton.Disabled = true;
            return;
        }

        var ship = string.IsNullOrEmpty(r.ShipName) ? "(unnamed)" : r.ShipName;
        var keyDesc = r.PubkeyFingerprint is { } fp ? ShortHash(fp) : "(unsigned)";
        SelectedLabel.Text = $"Selected: Name=\"{ship}\", Key={keyDesc}, Ship={ShortHash(r.ShipHashHex)}";

        GrantPermitButton.Disabled = false;
    }

    private void GrantPermitForSelected()
    {
        if (_selectedRow is not { } r)
            return;

        // The audit row already holds the player, so a permit can be granted straight from the row.
        _eui.Send(new TriadTamperAdminGrantPermitMessage
        {
            Target = r.PlayerUserId,
            Notes = string.IsNullOrWhiteSpace(NotesInput.Text) ? null : NotesInput.Text,
        });
    }

    private void RequestAuditPage(int page)
    {
        _eui.Send(new TriadTamperAdminRequestAuditPageMessage
        {
            Page = page,
            PageSize = AuditPageSize,
            RoundId = _selectedRound,
            RoundTimeFromSeconds = ParseRoundTimeSeconds(RoundTimeFromInput.Text),
            RoundTimeToSeconds = ParseRoundTimeSeconds(RoundTimeToInput.Text),
            PlayerUserId = _selectedPlayer,
            EventTypes = SelectedActions(),
            ShipNameContains = string.IsNullOrWhiteSpace(ShipNameInput.Text) ? null : ShipNameInput.Text,
        });
    }

    // HH:MM:SS (or MM:SS) into seconds; empty / unparseable / out-of-range means an unbounded side.
    // TimeSpan.TryParse accepts negatives ("-1:00:00") and values that overflow int seconds; either
    // would silently corrupt the round-time window (blank or flooded feed), so clamp to
    // [0, int.MaxValue] and treat anything outside as "no bound".
    private static int? ParseRoundTimeSeconds(string text)
    {
        if (!TimeSpan.TryParse(text, out var ts))
            return null;
        var secs = ts.TotalSeconds;
        if (secs < 0 || secs > int.MaxValue)
            return null;
        return (int)secs;
    }

    // The checked action event types, or null when every box is checked (= no action filter).
    private List<string>? SelectedActions()
    {
        var selected = new List<string>();
        var allChecked = true;
        foreach (var (box, types) in _actionBoxes)
        {
            if (box.Pressed)
                selected.AddRange(types);
            else
                allChecked = false;
        }

        return allChecked ? null : selected;
    }

    private void UpdatePager(TriadTamperAdminEuiState state)
    {
        var totalPages = Math.Max(1, (state.AuditTotalCount + AuditPageSize - 1) / AuditPageSize);
        PageLabel.Text = $"Page {state.AuditPage_Index + 1} / {totalPages}";
        PrevPageButton.Disabled = state.AuditPage_Index <= 0;
        NextPageButton.Disabled = state.AuditPage_Index + 1 >= totalPages;
    }

    private int LastAuditPageIndex()
        => _lastState == null ? 0 : Math.Max(0, (_lastState.AuditTotalCount - 1) / AuditPageSize);

    // Prose description of one audit row, mirroring the engine admin-log style: entities read as
    // "Name" (shorthash) in a natural sentence rather than key="value" tags. Bucket() tints the line
    // by severity; the event type is carried by the verb (and stays a filter dimension, not printed).
    private static string Describe(AuditRowDto r)
    {
        var who = string.IsNullOrEmpty(r.PlayerName) ? r.PlayerUserId.ToString() : r.PlayerName;
        var ship = string.IsNullOrEmpty(r.ShipName)
            ? $"ship {ShortHash(r.ShipHashHex)}"
            : $"\"{r.ShipName}\" ({ShortHash(r.ShipHashHex)})";
        var key = r.PubkeyFingerprint is { } fp
            ? $"key {ShortHash(fp)}"
            : "unsigned";
        var appraised = r.SaveTimeAppraisal is { } a ? $", appraised {a}" : "";
        var admin = string.IsNullOrEmpty(r.AdminName) ? "an admin" : r.AdminName;

        return r.EventType switch
        {
            "SaveSigned" => $"{who} saved {ship}, {key}{appraised}",
            "LoadVerifiedTrusted" => $"{who} loaded {ship}, verified with {key}{appraised}",
            "LoadVerifiedUntrusted" => $"{who} loaded {ship}, verified with {key}{appraised}",
            "LoadUnsigned" => $"{who} loaded {ship}, unsigned",
            "LoadInvalidSignature" => $"{who} loaded {ship}, invalid signature",
            "LoadMigrated" => $"{who} loaded {ship} under a migration permit{appraised}",
            "LoadRejected" => $"{who} was blocked loading {ship}",
            "LoadRejectedUnsigned" => $"{who} was blocked loading {ship} (unsigned)",
            "LoadRejectedInvalidSignature" => $"{who} was blocked loading {ship} (invalid signature)",
            "LoadRejectedForeignKey" => $"{who} was blocked loading {ship} (signed with an unrecognized key)",
            "PermitGranted" => $"{admin} granted {who} a permit",
            "PermitRevoked" => $"{admin} revoked {who}'s permit",
            _ => $"{who}: {r.EventType} {ship}",
        };
    }

    private static Color Bucket(string eventType) => eventType switch
    {
        "SaveSigned" or "LoadVerifiedTrusted" => InfoColor,
        "LoadVerifiedUntrusted" or "LoadUnsigned" or "LoadMigrated" => NoticeColor,
        "LoadInvalidSignature" or "LoadRejected"
            or "LoadRejectedUnsigned" or "LoadRejectedInvalidSignature" or "LoadRejectedForeignKey" => RejectColor,
        "PermitGranted" or "PermitRevoked" => AdminColor,
        _ => Color.Gray,
    };

    private sealed class FeedRow
    {
        public AuditRowDto Row = default!;
        public PanelContainer Highlight = default!;
        public ContainerButton Button = default!;
        public Control Separator = default!;
    }
}
