- type: department
  id: Infrastructure
  name: department-Infrastructure
  description: department-Infrastructure-description
  color: "#c59a3b"
  weight: 100
  roles:
  - PlantManager
  - PlantTechnician

- type: department
  id: Security
  name: department-TriadDefenseForce
  description: department-TriadDefenseForce-description
  color: "#FFD580"
  weight: 120
  roles:
  - TdfChiefEnforcer
  - TdfLieutenant
  - TdfPatrolTeamLeader
  - TdfEnforcer
  - TdfMedic
  - TdfCadet

- type: department
  id: SolarianDirective
  name: department-SolarianDirective
  description: department-TriadDefenseForce-description # TODO, desc
  color: "#556cf1"
  weight: 120
  # roles: TODO
  editorHidden: true # TODO
